// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 36b0f7d02af6

package operations

import (
	"github.com/cloudsmith-io/cloudsmith-go-v2/internal/utils"
	"github.com/cloudsmith-io/cloudsmith-go-v2/models/components"
)

type MetadataPackagesCreateRequest struct {
	// The `slug_perm` of the package.
	PackageSlugPerm string                                  `pathParam:"style=simple,explode=false,name=package_slug_perm"`
	Body            components.ArtifactMetadataWriteRequest `request:"mediaType=application/json"`
}

func (m *MetadataPackagesCreateRequest) GetPackageSlugPerm() string {
	if m == nil {
		return ""
	}
	return m.PackageSlugPerm
}

func (m *MetadataPackagesCreateRequest) GetBody() components.ArtifactMetadataWriteRequest {
	if m == nil {
		return components.ArtifactMetadataWriteRequest{}
	}
	return m.Body
}

type MetadataPackagesCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The metadata entry was created successfully.
	ArtifactMetadataWrite *components.ArtifactMetadataWrite
}

func (m MetadataPackagesCreateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MetadataPackagesCreateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MetadataPackagesCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if m == nil {
		return components.HTTPMetadata{}
	}
	return m.HTTPMeta
}

func (m *MetadataPackagesCreateResponse) GetArtifactMetadataWrite() *components.ArtifactMetadataWrite {
	if m == nil {
		return nil
	}
	return m.ArtifactMetadataWrite
}
