// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/cloudsmith-io/cloudsmith-go-v2/models/components"
)

type MetadataValidateCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (m *MetadataValidateCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if m == nil {
		return components.HTTPMetadata{}
	}
	return m.HTTPMeta
}
