// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1708097e1747

package operations

import (
	"github.com/cloudsmith-io/cloudsmith-go-v2/models/components"
)

type MetadataPackagesDestroyRequest struct {
	// The `slug_perm` of the package.
	PackageSlugPerm string `pathParam:"style=simple,explode=false,name=package_slug_perm"`
	// The `slug_perm` of the metadata entry.
	SlugPerm string `pathParam:"style=simple,explode=false,name=slug_perm"`
}

func (m *MetadataPackagesDestroyRequest) GetPackageSlugPerm() string {
	if m == nil {
		return ""
	}
	return m.PackageSlugPerm
}

func (m *MetadataPackagesDestroyRequest) GetSlugPerm() string {
	if m == nil {
		return ""
	}
	return m.SlugPerm
}

type MetadataPackagesDestroyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (m *MetadataPackagesDestroyResponse) GetHTTPMeta() components.HTTPMetadata {
	if m == nil {
		return components.HTTPMetadata{}
	}
	return m.HTTPMeta
}
