// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f4054dc349c2

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/cloudsmith-io/cloudsmith-go-v2/internal/utils"
	"github.com/cloudsmith-io/cloudsmith-go-v2/models/components"
)

// Classification - Filter results by metadata classification.
//
// * `UNKNOWN` - Unknown
// * `INTRINSIC` - Intrinsic
// * `SECURITY` - Security
// * `PROVENANCE` - Provenance
// * `SBOM` - SBOM
// * `GENERIC` - Generic
type Classification string

const (
	ClassificationUnknown    Classification = "UNKNOWN"
	ClassificationIntrinsic  Classification = "INTRINSIC"
	ClassificationSecurity   Classification = "SECURITY"
	ClassificationProvenance Classification = "PROVENANCE"
	ClassificationSbom       Classification = "SBOM"
	ClassificationGeneric    Classification = "GENERIC"
)

func (e Classification) ToPointer() *Classification {
	return &e
}
func (e *Classification) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "UNKNOWN":
		fallthrough
	case "INTRINSIC":
		fallthrough
	case "SECURITY":
		fallthrough
	case "PROVENANCE":
		fallthrough
	case "SBOM":
		fallthrough
	case "GENERIC":
		*e = Classification(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Classification: %v", v)
	}
}

// SourceKind - Filter results by metadata source kind.
//
// * `UNKNOWN` - Unknown
// * `SYSTEM` - System
// * `UPSTREAM` - Upstream
// * `CUSTOM` - Custom
// * `THIRD_PARTY` - Third Party
type SourceKind string

const (
	SourceKindUnknown    SourceKind = "UNKNOWN"
	SourceKindSystem     SourceKind = "SYSTEM"
	SourceKindUpstream   SourceKind = "UPSTREAM"
	SourceKindCustom     SourceKind = "CUSTOM"
	SourceKindThirdParty SourceKind = "THIRD_PARTY"
)

func (e SourceKind) ToPointer() *SourceKind {
	return &e
}
func (e *SourceKind) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "UNKNOWN":
		fallthrough
	case "SYSTEM":
		fallthrough
	case "UPSTREAM":
		fallthrough
	case "CUSTOM":
		fallthrough
	case "THIRD_PARTY":
		*e = SourceKind(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceKind: %v", v)
	}
}

type MetadataPackagesListRequest struct {
	// Filter results by metadata classification.
	//
	// * `UNKNOWN` - Unknown
	// * `INTRINSIC` - Intrinsic
	// * `SECURITY` - Security
	// * `PROVENANCE` - Provenance
	// * `SBOM` - SBOM
	// * `GENERIC` - Generic
	Classification *Classification `queryParam:"style=form,explode=true,name=classification"`
	// The `slug_perm` of the package.
	PackageSlugPerm string `pathParam:"style=simple,explode=false,name=package_slug_perm"`
	// A page number within the paginated result set.
	Page *int64 `queryParam:"style=form,explode=true,name=page"`
	// Number of results to return per page.
	PageSize *int64 `queryParam:"style=form,explode=true,name=page_size"`
	// Filter results by metadata source kind.
	//
	// * `UNKNOWN` - Unknown
	// * `SYSTEM` - System
	// * `UPSTREAM` - Upstream
	// * `CUSTOM` - Custom
	// * `THIRD_PARTY` - Third Party
	SourceKind *SourceKind `queryParam:"style=form,explode=true,name=source_kind"`
}

func (m *MetadataPackagesListRequest) GetClassification() *Classification {
	if m == nil {
		return nil
	}
	return m.Classification
}

func (m *MetadataPackagesListRequest) GetPackageSlugPerm() string {
	if m == nil {
		return ""
	}
	return m.PackageSlugPerm
}

func (m *MetadataPackagesListRequest) GetPage() *int64 {
	if m == nil {
		return nil
	}
	return m.Page
}

func (m *MetadataPackagesListRequest) GetPageSize() *int64 {
	if m == nil {
		return nil
	}
	return m.PageSize
}

func (m *MetadataPackagesListRequest) GetSourceKind() *SourceKind {
	if m == nil {
		return nil
	}
	return m.SourceKind
}

type MetadataPackagesListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A paginated collection of metadata entries for the package.
	PaginatedArtifactMetadataReadList *components.PaginatedArtifactMetadataReadList
}

func (m MetadataPackagesListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MetadataPackagesListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MetadataPackagesListResponse) GetHTTPMeta() components.HTTPMetadata {
	if m == nil {
		return components.HTTPMetadata{}
	}
	return m.HTTPMeta
}

func (m *MetadataPackagesListResponse) GetPaginatedArtifactMetadataReadList() *components.PaginatedArtifactMetadataReadList {
	if m == nil {
		return nil
	}
	return m.PaginatedArtifactMetadataReadList
}
