// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/cloudsmith-io/cloudsmith-go-v2/models/components"
)

type PackagesMetadataDestroyRequest struct {
	// The `slug_perm` of the package.
	PackageSlugPerm string `pathParam:"style=simple,explode=false,name=package_slug_perm"`
	// The `slug_perm` of the metadata entry.
	SlugPerm string `pathParam:"style=simple,explode=false,name=slug_perm"`
}

func (p *PackagesMetadataDestroyRequest) GetPackageSlugPerm() string {
	if p == nil {
		return ""
	}
	return p.PackageSlugPerm
}

func (p *PackagesMetadataDestroyRequest) GetSlugPerm() string {
	if p == nil {
		return ""
	}
	return p.SlugPerm
}

type PackagesMetadataDestroyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (p *PackagesMetadataDestroyResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}
