// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/cloudsmith-io/cloudsmith-go-v2/internal/utils"
	"github.com/cloudsmith-io/cloudsmith-go-v2/models/components"
)

type PackagesMetadataRetrieveRequest struct {
	// The `slug_perm` of the package.
	PackageSlugPerm string `pathParam:"style=simple,explode=false,name=package_slug_perm"`
	// The `slug_perm` of the metadata entry.
	SlugPerm string `pathParam:"style=simple,explode=false,name=slug_perm"`
}

func (p *PackagesMetadataRetrieveRequest) GetPackageSlugPerm() string {
	if p == nil {
		return ""
	}
	return p.PackageSlugPerm
}

func (p *PackagesMetadataRetrieveRequest) GetSlugPerm() string {
	if p == nil {
		return ""
	}
	return p.SlugPerm
}

type PackagesMetadataRetrieveResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The requested metadata entry.
	ArtifactMetadataRead *components.ArtifactMetadataRead
}

func (p PackagesMetadataRetrieveResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PackagesMetadataRetrieveResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PackagesMetadataRetrieveResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PackagesMetadataRetrieveResponse) GetArtifactMetadataRead() *components.ArtifactMetadataRead {
	if p == nil {
		return nil
	}
	return p.ArtifactMetadataRead
}
