// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f7a5834ff351

package operations

import (
	"github.com/cloudsmith-io/cloudsmith-go-v2/internal/utils"
	"github.com/cloudsmith-io/cloudsmith-go-v2/models/components"
)

type PackagesMetadataPartialUpdateRequest struct {
	// The `slug_perm` of the package.
	PackageSlugPerm string `pathParam:"style=simple,explode=false,name=package_slug_perm"`
	// The `slug_perm` of the metadata entry.
	SlugPerm string                                   `pathParam:"style=simple,explode=false,name=slug_perm"`
	Body     *components.PatchedArtifactMetadataWrite `request:"mediaType=application/json"`
}

func (p PackagesMetadataPartialUpdateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PackagesMetadataPartialUpdateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PackagesMetadataPartialUpdateRequest) GetPackageSlugPerm() string {
	if p == nil {
		return ""
	}
	return p.PackageSlugPerm
}

func (p *PackagesMetadataPartialUpdateRequest) GetSlugPerm() string {
	if p == nil {
		return ""
	}
	return p.SlugPerm
}

func (p *PackagesMetadataPartialUpdateRequest) GetBody() *components.PatchedArtifactMetadataWrite {
	if p == nil {
		return nil
	}
	return p.Body
}

type PackagesMetadataPartialUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The metadata entry was updated successfully.
	ArtifactMetadataWrite *components.ArtifactMetadataWrite
}

func (p PackagesMetadataPartialUpdateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PackagesMetadataPartialUpdateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PackagesMetadataPartialUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PackagesMetadataPartialUpdateResponse) GetArtifactMetadataWrite() *components.ArtifactMetadataWrite {
	if p == nil {
		return nil
	}
	return p.ArtifactMetadataWrite
}
