// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/cloudsmith-io/cloudsmith-go-v2/internal/utils"
	"github.com/cloudsmith-io/cloudsmith-go-v2/models/components"
)

type WorkspacesPoliciesSimulateListRequest struct {
	// A [package search](https://help.cloudsmith.io/docs/search-packages) query by which to filter the packages being evaluated.
	PackageQueryString *string `queryParam:"style=form,explode=true,name=package_query_string"`
	// A page number within the paginated result set.
	Page *int64 `queryParam:"style=form,explode=true,name=page"`
	// Number of results to return per page.
	PageSize *int64 `queryParam:"style=form,explode=true,name=page_size"`
	// The `slug_perm` (identifier) of the Policy.
	Policy string `pathParam:"style=simple,explode=false,name=policy"`
	// The `name` of the Workspace.
	Workspace string `pathParam:"style=simple,explode=false,name=workspace"`
}

func (w *WorkspacesPoliciesSimulateListRequest) GetPackageQueryString() *string {
	if w == nil {
		return nil
	}
	return w.PackageQueryString
}

func (w *WorkspacesPoliciesSimulateListRequest) GetPage() *int64 {
	if w == nil {
		return nil
	}
	return w.Page
}

func (w *WorkspacesPoliciesSimulateListRequest) GetPageSize() *int64 {
	if w == nil {
		return nil
	}
	return w.PageSize
}

func (w *WorkspacesPoliciesSimulateListRequest) GetPolicy() string {
	if w == nil {
		return ""
	}
	return w.Policy
}

func (w *WorkspacesPoliciesSimulateListRequest) GetWorkspace() string {
	if w == nil {
		return ""
	}
	return w.Workspace
}

type WorkspacesPoliciesSimulateListResponse struct {
	HTTPMeta                       components.HTTPMetadata `json:"-"`
	PaginatedPolicyDecisionLogList *components.PaginatedPolicyDecisionLogList
}

func (w WorkspacesPoliciesSimulateListResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WorkspacesPoliciesSimulateListResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WorkspacesPoliciesSimulateListResponse) GetHTTPMeta() components.HTTPMetadata {
	if w == nil {
		return components.HTTPMetadata{}
	}
	return w.HTTPMeta
}

func (w *WorkspacesPoliciesSimulateListResponse) GetPaginatedPolicyDecisionLogList() *components.PaginatedPolicyDecisionLogList {
	if w == nil {
		return nil
	}
	return w.PaginatedPolicyDecisionLogList
}
