// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/cloudsmith-io/cloudsmith-go-v2/internal/utils"
	"github.com/cloudsmith-io/cloudsmith-go-v2/models/components"
)

type WorkspacesPoliciesUpdateRequest struct {
	// The `slug_perm` (identifier) of the Policy.
	Policy string `pathParam:"style=simple,explode=false,name=policy"`
	// The `name` of the Workspace.
	Workspace string                  `pathParam:"style=simple,explode=false,name=workspace"`
	Body      components.PolicyInput1 `request:"mediaType=application/json"`
}

func (w *WorkspacesPoliciesUpdateRequest) GetPolicy() string {
	if w == nil {
		return ""
	}
	return w.Policy
}

func (w *WorkspacesPoliciesUpdateRequest) GetWorkspace() string {
	if w == nil {
		return ""
	}
	return w.Workspace
}

func (w *WorkspacesPoliciesUpdateRequest) GetBody() components.PolicyInput1 {
	if w == nil {
		return components.PolicyInput1{}
	}
	return w.Body
}

type WorkspacesPoliciesUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Policy   *components.Policy
}

func (w WorkspacesPoliciesUpdateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WorkspacesPoliciesUpdateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WorkspacesPoliciesUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if w == nil {
		return components.HTTPMetadata{}
	}
	return w.HTTPMeta
}

func (w *WorkspacesPoliciesUpdateResponse) GetPolicy() *components.Policy {
	if w == nil {
		return nil
	}
	return w.Policy
}
