// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/cloudsmith-io/cloudsmith-go-v2/models/components"
)

type WorkspacesPoliciesActionsRetrieveRequest struct {
	// The `slug_perm` (identifier) of the Action.
	Action string `pathParam:"style=simple,explode=false,name=action"`
	// The `slug_perm` (identifier) of the Policy.
	Policy string `pathParam:"style=simple,explode=false,name=policy"`
	// The `name` of the Workspace.
	Workspace string `pathParam:"style=simple,explode=false,name=workspace"`
}

func (w *WorkspacesPoliciesActionsRetrieveRequest) GetAction() string {
	if w == nil {
		return ""
	}
	return w.Action
}

func (w *WorkspacesPoliciesActionsRetrieveRequest) GetPolicy() string {
	if w == nil {
		return ""
	}
	return w.Policy
}

func (w *WorkspacesPoliciesActionsRetrieveRequest) GetWorkspace() string {
	if w == nil {
		return ""
	}
	return w.Workspace
}

type WorkspacesPoliciesActionsRetrieveResponse struct {
	HTTPMeta     components.HTTPMetadata `json:"-"`
	PolicyAction *components.PolicyAction
}

func (w *WorkspacesPoliciesActionsRetrieveResponse) GetHTTPMeta() components.HTTPMetadata {
	if w == nil {
		return components.HTTPMetadata{}
	}
	return w.HTTPMeta
}

func (w *WorkspacesPoliciesActionsRetrieveResponse) GetPolicyAction() *components.PolicyAction {
	if w == nil {
		return nil
	}
	return w.PolicyAction
}

func (w *WorkspacesPoliciesActionsRetrieveResponse) GetPolicyActionSetPackageState() *components.SetPackageStatePolicyActionTyped {
	if v := w.GetPolicyAction(); v != nil {
		return v.SetPackageStatePolicyActionTyped
	}
	return nil
}

func (w *WorkspacesPoliciesActionsRetrieveResponse) GetPolicyActionAddPackageTags() *components.AddPackageTagsPolicyActionTyped {
	if v := w.GetPolicyAction(); v != nil {
		return v.AddPackageTagsPolicyActionTyped
	}
	return nil
}

func (w *WorkspacesPoliciesActionsRetrieveResponse) GetPolicyActionRemovePackageTags() *components.RemovePackageTagsPolicyActionTyped {
	if v := w.GetPolicyAction(); v != nil {
		return v.RemovePackageTagsPolicyActionTyped
	}
	return nil
}
