// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f60dec8e48b3

package operations

import (
	"github.com/cloudsmith-io/cloudsmith-go-v2/internal/utils"
	"github.com/cloudsmith-io/cloudsmith-go-v2/models/components"
)

type WorkspacesPoliciesCreateRequest struct {
	// The `name` of the Workspace.
	Workspace string                  `pathParam:"style=simple,explode=false,name=workspace"`
	Body      components.PolicyInput1 `request:"mediaType=application/json"`
}

func (w *WorkspacesPoliciesCreateRequest) GetWorkspace() string {
	if w == nil {
		return ""
	}
	return w.Workspace
}

func (w *WorkspacesPoliciesCreateRequest) GetBody() components.PolicyInput1 {
	if w == nil {
		return components.PolicyInput1{}
	}
	return w.Body
}

type WorkspacesPoliciesCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Policy   *components.Policy
}

func (w WorkspacesPoliciesCreateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WorkspacesPoliciesCreateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WorkspacesPoliciesCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if w == nil {
		return components.HTTPMetadata{}
	}
	return w.HTTPMeta
}

func (w *WorkspacesPoliciesCreateResponse) GetPolicy() *components.Policy {
	if w == nil {
		return nil
	}
	return w.Policy
}
