// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/cloudsmith-io/cloudsmith-go-v2/internal/utils"
	"github.com/cloudsmith-io/cloudsmith-go-v2/models/components"
)

type WorkspacesPoliciesDecisionLogsV1RetrieveRequest struct {
	DecisionLogID string `pathParam:"style=simple,explode=false,name=decision_log_id"`
	// Comma-separated fields to include in the response (e.g. `id,correlation_id,policy_output`).
	Fields    *string `queryParam:"style=form,explode=true,name=fields"`
	Workspace string  `pathParam:"style=simple,explode=false,name=workspace"`
}

func (w *WorkspacesPoliciesDecisionLogsV1RetrieveRequest) GetDecisionLogID() string {
	if w == nil {
		return ""
	}
	return w.DecisionLogID
}

func (w *WorkspacesPoliciesDecisionLogsV1RetrieveRequest) GetFields() *string {
	if w == nil {
		return nil
	}
	return w.Fields
}

func (w *WorkspacesPoliciesDecisionLogsV1RetrieveRequest) GetWorkspace() string {
	if w == nil {
		return ""
	}
	return w.Workspace
}

// #region class-body-workspacespoliciesdecisionlogsv1retrieverequest
// #endregion class-body-workspacespoliciesdecisionlogsv1retrieverequest

type WorkspacesPoliciesDecisionLogsV1RetrieveResponse struct {
	HTTPMeta          components.HTTPMetadata `json:"-"`
	PolicyDecisionLog *components.PolicyDecisionLog
}

func (w WorkspacesPoliciesDecisionLogsV1RetrieveResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WorkspacesPoliciesDecisionLogsV1RetrieveResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WorkspacesPoliciesDecisionLogsV1RetrieveResponse) GetHTTPMeta() components.HTTPMetadata {
	if w == nil {
		return components.HTTPMetadata{}
	}
	return w.HTTPMeta
}

func (w *WorkspacesPoliciesDecisionLogsV1RetrieveResponse) GetPolicyDecisionLog() *components.PolicyDecisionLog {
	if w == nil {
		return nil
	}
	return w.PolicyDecisionLog
}

// #region class-body-workspacespoliciesdecisionlogsv1retrieveresponse
// #endregion class-body-workspacespoliciesdecisionlogsv1retrieveresponse
