// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d3a864444be0

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathPutWorkspacesWorkspacePoliciesPolicyActionsAction(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "workspaces_policies_actions_update[0]":
			dir.HandlerFunc("workspaces_policies_actions_update", testWorkspacesPoliciesActionsUpdateWorkspacesPoliciesActionsUpdate0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testWorkspacesPoliciesActionsUpdateWorkspacesPoliciesActionsUpdate0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityHeader(req, "X-Api-Key", false); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.ContentType(req, "application/json", false); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *components.PolicyAction = types.Pointer(components.CreatePolicyActionSetPackageState(
		components.SetPackageStatePolicyActionTyped{
			ActionType:   "SetPackageState",
			SlugPerm:     "<value>",
			CreatedAt:    types.MustTimeFromString("2025-01-01T06:02:52.023Z"),
			UpdatedAt:    types.MustTimeFromString("2025-12-30T15:47:39.800Z"),
			Effect:       "<value>",
			PackageState: components.PackageStateEnumHidden,
		},
	))
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
