// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 67fe6a5b1ec9

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathGetWorkspacesWorkspacePoliciesDecisionLogsV1(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "workspaces_policies_decision_logs_v1_list-ReverseChronologicalOrder(theDefault)[0]":
			dir.HandlerFunc("workspaces_policies_decision_logs_v1_list", testWorkspacesPoliciesDecisionLogsV1ListWorkspacesPoliciesDecisionLogsV1ListReverseChronologicalOrderTheDefault0)(w, req)
		case "workspaces_policies_decision_logs_v1_list-ChronologicalOrder[0]":
			dir.HandlerFunc("workspaces_policies_decision_logs_v1_list", testWorkspacesPoliciesDecisionLogsV1ListWorkspacesPoliciesDecisionLogsV1ListChronologicalOrder0)(w, req)
		case "workspaces_policies_decision_logs_v1_list[0]":
			dir.HandlerFunc("workspaces_policies_decision_logs_v1_list", testWorkspacesPoliciesDecisionLogsV1ListWorkspacesPoliciesDecisionLogsV1List0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testWorkspacesPoliciesDecisionLogsV1ListWorkspacesPoliciesDecisionLogsV1ListReverseChronologicalOrderTheDefault0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityHeader(req, "X-Api-Key", false); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *components.PaginatedPolicyDecisionLogV1SummaryList = &components.PaginatedPolicyDecisionLogV1SummaryList{
		Results: []components.PolicyDecisionLogV1Summary{
			components.PolicyDecisionLogV1Summary{
				ID: "<id>",
				Actions: map[string]any{
					"key":  "<value>",
					"key1": "<value>",
					"key2": "<value>",
				},
				CorrelationID:      "cc20ef83-023e-4b49-bd56-4d6c7483b88a",
				EndedAt:            types.MustTimeFromString("2026-10-21T00:37:41.737Z"),
				Match:              false,
				PackageFormat:      "<value>",
				PackageName:        "<value>",
				PackageSlug:        "<value>",
				PackageSlugPerm:    "<value>",
				PackageVersion:     "<value>",
				PolicyIsTerminal:   false,
				PolicyName:         "<value>",
				PolicyPrecedence:   731170,
				PolicySlugPerm:     "<value>",
				PolicyVersion:      125110,
				RepositoryName:     "<value>",
				RepositorySlug:     "<value>",
				RepositorySlugPerm: "<value>",
				StartedAt:          types.MustTimeFromString("2024-09-16T10:22:51.075Z"),
			},
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}

func testWorkspacesPoliciesDecisionLogsV1ListWorkspacesPoliciesDecisionLogsV1ListChronologicalOrder0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityHeader(req, "X-Api-Key", false); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *components.PaginatedPolicyDecisionLogV1SummaryList = &components.PaginatedPolicyDecisionLogV1SummaryList{
		Results: []components.PolicyDecisionLogV1Summary{
			components.PolicyDecisionLogV1Summary{
				ID: "<id>",
				Actions: map[string]any{
					"key":  "<value>",
					"key1": "<value>",
					"key2": "<value>",
				},
				CorrelationID:      "cc20ef83-023e-4b49-bd56-4d6c7483b88a",
				EndedAt:            types.MustTimeFromString("2026-10-21T00:37:41.737Z"),
				Match:              false,
				PackageFormat:      "<value>",
				PackageName:        "<value>",
				PackageSlug:        "<value>",
				PackageSlugPerm:    "<value>",
				PackageVersion:     "<value>",
				PolicyIsTerminal:   false,
				PolicyName:         "<value>",
				PolicyPrecedence:   731170,
				PolicySlugPerm:     "<value>",
				PolicyVersion:      125110,
				RepositoryName:     "<value>",
				RepositorySlug:     "<value>",
				RepositorySlugPerm: "<value>",
				StartedAt:          types.MustTimeFromString("2024-09-16T10:22:51.075Z"),
			},
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}

func testWorkspacesPoliciesDecisionLogsV1ListWorkspacesPoliciesDecisionLogsV1List0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityHeader(req, "X-Api-Key", false); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *components.PaginatedPolicyDecisionLogV1SummaryList = &components.PaginatedPolicyDecisionLogV1SummaryList{
		Results: []components.PolicyDecisionLogV1Summary{
			components.PolicyDecisionLogV1Summary{
				ID: "<id>",
				Actions: map[string]any{
					"key":  "<value>",
					"key1": "<value>",
					"key2": "<value>",
				},
				CorrelationID:      "cc20ef83-023e-4b49-bd56-4d6c7483b88a",
				EndedAt:            types.MustTimeFromString("2026-10-21T00:37:41.737Z"),
				Match:              false,
				PackageFormat:      "<value>",
				PackageName:        "<value>",
				PackageSlug:        "<value>",
				PackageSlugPerm:    "<value>",
				PackageVersion:     "<value>",
				PolicyIsTerminal:   false,
				PolicyName:         "<value>",
				PolicyPrecedence:   731170,
				PolicySlugPerm:     "<value>",
				PolicyVersion:      125110,
				RepositoryName:     "<value>",
				RepositorySlug:     "<value>",
				RepositorySlugPerm: "<value>",
				StartedAt:          types.MustTimeFromString("2024-09-16T10:22:51.075Z"),
			},
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
