// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e8c711a37cbd

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathGetWorkspacesWorkspacePolicies(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "workspaces_policies_list-PoliciesNamedFooOrBar[0]":
			dir.HandlerFunc("workspaces_policies_list", testWorkspacesPoliciesListWorkspacesPoliciesListPoliciesNamedFooOrBar0)(w, req)
		case "workspaces_policies_list-`version`Descending,`updatedAt`Ascending[0]":
			dir.HandlerFunc("workspaces_policies_list", testWorkspacesPoliciesListWorkspacesPoliciesListVersionDescendingUpdatedAtAscending0)(w, req)
		case "workspaces_policies_list[0]":
			dir.HandlerFunc("workspaces_policies_list", testWorkspacesPoliciesListWorkspacesPoliciesList0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testWorkspacesPoliciesListWorkspacesPoliciesListPoliciesNamedFooOrBar0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityHeader(req, "X-Api-Key", false); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *components.PaginatedPolicyList = &components.PaginatedPolicyList{
		Results: []components.Policy{
			components.Policy{
				CreatedAt: types.MustTimeFromString("2025-07-27T20:51:05.736Z"),
				Name:      "<value>",
				Rego:      "<value>",
				ReadOnly:  true,
				SlugPerm:  "<value>",
				UpdatedAt: types.MustTimeFromString("2024-02-06T23:49:45.490Z"),
				Version:   814179,
			},
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}

func testWorkspacesPoliciesListWorkspacesPoliciesListVersionDescendingUpdatedAtAscending0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityHeader(req, "X-Api-Key", false); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *components.PaginatedPolicyList = &components.PaginatedPolicyList{
		Results: []components.Policy{
			components.Policy{
				CreatedAt: types.MustTimeFromString("2025-07-27T20:51:05.736Z"),
				Name:      "<value>",
				Rego:      "<value>",
				ReadOnly:  true,
				SlugPerm:  "<value>",
				UpdatedAt: types.MustTimeFromString("2024-02-06T23:49:45.490Z"),
				Version:   814179,
			},
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}

func testWorkspacesPoliciesListWorkspacesPoliciesList0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityHeader(req, "X-Api-Key", false); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *components.PaginatedPolicyList = &components.PaginatedPolicyList{
		Results: []components.Policy{
			components.Policy{
				CreatedAt: types.MustTimeFromString("2025-07-27T20:51:05.736Z"),
				Name:      "<value>",
				Rego:      "<value>",
				ReadOnly:  true,
				SlugPerm:  "<value>",
				UpdatedAt: types.MustTimeFromString("2024-02-06T23:49:45.490Z"),
				Version:   814179,
			},
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
