// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5b357b18a3e9

package tests

import (
	"context"
	cloudsmith "github.com/cloudsmith-io/cloudsmith-go-v2"
	"github.com/cloudsmith-io/cloudsmith-go-v2/internal/utils"
	"github.com/cloudsmith-io/cloudsmith-go-v2/models/components"
	"github.com/cloudsmith-io/cloudsmith-go-v2/models/operations"
	"github.com/cloudsmith-io/cloudsmith-go-v2/types"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestWorkspaces_WorkspacesPoliciesListPoliciesNamedFooOrBar(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("workspaces_policies_list-PoliciesNamedFooOrBar")

	s := cloudsmith.New(
		cloudsmith.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		cloudsmith.WithClient(testHTTPClient),
		cloudsmith.WithSecurity("<YOUR_API_KEY_HERE>"),
	)

	res, err := s.Workspaces.WorkspacesPoliciesList(ctx, operations.WorkspacesPoliciesListRequest{
		Page:      694333,
		Query:     cloudsmith.Pointer("name: foo OR name: bar"),
		Workspace: "<value>",
	})
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.PaginatedPolicyList)
	assert.Equal(t, &components.PaginatedPolicyList{
		Results: []components.Policy{
			components.Policy{
				CreatedAt: types.MustTimeFromString("2025-07-27T20:51:05.736Z"),
				Name:      "<value>",
				Rego:      "<value>",
				ReadOnly:  true,
				SlugPerm:  "<value>",
				UpdatedAt: types.MustTimeFromString("2024-02-06T23:49:45.490Z"),
				Version:   814179,
			},
		},
	}, res.PaginatedPolicyList)

}

func TestWorkspaces_WorkspacesPoliciesListVersionDescendingUpdatedAtAscending(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("workspaces_policies_list-`version`Descending,`updatedAt`Ascending")

	s := cloudsmith.New(
		cloudsmith.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		cloudsmith.WithClient(testHTTPClient),
		cloudsmith.WithSecurity("<YOUR_API_KEY_HERE>"),
	)

	res, err := s.Workspaces.WorkspacesPoliciesList(ctx, operations.WorkspacesPoliciesListRequest{
		Page:      475392,
		Sort:      cloudsmith.Pointer("-version,updated_at"),
		Workspace: "<value>",
	})
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.PaginatedPolicyList)
	assert.Equal(t, &components.PaginatedPolicyList{
		Results: []components.Policy{
			components.Policy{
				CreatedAt: types.MustTimeFromString("2025-07-27T20:51:05.736Z"),
				Name:      "<value>",
				Rego:      "<value>",
				ReadOnly:  true,
				SlugPerm:  "<value>",
				UpdatedAt: types.MustTimeFromString("2024-02-06T23:49:45.490Z"),
				Version:   814179,
			},
		},
	}, res.PaginatedPolicyList)

}

func TestWorkspaces_WorkspacesPoliciesList(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("workspaces_policies_list")

	s := cloudsmith.New(
		cloudsmith.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		cloudsmith.WithClient(testHTTPClient),
		cloudsmith.WithSecurity("<YOUR_API_KEY_HERE>"),
	)

	res, err := s.Workspaces.WorkspacesPoliciesList(ctx, operations.WorkspacesPoliciesListRequest{
		Page:      849692,
		Workspace: "<value>",
	})
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.PaginatedPolicyList)
	assert.Equal(t, &components.PaginatedPolicyList{
		Results: []components.Policy{
			components.Policy{
				CreatedAt: types.MustTimeFromString("2025-07-27T20:51:05.736Z"),
				Name:      "<value>",
				Rego:      "<value>",
				ReadOnly:  true,
				SlugPerm:  "<value>",
				UpdatedAt: types.MustTimeFromString("2024-02-06T23:49:45.490Z"),
				Version:   814179,
			},
		},
	}, res.PaginatedPolicyList)

}

func TestWorkspaces_WorkspacesPoliciesCreate(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("workspaces_policies_create")

	s := cloudsmith.New(
		cloudsmith.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		cloudsmith.WithClient(testHTTPClient),
		cloudsmith.WithSecurity("<YOUR_API_KEY_HERE>"),
	)

	res, err := s.Workspaces.WorkspacesPoliciesCreate(ctx, "<value>", components.PolicyInput1{
		Name: "<value>",
		Rego: "<value>",
	})
	require.NoError(t, err)
	assert.Equal(t, 201, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.Policy)
	assert.Equal(t, &components.Policy{
		CreatedAt: types.MustTimeFromString("2026-01-16T04:49:37.899Z"),
		Name:      "<value>",
		Rego:      "<value>",
		ReadOnly:  false,
		SlugPerm:  "<value>",
		UpdatedAt: types.MustTimeFromString("2026-08-05T02:22:13.921Z"),
		Version:   416950,
	}, res.Policy)

}

func TestWorkspaces_WorkspacesPoliciesRetrieve(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("workspaces_policies_retrieve")

	s := cloudsmith.New(
		cloudsmith.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		cloudsmith.WithClient(testHTTPClient),
		cloudsmith.WithSecurity("<YOUR_API_KEY_HERE>"),
	)

	res, err := s.Workspaces.WorkspacesPoliciesRetrieve(ctx, "<value>", "<value>")
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.Policy)
	assert.Equal(t, &components.Policy{
		CreatedAt: types.MustTimeFromString("2024-02-25T01:47:43.113Z"),
		Name:      "<value>",
		Rego:      "<value>",
		ReadOnly:  false,
		SlugPerm:  "<value>",
		UpdatedAt: types.MustTimeFromString("2026-03-28T21:06:43.659Z"),
		Version:   355598,
	}, res.Policy)

}

func TestWorkspaces_WorkspacesPoliciesUpdate(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("workspaces_policies_update")

	s := cloudsmith.New(
		cloudsmith.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		cloudsmith.WithClient(testHTTPClient),
		cloudsmith.WithSecurity("<YOUR_API_KEY_HERE>"),
	)

	res, err := s.Workspaces.WorkspacesPoliciesUpdate(ctx, "<value>", "<value>", components.PolicyInput1{
		Name: "<value>",
		Rego: "<value>",
	})
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.Policy)
	assert.Equal(t, &components.Policy{
		CreatedAt: types.MustTimeFromString("2025-06-13T11:53:09.193Z"),
		Name:      "<value>",
		Rego:      "<value>",
		ReadOnly:  false,
		SlugPerm:  "<value>",
		UpdatedAt: types.MustTimeFromString("2024-08-22T06:15:17.414Z"),
		Version:   780036,
	}, res.Policy)

}

func TestWorkspaces_WorkspacesPoliciesPartialUpdate(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("workspaces_policies_partial_update")

	s := cloudsmith.New(
		cloudsmith.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		cloudsmith.WithClient(testHTTPClient),
		cloudsmith.WithSecurity("<YOUR_API_KEY_HERE>"),
	)

	res, err := s.Workspaces.WorkspacesPoliciesPartialUpdate(ctx, "<value>", "<value>", nil)
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.Policy)
	assert.Equal(t, &components.Policy{
		CreatedAt: types.MustTimeFromString("2025-05-15T07:54:42.171Z"),
		Name:      "<value>",
		Rego:      "<value>",
		ReadOnly:  true,
		SlugPerm:  "<value>",
		UpdatedAt: types.MustTimeFromString("2026-07-30T00:14:05.439Z"),
		Version:   222414,
	}, res.Policy)

}

func TestWorkspaces_WorkspacesPoliciesActionsList(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("workspaces_policies_actions_list")

	s := cloudsmith.New(
		cloudsmith.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		cloudsmith.WithClient(testHTTPClient),
		cloudsmith.WithSecurity("<YOUR_API_KEY_HERE>"),
	)

	res, err := s.Workspaces.WorkspacesPoliciesActionsList(ctx, "<value>", "<value>", nil, nil)
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.PaginatedPolicyActionList)
	assert.Equal(t, &components.PaginatedPolicyActionList{
		Results: []components.PolicyAction{},
	}, res.PaginatedPolicyActionList)

}

func TestWorkspaces_WorkspacesPoliciesActionsCreate(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("workspaces_policies_actions_create")

	s := cloudsmith.New(
		cloudsmith.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		cloudsmith.WithClient(testHTTPClient),
		cloudsmith.WithSecurity("<YOUR_API_KEY_HERE>"),
	)

	res, err := s.Workspaces.WorkspacesPoliciesActionsCreate(ctx, "<value>", "<value>", nil)
	require.NoError(t, err)
	assert.Equal(t, 201, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.PolicyAction)
	assert.Equal(t, cloudsmith.Pointer(components.CreatePolicyActionSetPackageState(
		components.SetPackageStatePolicyActionTyped{
			ActionType:   "SetPackageState",
			SlugPerm:     "<value>",
			CreatedAt:    types.MustTimeFromString("2026-01-26T13:02:30.955Z"),
			UpdatedAt:    types.MustTimeFromString("2024-07-14T00:26:02.146Z"),
			Effect:       "<value>",
			PackageState: components.PackageStateEnumDeleted,
		},
	)), res.PolicyAction)

}

func TestWorkspaces_WorkspacesPoliciesActionsRetrieve(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("workspaces_policies_actions_retrieve")

	s := cloudsmith.New(
		cloudsmith.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		cloudsmith.WithClient(testHTTPClient),
		cloudsmith.WithSecurity("<YOUR_API_KEY_HERE>"),
	)

	res, err := s.Workspaces.WorkspacesPoliciesActionsRetrieve(ctx, "<value>", "<value>", "<value>")
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.PolicyAction)
	assert.Equal(t, cloudsmith.Pointer(components.CreatePolicyActionSetPackageState(
		components.SetPackageStatePolicyActionTyped{
			ActionType:   "SetPackageState",
			SlugPerm:     "<value>",
			CreatedAt:    types.MustTimeFromString("2026-12-26T16:15:13.417Z"),
			UpdatedAt:    types.MustTimeFromString("2025-12-22T23:44:49.910Z"),
			Effect:       "<value>",
			PackageState: components.PackageStateEnumHidden,
		},
	)), res.PolicyAction)

}

func TestWorkspaces_WorkspacesPoliciesActionsUpdate(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("workspaces_policies_actions_update")

	s := cloudsmith.New(
		cloudsmith.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		cloudsmith.WithClient(testHTTPClient),
		cloudsmith.WithSecurity("<YOUR_API_KEY_HERE>"),
	)

	res, err := s.Workspaces.WorkspacesPoliciesActionsUpdate(ctx, "<value>", "<value>", "<value>", nil)
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.PolicyAction)
	assert.Equal(t, cloudsmith.Pointer(components.CreatePolicyActionSetPackageState(
		components.SetPackageStatePolicyActionTyped{
			ActionType:   "SetPackageState",
			SlugPerm:     "<value>",
			CreatedAt:    types.MustTimeFromString("2025-01-01T06:02:52.023Z"),
			UpdatedAt:    types.MustTimeFromString("2025-12-30T15:47:39.800Z"),
			Effect:       "<value>",
			PackageState: components.PackageStateEnumHidden,
		},
	)), res.PolicyAction)

}

func TestWorkspaces_WorkspacesPoliciesActionsPartialUpdate(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("workspaces_policies_actions_partial_update")

	s := cloudsmith.New(
		cloudsmith.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		cloudsmith.WithClient(testHTTPClient),
		cloudsmith.WithSecurity("<YOUR_API_KEY_HERE>"),
	)

	res, err := s.Workspaces.WorkspacesPoliciesActionsPartialUpdate(ctx, "<value>", "<value>", "<value>", nil)
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.PolicyAction)
	assert.Equal(t, cloudsmith.Pointer(components.CreatePolicyActionSetPackageState(
		components.SetPackageStatePolicyActionTyped{
			ActionType:   "SetPackageState",
			SlugPerm:     "<value>",
			CreatedAt:    types.MustTimeFromString("2025-06-01T09:48:19.072Z"),
			UpdatedAt:    types.MustTimeFromString("2026-05-29T01:18:47.337Z"),
			Effect:       "<value>",
			PackageState: components.PackageStateEnumAvailable,
		},
	)), res.PolicyAction)

}

func TestWorkspaces_WorkspacesPoliciesSimulateList(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("workspaces_policies_simulate_list")

	s := cloudsmith.New(
		cloudsmith.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		cloudsmith.WithClient(testHTTPClient),
		cloudsmith.WithSecurity("<YOUR_API_KEY_HERE>"),
	)

	res, err := s.Workspaces.WorkspacesPoliciesSimulateList(ctx, operations.WorkspacesPoliciesSimulateListRequest{
		Policy:    "<value>",
		Workspace: "<value>",
	})
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.PaginatedPolicyDecisionLogList)
	assert.Equal(t, &components.PaginatedPolicyDecisionLogList{
		Results: []components.PolicyDecisionLog{},
	}, res.PaginatedPolicyDecisionLogList)

}

func TestWorkspaces_WorkspacesPoliciesDecisionLogsV1ListReverseChronologicalOrderTheDefault(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("workspaces_policies_decision_logs_v1_list-ReverseChronologicalOrder(theDefault)")

	s := cloudsmith.New(
		cloudsmith.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		cloudsmith.WithClient(testHTTPClient),
		cloudsmith.WithSecurity("<YOUR_API_KEY_HERE>"),
	)

	res, err := s.Workspaces.WorkspacesPoliciesDecisionLogsV1List(ctx, operations.WorkspacesPoliciesDecisionLogsV1ListRequest{
		CreatedAfter: types.MustTimeFromString("2025-02-17T14:08:57.543Z"),
		Workspace:    "<value>",
	})
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.PaginatedPolicyDecisionLogV1SummaryList)
	assert.Equal(t, &components.PaginatedPolicyDecisionLogV1SummaryList{
		Results: []components.PolicyDecisionLogV1Summary{
			components.PolicyDecisionLogV1Summary{
				ID: "<id>",
				Actions: map[string]any{
					"key":  "<value>",
					"key1": "<value>",
					"key2": "<value>",
				},
				CorrelationID:      "cc20ef83-023e-4b49-bd56-4d6c7483b88a",
				EndedAt:            types.MustTimeFromString("2026-10-21T00:37:41.737Z"),
				Match:              false,
				PackageFormat:      "<value>",
				PackageName:        "<value>",
				PackageSlug:        "<value>",
				PackageSlugPerm:    "<value>",
				PackageVersion:     "<value>",
				PolicyIsTerminal:   false,
				PolicyName:         "<value>",
				PolicyPrecedence:   731170,
				PolicySlugPerm:     "<value>",
				PolicyVersion:      125110,
				RepositoryName:     "<value>",
				RepositorySlug:     "<value>",
				RepositorySlugPerm: "<value>",
				StartedAt:          types.MustTimeFromString("2024-09-16T10:22:51.075Z"),
			},
		},
	}, res.PaginatedPolicyDecisionLogV1SummaryList)

}

func TestWorkspaces_WorkspacesPoliciesDecisionLogsV1ListChronologicalOrder(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("workspaces_policies_decision_logs_v1_list-ChronologicalOrder")

	s := cloudsmith.New(
		cloudsmith.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		cloudsmith.WithClient(testHTTPClient),
		cloudsmith.WithSecurity("<YOUR_API_KEY_HERE>"),
	)

	res, err := s.Workspaces.WorkspacesPoliciesDecisionLogsV1List(ctx, operations.WorkspacesPoliciesDecisionLogsV1ListRequest{
		CreatedAfter: types.MustTimeFromString("2024-11-12T13:20:12.290Z"),
		Sort:         cloudsmith.Pointer("id"),
		Workspace:    "<value>",
	})
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.PaginatedPolicyDecisionLogV1SummaryList)
	assert.Equal(t, &components.PaginatedPolicyDecisionLogV1SummaryList{
		Results: []components.PolicyDecisionLogV1Summary{
			components.PolicyDecisionLogV1Summary{
				ID: "<id>",
				Actions: map[string]any{
					"key":  "<value>",
					"key1": "<value>",
					"key2": "<value>",
				},
				CorrelationID:      "cc20ef83-023e-4b49-bd56-4d6c7483b88a",
				EndedAt:            types.MustTimeFromString("2026-10-21T00:37:41.737Z"),
				Match:              false,
				PackageFormat:      "<value>",
				PackageName:        "<value>",
				PackageSlug:        "<value>",
				PackageSlugPerm:    "<value>",
				PackageVersion:     "<value>",
				PolicyIsTerminal:   false,
				PolicyName:         "<value>",
				PolicyPrecedence:   731170,
				PolicySlugPerm:     "<value>",
				PolicyVersion:      125110,
				RepositoryName:     "<value>",
				RepositorySlug:     "<value>",
				RepositorySlugPerm: "<value>",
				StartedAt:          types.MustTimeFromString("2024-09-16T10:22:51.075Z"),
			},
		},
	}, res.PaginatedPolicyDecisionLogV1SummaryList)

}

func TestWorkspaces_WorkspacesPoliciesDecisionLogsV1List(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("workspaces_policies_decision_logs_v1_list")

	s := cloudsmith.New(
		cloudsmith.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		cloudsmith.WithClient(testHTTPClient),
		cloudsmith.WithSecurity("<YOUR_API_KEY_HERE>"),
	)

	res, err := s.Workspaces.WorkspacesPoliciesDecisionLogsV1List(ctx, operations.WorkspacesPoliciesDecisionLogsV1ListRequest{
		CreatedAfter: types.MustTimeFromString("2024-04-19T12:20:32.132Z"),
		Workspace:    "<value>",
	})
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.PaginatedPolicyDecisionLogV1SummaryList)
	assert.Equal(t, &components.PaginatedPolicyDecisionLogV1SummaryList{
		Results: []components.PolicyDecisionLogV1Summary{
			components.PolicyDecisionLogV1Summary{
				ID: "<id>",
				Actions: map[string]any{
					"key":  "<value>",
					"key1": "<value>",
					"key2": "<value>",
				},
				CorrelationID:      "cc20ef83-023e-4b49-bd56-4d6c7483b88a",
				EndedAt:            types.MustTimeFromString("2026-10-21T00:37:41.737Z"),
				Match:              false,
				PackageFormat:      "<value>",
				PackageName:        "<value>",
				PackageSlug:        "<value>",
				PackageSlugPerm:    "<value>",
				PackageVersion:     "<value>",
				PolicyIsTerminal:   false,
				PolicyName:         "<value>",
				PolicyPrecedence:   731170,
				PolicySlugPerm:     "<value>",
				PolicyVersion:      125110,
				RepositoryName:     "<value>",
				RepositorySlug:     "<value>",
				RepositorySlugPerm: "<value>",
				StartedAt:          types.MustTimeFromString("2024-09-16T10:22:51.075Z"),
			},
		},
	}, res.PaginatedPolicyDecisionLogV1SummaryList)

}

func TestWorkspaces_WorkspacesPoliciesDecisionLogsV1Retrieve(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("workspaces_policies_decision_logs_v1_retrieve")

	s := cloudsmith.New(
		cloudsmith.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		cloudsmith.WithClient(testHTTPClient),
		cloudsmith.WithSecurity("<YOUR_API_KEY_HERE>"),
	)

	res, err := s.Workspaces.WorkspacesPoliciesDecisionLogsV1Retrieve(ctx, "<id>", "<value>", nil)
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.PolicyDecisionLog)
	assert.Equal(t, &components.PolicyDecisionLog{
		CorrelationID: "5d0374a7-0667-42d5-bbd3-e230e41cdfa4",
		Policy: components.Policy{
			CreatedAt: types.MustTimeFromString("2026-11-11T07:45:14.285Z"),
			Name:      "<value>",
			Rego:      "<value>",
			ReadOnly:  false,
			SlugPerm:  "<value>",
			UpdatedAt: types.MustTimeFromString("2025-04-09T19:29:36.919Z"),
			Version:   526642,
		},
		StartedAt: types.MustTimeFromString("2025-11-01T03:46:01.833Z"),
		EndedAt:   types.MustTimeFromString("2026-09-27T14:35:11.388Z"),
		PolicyInput: components.PolicyInput2{
			V0: components.PolicyInputV0{
				Package: components.CreatePolicyPolymorphicPackageHuggingfacePackage(
					components.PolicyHuggingfacePackageTyped{
						Format: "HuggingfacePackage",
						Architectures: []components.PolicyArchitecture{
							components.PolicyArchitecture{
								Name: "<value>",
							},
						},
						Files: []components.PolicyHuggingfaceFileReference{
							components.PolicyHuggingfaceFileReference{
								FileExtension: "<value>",
								Oid:           "<id>",
								Size:          537019,
								Path:          "/opt",
							},
						},
						IsLocal:          false,
						LastDownloadedAt: types.MustTimeFromString("2026-09-23T00:43:31.883Z"),
						License: components.PolicyPackageLicense{
							RawLicenseFileContents: components.RawLicenseFileContents{
								Sha256:  "<value>",
								RawText: "<value>",
							},
							OssLicense: components.OssLicense{
								FullName:       "Karl Rau",
								LicenseText:    "<value>",
								SpdxIdentifier: "<value>",
							},
							Source:     components.LicenseSourceEnumAutomatic,
							Match:      components.LicenseMatchTypeEnumUnknown,
							Similarity: cloudsmith.Pointer[int](326595),
							Override:   components.LicenseOverrideEnumIgnored,
						},
						NumFiles:           382506,
						PackageType:        components.PackageTypeEnumOther,
						SecurityScanStatus: components.SecurityScanStatusEnumUnsupportedPackage,
						Slug:               "<value>",
						Tags: []components.PolicyPackageTag{
							components.PolicyPackageTag{
								Name:    "<value>",
								Source:  components.PackageTagSourceTypeEnumManual,
								TagType: components.PackageTagTypeEnumSomeVersion,
							},
						},
					},
				),
				Repository: components.PolicyRepository{
					EcdsaKeys: []components.PolicyRepositoryEcdsaKey{
						components.PolicyRepositoryEcdsaKey{
							FingerprintShort: "<value>",
							Fingerprint:      "<value>",
							PublicKey:        "<value>",
						},
					},
					GpgKeys: []components.PolicyRepositoryGpgKey{
						components.PolicyRepositoryGpgKey{
							Comment:          "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
							FingerprintShort: "<value>",
							Fingerprint:      "<value>",
							PublicKey:        "<value>",
						},
					},
					Name:              "<value>",
					OpenSourceLicense: nil,
					RepositoryType:    components.RepositoryTypeEnumPrivate,
					StorageRegion:     "<value>",
				},
				Workspace: components.PolicyWorkspace{
					Name:     "<value>",
					Slug:     "<value>",
					SlugPerm: "<value>",
				},
			},
		},
		PolicyOutput: "<value>",
		Actions: []components.PolicyAction{
			components.CreatePolicyActionRemovePackageTags(
				components.RemovePackageTagsPolicyActionTyped{
					ActionType: "RemovePackageTags",
					SlugPerm:   "<value>",
					CreatedAt:  types.MustTimeFromString("2025-04-14T10:55:17.857Z"),
					UpdatedAt:  types.MustTimeFromString("2026-12-10T21:36:06.359Z"),
					Effect:     "<value>",
					Tags: []string{
						"<value 1>",
					},
				},
			),
		},
		ParsedActions: "<value>",
	}, res.PolicyDecisionLog)

}
