// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f9b80fa38102

package components

import (
	"github.com/cloudsmith-io/cloudsmith-go-v2/internal/utils"
)

type AddPackageTagsPolicyActionTypedInput struct {
	ActionType string `json:"action_type"`
	// The order in which this action occurs relative to other actions for the same policy.
	Precedence *int64   `json:"precedence,omitzero"`
	Tags       []string `json:"tags"`
}

func (a AddPackageTagsPolicyActionTypedInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AddPackageTagsPolicyActionTypedInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AddPackageTagsPolicyActionTypedInput) GetActionType() string {
	if a == nil {
		return ""
	}
	return a.ActionType
}

func (a *AddPackageTagsPolicyActionTypedInput) GetPrecedence() *int64 {
	if a == nil {
		return nil
	}
	return a.Precedence
}

func (a *AddPackageTagsPolicyActionTypedInput) GetTags() []string {
	if a == nil {
		return []string{}
	}
	return a.Tags
}
