// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5142b39fa22c

package components

// ArtifactMetadataWriteRequest - Serializer for POST create and PATCH update on artifact metadata.
type ArtifactMetadataWriteRequest struct {
	// The metadata payload as a JSON object.
	Content any `json:"content"`
	// The content type describing the structure of the metadata payload.
	ContentType string `json:"content_type"`
	// The identifier for the source of this metadata, for example 'upstream:npmjs'.
	SourceIdentity string `json:"source_identity"`
}

func (a *ArtifactMetadataWriteRequest) GetContent() any {
	if a == nil {
		return nil
	}
	return a.Content
}

func (a *ArtifactMetadataWriteRequest) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *ArtifactMetadataWriteRequest) GetSourceIdentity() string {
	if a == nil {
		return ""
	}
	return a.SourceIdentity
}
