// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/cloudsmith-io/cloudsmith-go-v2/internal/utils"
	"time"
)

// ArtifactMetadataRead - Serializer for GET list/retrieve on the effective metadata view.
type ArtifactMetadataRead struct {
	// The unique slug identifying this metadata entry.
	SlugPerm string `json:"slug_perm"`
	// The metadata payload as a JSON object.
	Content any `json:"content"`
	// The content type describing the structure of the metadata payload.
	ContentType string `json:"content_type"`
	// The classification assigned to this metadata entry.
	//
	// * `UNKNOWN` - Unknown
	// * `INTRINSIC` - Intrinsic
	// * `SECURITY` - Security
	// * `PROVENANCE` - Provenance
	// * `SBOM` - SBOM
	// * `GENERIC` - Generic
	Classification ClassificationEnum `json:"classification"`
	// The origin of this metadata entry, such as upstream, custom, or third party.
	//
	// * `UNKNOWN` - Unknown
	// * `SYSTEM` - System
	// * `UPSTREAM` - Upstream
	// * `CUSTOM` - Custom
	// * `THIRD_PARTY` - Third Party
	SourceKind SourceKindEnum `json:"source_kind"`
	// The identifier for the source that supplied this metadata.
	SourceIdentity string `json:"source_identity"`
	// Whether this entry is the canonical metadata record for its type.
	IsCanonical bool `json:"is_canonical"`
	// The backing table or source model for this metadata entry.
	SourceTable string `json:"source_table"`
	// When this metadata entry was created.
	CreatedAt time.Time `json:"created_at"`
}

func (a ArtifactMetadataRead) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ArtifactMetadataRead) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *ArtifactMetadataRead) GetSlugPerm() string {
	if a == nil {
		return ""
	}
	return a.SlugPerm
}

func (a *ArtifactMetadataRead) GetContent() any {
	if a == nil {
		return nil
	}
	return a.Content
}

func (a *ArtifactMetadataRead) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *ArtifactMetadataRead) GetClassification() ClassificationEnum {
	if a == nil {
		return ClassificationEnum("")
	}
	return a.Classification
}

func (a *ArtifactMetadataRead) GetSourceKind() SourceKindEnum {
	if a == nil {
		return SourceKindEnum("")
	}
	return a.SourceKind
}

func (a *ArtifactMetadataRead) GetSourceIdentity() string {
	if a == nil {
		return ""
	}
	return a.SourceIdentity
}

func (a *ArtifactMetadataRead) GetIsCanonical() bool {
	if a == nil {
		return false
	}
	return a.IsCanonical
}

func (a *ArtifactMetadataRead) GetSourceTable() string {
	if a == nil {
		return ""
	}
	return a.SourceTable
}

func (a *ArtifactMetadataRead) GetCreatedAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.CreatedAt
}
