// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ArtifactMetadataValidate - Serializer for POST /metadata/validate.
//
// Same shape and validation rules as the write serializer but without
// fields tied to persistence (e.g. “source_identity“). Used by clients
// that want to fail fast on a metadata payload before they have a
// package slug to attach it to.
type ArtifactMetadataValidate struct {
	// The metadata payload as a JSON object.
	Content any `json:"content"`
	// The content type describing the structure of the metadata payload.
	ContentType string `json:"content_type"`
}

func (a *ArtifactMetadataValidate) GetContent() any {
	if a == nil {
		return nil
	}
	return a.Content
}

func (a *ArtifactMetadataValidate) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}
