// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b2d148abdb82

package components

// LicenseOverrideEnum - * `NONE` - None
// * `IGNORED` - Ignored
// * `PURCHASED` - Purchased
type LicenseOverrideEnum string

const (
	LicenseOverrideEnumNone      LicenseOverrideEnum = "NONE"
	LicenseOverrideEnumIgnored   LicenseOverrideEnum = "IGNORED"
	LicenseOverrideEnumPurchased LicenseOverrideEnum = "PURCHASED"
)

func (e LicenseOverrideEnum) ToPointer() *LicenseOverrideEnum {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *LicenseOverrideEnum) IsExact() bool {
	if e != nil {
		switch *e {
		case "NONE", "IGNORED", "PURCHASED":
			return true
		}
	}
	return false
}
