// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: be4eb31ea093

package components

// LicenseMatchTypeEnum - * `NONE` - None
// * `OSS_EXACT` - OSS exact match
// * `OSS_FUZZY` - OSS fuzzy match
// * `PROPRIETARY` - Proprietary match
// * `UNKNOWN` - Unknown match
// * `CURATED` - Curated match
type LicenseMatchTypeEnum string

const (
	LicenseMatchTypeEnumNone        LicenseMatchTypeEnum = "NONE"
	LicenseMatchTypeEnumOssExact    LicenseMatchTypeEnum = "OSS_EXACT"
	LicenseMatchTypeEnumOssFuzzy    LicenseMatchTypeEnum = "OSS_FUZZY"
	LicenseMatchTypeEnumProprietary LicenseMatchTypeEnum = "PROPRIETARY"
	LicenseMatchTypeEnumUnknown     LicenseMatchTypeEnum = "UNKNOWN"
	LicenseMatchTypeEnumCurated     LicenseMatchTypeEnum = "CURATED"
)

func (e LicenseMatchTypeEnum) ToPointer() *LicenseMatchTypeEnum {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *LicenseMatchTypeEnum) IsExact() bool {
	if e != nil {
		switch *e {
		case "NONE", "OSS_EXACT", "OSS_FUZZY", "PROPRIETARY", "UNKNOWN", "CURATED":
			return true
		}
	}
	return false
}
