// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PackageStateEnum - * `AVAILABLE` - The package is available for download.
// * `DELETED` - The package is deleted.
// * `QUARANTINED` - The package is quarantined.
// * `HIDDEN` - The package is hidden.
type PackageStateEnum string

const (
	PackageStateEnumAvailable   PackageStateEnum = "AVAILABLE"
	PackageStateEnumDeleted     PackageStateEnum = "DELETED"
	PackageStateEnumQuarantined PackageStateEnum = "QUARANTINED"
	PackageStateEnumHidden      PackageStateEnum = "HIDDEN"
)

func (e PackageStateEnum) ToPointer() *PackageStateEnum {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PackageStateEnum) IsExact() bool {
	if e != nil {
		switch *e {
		case "AVAILABLE", "DELETED", "QUARANTINED", "HIDDEN":
			return true
		}
	}
	return false
}
