// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PackageTagSourceTypeEnum - * `AUTOMATIC` - Automatic
// * `MANUAL` - Manual
type PackageTagSourceTypeEnum string

const (
	PackageTagSourceTypeEnumAutomatic PackageTagSourceTypeEnum = "AUTOMATIC"
	PackageTagSourceTypeEnumManual    PackageTagSourceTypeEnum = "MANUAL"
)

func (e PackageTagSourceTypeEnum) ToPointer() *PackageTagSourceTypeEnum {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PackageTagSourceTypeEnum) IsExact() bool {
	if e != nil {
		switch *e {
		case "AUTOMATIC", "MANUAL":
			return true
		}
	}
	return false
}
