// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PackageTypeEnum - * `BINARY` - Binary
// * `SOURCE` - Source
// * `COMBINED` - Combined
// * `OTHER` - Other
type PackageTypeEnum string

const (
	PackageTypeEnumBinary   PackageTypeEnum = "BINARY"
	PackageTypeEnumSource   PackageTypeEnum = "SOURCE"
	PackageTypeEnumCombined PackageTypeEnum = "COMBINED"
	PackageTypeEnumOther    PackageTypeEnum = "OTHER"
)

func (e PackageTypeEnum) ToPointer() *PackageTypeEnum {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PackageTypeEnum) IsExact() bool {
	if e != nil {
		switch *e {
		case "BINARY", "SOURCE", "COMBINED", "OTHER":
			return true
		}
	}
	return false
}
