// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PaginatedPolicyDecisionLogList struct {
	Results []PolicyDecisionLog `json:"results"`
}

func (p *PaginatedPolicyDecisionLogList) GetResults() []PolicyDecisionLog {
	if p == nil {
		return []PolicyDecisionLog{}
	}
	return p.Results
}
