// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6af73e398c06

package components

type PaginatedArtifactMetadataReadList struct {
	Results []ArtifactMetadataRead `json:"results"`
}

func (p *PaginatedArtifactMetadataReadList) GetResults() []ArtifactMetadataRead {
	if p == nil {
		return []ArtifactMetadataRead{}
	}
	return p.Results
}
