// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ebc3b04eee65

package components

type PaginatedPolicyActionList struct {
	Results []PolicyAction `json:"results"`
}

func (p *PaginatedPolicyActionList) GetResults() []PolicyAction {
	if p == nil {
		return []PolicyAction{}
	}
	return p.Results
}
