// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 416be70cb64b

package components

type PaginatedPolicyList struct {
	Results []Policy `json:"results"`
	// Total number of pages. Synthesised from the X-Pagination-Pagetotal
	// header by the SDK; not a field returned by the server.
	//
	Pagetotal *int64 `json:"pagetotal,omitzero"`
}

func (p *PaginatedPolicyList) GetResults() []Policy {
	if p == nil {
		return []Policy{}
	}
	return p.Results
}

func (p *PaginatedPolicyList) GetPagetotal() *int64 {
	if p == nil {
		return nil
	}
	return p.Pagetotal
}
