// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3e7ff5fcc590

package components

type PaginatedPolicyDecisionLogV1SummaryList struct {
	Results []PolicyDecisionLogV1Summary `json:"results"`
}

func (p *PaginatedPolicyDecisionLogV1SummaryList) GetResults() []PolicyDecisionLogV1Summary {
	if p == nil {
		return []PolicyDecisionLogV1Summary{}
	}
	return p.Results
}

// #region class-body-paginatedpolicydecisionlogv1summarylist
// #endregion class-body-paginatedpolicydecisionlogv1summarylist
