// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a3b77f53914a

package components

import (
	"github.com/cloudsmith-io/cloudsmith-go-v2/internal/utils"
)

type PatchedRemovePackageTagsPolicyActionTyped struct {
	ActionType *string `json:"action_type,omitzero"`
	// The order in which this action occurs relative to other actions for the same policy.
	Precedence *int64   `json:"precedence,omitzero"`
	Tags       []string `json:"tags,omitzero"`
}

func (p PatchedRemovePackageTagsPolicyActionTyped) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PatchedRemovePackageTagsPolicyActionTyped) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PatchedRemovePackageTagsPolicyActionTyped) GetActionType() *string {
	if p == nil {
		return nil
	}
	return p.ActionType
}

func (p *PatchedRemovePackageTagsPolicyActionTyped) GetPrecedence() *int64 {
	if p == nil {
		return nil
	}
	return p.Precedence
}

func (p *PatchedRemovePackageTagsPolicyActionTyped) GetTags() []string {
	if p == nil {
		return nil
	}
	return p.Tags
}
