// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ea952711c178

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/cloudsmith-io/cloudsmith-go-v2/internal/utils"
)

type PolicyActionRequestType string

const (
	PolicyActionRequestTypeSetPackageState   PolicyActionRequestType = "SetPackageState"
	PolicyActionRequestTypeAddPackageTags    PolicyActionRequestType = "AddPackageTags"
	PolicyActionRequestTypeRemovePackageTags PolicyActionRequestType = "RemovePackageTags"
)

type PolicyActionRequest struct {
	SetPackageStatePolicyActionTypedRequest   *SetPackageStatePolicyActionTypedRequest   `queryParam:"inline" union:"member"`
	AddPackageTagsPolicyActionTypedRequest    *AddPackageTagsPolicyActionTypedRequest    `queryParam:"inline" union:"member"`
	RemovePackageTagsPolicyActionTypedRequest *RemovePackageTagsPolicyActionTypedRequest `queryParam:"inline" union:"member"`

	Type PolicyActionRequestType
}

func CreatePolicyActionRequestSetPackageState(setPackageState SetPackageStatePolicyActionTypedRequest) PolicyActionRequest {
	typ := PolicyActionRequestTypeSetPackageState

	typStr := string(typ)
	setPackageState.ActionType = typStr

	return PolicyActionRequest{
		SetPackageStatePolicyActionTypedRequest: &setPackageState,
		Type:                                    typ,
	}
}

func CreatePolicyActionRequestAddPackageTags(addPackageTags AddPackageTagsPolicyActionTypedRequest) PolicyActionRequest {
	typ := PolicyActionRequestTypeAddPackageTags

	typStr := string(typ)
	addPackageTags.ActionType = typStr

	return PolicyActionRequest{
		AddPackageTagsPolicyActionTypedRequest: &addPackageTags,
		Type:                                   typ,
	}
}

func CreatePolicyActionRequestRemovePackageTags(removePackageTags RemovePackageTagsPolicyActionTypedRequest) PolicyActionRequest {
	typ := PolicyActionRequestTypeRemovePackageTags

	typStr := string(typ)
	removePackageTags.ActionType = typStr

	return PolicyActionRequest{
		RemovePackageTagsPolicyActionTypedRequest: &removePackageTags,
		Type: typ,
	}
}

func (u *PolicyActionRequest) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		ActionType string `json:"action_type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.ActionType {
	case "SetPackageState":
		setPackageStatePolicyActionTypedRequest := new(SetPackageStatePolicyActionTypedRequest)
		if err := utils.UnmarshalJSON(data, &setPackageStatePolicyActionTypedRequest, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ActionType == SetPackageState) type SetPackageStatePolicyActionTypedRequest within PolicyActionRequest: %w", string(data), err)
		}

		u.SetPackageStatePolicyActionTypedRequest = setPackageStatePolicyActionTypedRequest
		u.Type = PolicyActionRequestTypeSetPackageState
		return nil
	case "AddPackageTags":
		addPackageTagsPolicyActionTypedRequest := new(AddPackageTagsPolicyActionTypedRequest)
		if err := utils.UnmarshalJSON(data, &addPackageTagsPolicyActionTypedRequest, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ActionType == AddPackageTags) type AddPackageTagsPolicyActionTypedRequest within PolicyActionRequest: %w", string(data), err)
		}

		u.AddPackageTagsPolicyActionTypedRequest = addPackageTagsPolicyActionTypedRequest
		u.Type = PolicyActionRequestTypeAddPackageTags
		return nil
	case "RemovePackageTags":
		removePackageTagsPolicyActionTypedRequest := new(RemovePackageTagsPolicyActionTypedRequest)
		if err := utils.UnmarshalJSON(data, &removePackageTagsPolicyActionTypedRequest, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ActionType == RemovePackageTags) type RemovePackageTagsPolicyActionTypedRequest within PolicyActionRequest: %w", string(data), err)
		}

		u.RemovePackageTagsPolicyActionTypedRequest = removePackageTagsPolicyActionTypedRequest
		u.Type = PolicyActionRequestTypeRemovePackageTags
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for PolicyActionRequest", string(data))
}

func (u PolicyActionRequest) MarshalJSON() ([]byte, error) {
	if u.SetPackageStatePolicyActionTypedRequest != nil {
		return utils.MarshalJSON(u.SetPackageStatePolicyActionTypedRequest, "", true)
	}

	if u.AddPackageTagsPolicyActionTypedRequest != nil {
		return utils.MarshalJSON(u.AddPackageTagsPolicyActionTypedRequest, "", true)
	}

	if u.RemovePackageTagsPolicyActionTypedRequest != nil {
		return utils.MarshalJSON(u.RemovePackageTagsPolicyActionTypedRequest, "", true)
	}

	return nil, errors.New("could not marshal union type PolicyActionRequest: all fields are null")
}
