// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/cloudsmith-io/cloudsmith-go-v2/internal/utils"
	"github.com/cloudsmith-io/cloudsmith-go-v2/optionalnullable"
	"time"
)

// PolicyRepositoryEcdsaKey - An ECDSA key used to sign repository contents.
type PolicyRepositoryEcdsaKey struct {
	// If selected this is the active key for this repository.
	Active    *bool      `json:"active,omitzero"`
	CreatedAt *time.Time `json:"created_at,omitzero"`
	// If selected this is the default key for this repository.
	Default          *bool  `json:"default,omitzero"`
	FingerprintShort string `json:"fingerprint_short"`
	// The long identifier used by ECDSA for this key.
	Fingerprint string `json:"fingerprint"`
	// The public key given to repository users.
	PublicKey string `json:"public_key"`
	// The SSH fingerprint used by ECDSA for this key.
	SSHFingerprint optionalnullable.OptionalNullable[string] `json:"ssh_fingerprint,omitzero"`
}

func (p PolicyRepositoryEcdsaKey) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PolicyRepositoryEcdsaKey) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PolicyRepositoryEcdsaKey) GetActive() *bool {
	if p == nil {
		return nil
	}
	return p.Active
}

func (p *PolicyRepositoryEcdsaKey) GetCreatedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.CreatedAt
}

func (p *PolicyRepositoryEcdsaKey) GetDefault() *bool {
	if p == nil {
		return nil
	}
	return p.Default
}

func (p *PolicyRepositoryEcdsaKey) GetFingerprintShort() string {
	if p == nil {
		return ""
	}
	return p.FingerprintShort
}

func (p *PolicyRepositoryEcdsaKey) GetFingerprint() string {
	if p == nil {
		return ""
	}
	return p.Fingerprint
}

func (p *PolicyRepositoryEcdsaKey) GetPublicKey() string {
	if p == nil {
		return ""
	}
	return p.PublicKey
}

func (p *PolicyRepositoryEcdsaKey) GetSSHFingerprint() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.SSHFingerprint
}
