// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a0ccb2f47b01

package components

// PolicyAdvisorySource - The source of the advisory.
type PolicyAdvisorySource struct {
	// The advisory source name.
	Name string `json:"name"`
	// The advisory source URL.
	URL string `json:"url"`
}

func (p *PolicyAdvisorySource) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PolicyAdvisorySource) GetURL() string {
	if p == nil {
		return ""
	}
	return p.URL
}
