// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a19ebd415746

package components

import (
	"github.com/cloudsmith-io/cloudsmith-go-v2/optionalnullable"
)

type PolicyRequest struct {
	// The description of the Policy.
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	// The name of the Policy.
	Name string `json:"name"`
	// The rego code which constitutes the Policy logic.
	Rego string `json:"rego"`
	// If true, the policy is enabled.
	Enabled *bool `json:"enabled,omitzero"`
	// If true and the policy matches, no further policies are evaluated.
	IsTerminal *bool `json:"is_terminal,omitzero"`
	// The order in which this policy is evaluated relative to other policies.
	Precedence *int64 `json:"precedence,omitzero"`
}

func (p *PolicyRequest) GetDescription() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PolicyRequest) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PolicyRequest) GetRego() string {
	if p == nil {
		return ""
	}
	return p.Rego
}

func (p *PolicyRequest) GetEnabled() *bool {
	if p == nil {
		return nil
	}
	return p.Enabled
}

func (p *PolicyRequest) GetIsTerminal() *bool {
	if p == nil {
		return nil
	}
	return p.IsTerminal
}

func (p *PolicyRequest) GetPrecedence() *int64 {
	if p == nil {
		return nil
	}
	return p.Precedence
}
