// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c31ff87fe38a

package components

import (
	"github.com/cloudsmith-io/cloudsmith-go-v2/internal/utils"
	"time"
)

// PolicyRepositoryGpgKey - A GPG key used to sign repository contents.
type PolicyRepositoryGpgKey struct {
	// If selected this is the active key for this repository.
	Active    *bool      `json:"active,omitzero"`
	Comment   string     `json:"comment"`
	CreatedAt *time.Time `json:"created_at,omitzero"`
	// If selected this is the default key for this repository.
	Default          *bool  `json:"default,omitzero"`
	FingerprintShort string `json:"fingerprint_short"`
	// The long identifier used by GPG for this key.
	Fingerprint string `json:"fingerprint"`
	// The public key given to repository users.
	PublicKey string `json:"public_key"`
}

func (p PolicyRepositoryGpgKey) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PolicyRepositoryGpgKey) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PolicyRepositoryGpgKey) GetActive() *bool {
	if p == nil {
		return nil
	}
	return p.Active
}

func (p *PolicyRepositoryGpgKey) GetComment() string {
	if p == nil {
		return ""
	}
	return p.Comment
}

func (p *PolicyRepositoryGpgKey) GetCreatedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.CreatedAt
}

func (p *PolicyRepositoryGpgKey) GetDefault() *bool {
	if p == nil {
		return nil
	}
	return p.Default
}

func (p *PolicyRepositoryGpgKey) GetFingerprintShort() string {
	if p == nil {
		return ""
	}
	return p.FingerprintShort
}

func (p *PolicyRepositoryGpgKey) GetFingerprint() string {
	if p == nil {
		return ""
	}
	return p.Fingerprint
}

func (p *PolicyRepositoryGpgKey) GetPublicKey() string {
	if p == nil {
		return ""
	}
	return p.PublicKey
}
