// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 14cae9cc2d71

package components

// PolicyOSVSeverity - Describes the severity of a vulnerability using one or more quantitative scoring methods.
type PolicyOSVSeverity struct {
	// The type of severity being described. The type indicates how the associated score should be interpreted.
	//
	// * `Ubuntu` - An "Ubuntu" severity type indicates that the associated score is a lowercased string
	//     representing the Ubuntu priority.
	//
	//     If a severity has this type, the associated "score" will be one of "negligible",
	//     "low", "medium", "high", or "critical".
	//
	//     See https://ubuntu.com/security/cves/about#priority for more information.
	//
	// * `CVSS_V2` - A "CVSS_V2" severity type indicates that the associated score is a CVSS vector
	//     string using a version of the Common Vulnerability Scoring System notation that
	//     is == 2.0 (e.g."AV:L/AC:M/Au:N/C:N/I:P/A:C").
	//
	// * `CVSS_V3` - A "CVSS_V3" severity type indicates that the associated score is a CVSS vector string
	//     using a version of the Common Vulnerability Scoring System notation that
	//     is >= 3.0 and < 4.0 (e.g."CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:H/I:N/A:N").
	//
	// * `CVSS_V4` - A "CVSS_V4" severity type indicates that the associated score is a CVSS vector string
	//     using a version of the Common Vulnerability Scoring System notation that
	//     is >= 4.0 and < 5.0 (e.g. "CVSS:4.0/AV:N/AC:L/AT:N/PR:H/UI:N/VC:L/VI:L/VA:N/SC:N/SI:N/SA:N").
	//
	Type PolicyOSVSeverityTypeEnum `json:"type"`
	// The score of the vulnerability. This should be interpreted differently depending on the severity type.
	Score string `json:"score"`
	// A pre-calculated numerical score (added as a convenience by Cloudsmith) for CVSS severity types, based on the CVSS vector provided by OSV. For the UBUNTU severity type, this field is null.
	NumericalScore *float64 `json:"numerical_score"`
}

func (p *PolicyOSVSeverity) GetType() PolicyOSVSeverityTypeEnum {
	if p == nil {
		return PolicyOSVSeverityTypeEnum("")
	}
	return p.Type
}

func (p *PolicyOSVSeverity) GetScore() string {
	if p == nil {
		return ""
	}
	return p.Score
}

func (p *PolicyOSVSeverity) GetNumericalScore() *float64 {
	if p == nil {
		return nil
	}
	return p.NumericalScore
}
