// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/cloudsmith-io/cloudsmith-go-v2/internal/utils"
	"github.com/cloudsmith-io/cloudsmith-go-v2/optionalnullable"
)

// PolicyArchitecture - The package architecture for policy purposes.
type PolicyArchitecture struct {
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	Name        string                                    `json:"name"`
}

func (p PolicyArchitecture) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PolicyArchitecture) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PolicyArchitecture) GetDescription() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PolicyArchitecture) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}
