// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b775d2b5a4d6

package components

import (
	"github.com/cloudsmith-io/cloudsmith-go-v2/internal/utils"
	"time"
)

// PolicyDecisionLog - Serializer for policy decision logs
type PolicyDecisionLog struct {
	ID            *string   `json:"id,omitzero"`
	CorrelationID string    `json:"correlation_id"`
	Policy        Policy    `json:"policy"`
	StartedAt     time.Time `json:"started_at"`
	EndedAt       time.Time `json:"ended_at"`
	// Serializer for policy input.
	PolicyInput  PolicyInput2 `json:"policy_input"`
	PolicyOutput any          `json:"policy_output"`
	// The actions configured against the policy.
	Actions []PolicyAction `json:"actions"`
	// The actions which were invoked on this package.
	ParsedActions any `json:"parsed_actions"`
}

func (p PolicyDecisionLog) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PolicyDecisionLog) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PolicyDecisionLog) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *PolicyDecisionLog) GetCorrelationID() string {
	if p == nil {
		return ""
	}
	return p.CorrelationID
}

func (p *PolicyDecisionLog) GetPolicy() Policy {
	if p == nil {
		return Policy{}
	}
	return p.Policy
}

func (p *PolicyDecisionLog) GetStartedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.StartedAt
}

func (p *PolicyDecisionLog) GetEndedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.EndedAt
}

func (p *PolicyDecisionLog) GetPolicyInput() PolicyInput2 {
	if p == nil {
		return PolicyInput2{}
	}
	return p.PolicyInput
}

func (p *PolicyDecisionLog) GetPolicyOutput() any {
	if p == nil {
		return nil
	}
	return p.PolicyOutput
}

func (p *PolicyDecisionLog) GetActions() []PolicyAction {
	if p == nil {
		return []PolicyAction{}
	}
	return p.Actions
}

func (p *PolicyDecisionLog) GetParsedActions() any {
	if p == nil {
		return nil
	}
	return p.ParsedActions
}
