// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ec3571adafa2

package components

// PolicyInput - Serializer for policy input.
type PolicyInput struct {
	// Serializer for V0 policy input.
	V0 PolicyInputV0 `json:"v0"`
}

func (p *PolicyInput) GetV0() PolicyInputV0 {
	if p == nil {
		return PolicyInputV0{}
	}
	return p.V0
}
