// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9317c73532e5

package components

import (
	"github.com/cloudsmith-io/cloudsmith-go-v2/internal/utils"
)

// PolicyDistributionVersion - The version of  distribution of the package for policy purposes.
type PolicyDistributionVersion struct {
	// The textual name for this version.
	Name *string `json:"name,omitzero"`
	Slug string  `json:"slug"`
}

func (p PolicyDistributionVersion) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PolicyDistributionVersion) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PolicyDistributionVersion) GetName() *string {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *PolicyDistributionVersion) GetSlug() string {
	if p == nil {
		return ""
	}
	return p.Slug
}
