// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/cloudsmith-io/cloudsmith-go-v2/internal/utils"
	"time"
)

// PolicyDecisionLogV1Summary - A summary of a policy decision log.
type PolicyDecisionLogV1Summary struct {
	// A ULID which uniquely identifies this decision log in the context of the correlation_id.
	ID      string         `json:"id"`
	Actions map[string]any `json:"actions"`
	// A UUID which identifies the group of decision logs which were generated off the back of a single evaluation trigger.
	CorrelationID string    `json:"correlation_id"`
	EndedAt       time.Time `json:"ended_at"`
	// Whether the policy evaluation matched the package.
	Match bool `json:"match"`
	// The format of the package which policy evaluation occurred for.
	PackageFormat string `json:"package_format"`
	// The name of the package which policy evaluation occurred for.
	PackageName string `json:"package_name"`
	// The slug of the package which policy evaluation occurred for.
	PackageSlug string `json:"package_slug"`
	// The identifier of the package which policy evaluation occurred for.
	PackageSlugPerm string `json:"package_slug_perm"`
	// The version of the package which policy evaluation occurred for.
	PackageVersion string `json:"package_version"`
	// Whether the evaluated policy was terminal.
	PolicyIsTerminal bool `json:"policy_is_terminal"`
	// The name of the policy.
	PolicyName string `json:"policy_name"`
	// The order in which the policy was evaluated relative to other policies in the same correlation_id group.
	PolicyPrecedence int64 `json:"policy_precedence"`
	// The identifier of the policy.
	PolicySlugPerm string `json:"policy_slug_perm"`
	// The version of the policy.
	PolicyVersion int64 `json:"policy_version"`
	// The name of the repository which the package belongs to.
	RepositoryName string `json:"repository_name"`
	// The slug of the repository which the package belongs to.
	RepositorySlug string `json:"repository_slug"`
	// The identifier of the repository which the package belongs to.
	RepositorySlugPerm string `json:"repository_slug_perm"`
	// The date and time at which policy evaluation started.
	StartedAt time.Time `json:"started_at"`
}

func (p PolicyDecisionLogV1Summary) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PolicyDecisionLogV1Summary) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PolicyDecisionLogV1Summary) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PolicyDecisionLogV1Summary) GetActions() map[string]any {
	if p == nil {
		return map[string]any{}
	}
	return p.Actions
}

func (p *PolicyDecisionLogV1Summary) GetCorrelationID() string {
	if p == nil {
		return ""
	}
	return p.CorrelationID
}

func (p *PolicyDecisionLogV1Summary) GetEndedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.EndedAt
}

func (p *PolicyDecisionLogV1Summary) GetMatch() bool {
	if p == nil {
		return false
	}
	return p.Match
}

func (p *PolicyDecisionLogV1Summary) GetPackageFormat() string {
	if p == nil {
		return ""
	}
	return p.PackageFormat
}

func (p *PolicyDecisionLogV1Summary) GetPackageName() string {
	if p == nil {
		return ""
	}
	return p.PackageName
}

func (p *PolicyDecisionLogV1Summary) GetPackageSlug() string {
	if p == nil {
		return ""
	}
	return p.PackageSlug
}

func (p *PolicyDecisionLogV1Summary) GetPackageSlugPerm() string {
	if p == nil {
		return ""
	}
	return p.PackageSlugPerm
}

func (p *PolicyDecisionLogV1Summary) GetPackageVersion() string {
	if p == nil {
		return ""
	}
	return p.PackageVersion
}

func (p *PolicyDecisionLogV1Summary) GetPolicyIsTerminal() bool {
	if p == nil {
		return false
	}
	return p.PolicyIsTerminal
}

func (p *PolicyDecisionLogV1Summary) GetPolicyName() string {
	if p == nil {
		return ""
	}
	return p.PolicyName
}

func (p *PolicyDecisionLogV1Summary) GetPolicyPrecedence() int64 {
	if p == nil {
		return 0
	}
	return p.PolicyPrecedence
}

func (p *PolicyDecisionLogV1Summary) GetPolicySlugPerm() string {
	if p == nil {
		return ""
	}
	return p.PolicySlugPerm
}

func (p *PolicyDecisionLogV1Summary) GetPolicyVersion() int64 {
	if p == nil {
		return 0
	}
	return p.PolicyVersion
}

func (p *PolicyDecisionLogV1Summary) GetRepositoryName() string {
	if p == nil {
		return ""
	}
	return p.RepositoryName
}

func (p *PolicyDecisionLogV1Summary) GetRepositorySlug() string {
	if p == nil {
		return ""
	}
	return p.RepositorySlug
}

func (p *PolicyDecisionLogV1Summary) GetRepositorySlugPerm() string {
	if p == nil {
		return ""
	}
	return p.RepositorySlugPerm
}

func (p *PolicyDecisionLogV1Summary) GetStartedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.StartedAt
}

// #region class-body-policydecisionlogv1summary
// #endregion class-body-policydecisionlogv1summary
