// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PolicyAdvisoryCvss - A CVSS score and vector string.
type PolicyAdvisoryCvss struct {
	// The CVSS V2 score.
	V2Score *float64 `json:"V2Score"`
	// The CVSS V2 vector string.
	V2Vector *string `json:"V2Vector"`
	// The CVSS V3 score.
	V3Score *float64 `json:"V3Score"`
	// The CVSS V3 vector string.
	V3Vector *string `json:"V3Vector"`
}

func (p *PolicyAdvisoryCvss) GetV2Score() *float64 {
	if p == nil {
		return nil
	}
	return p.V2Score
}

func (p *PolicyAdvisoryCvss) GetV2Vector() *string {
	if p == nil {
		return nil
	}
	return p.V2Vector
}

func (p *PolicyAdvisoryCvss) GetV3Score() *float64 {
	if p == nil {
		return nil
	}
	return p.V3Score
}

func (p *PolicyAdvisoryCvss) GetV3Vector() *string {
	if p == nil {
		return nil
	}
	return p.V3Vector
}
