// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ab105bcc43ca

package components

import (
	"github.com/cloudsmith-io/cloudsmith-go-v2/internal/utils"
	"time"
)

// Epss - The EPSS details. Null if not available.
type Epss struct {
	// The EPSS score. Null if not available.
	Score *float64 `json:"score"`
	// The EPSS percentile. Null if not available.
	Percentile *float64 `json:"percentile"`
}

func (e *Epss) GetScore() *float64 {
	if e == nil {
		return nil
	}
	return e.Score
}

func (e *Epss) GetPercentile() *float64 {
	if e == nil {
		return nil
	}
	return e.Percentile
}

// PolicyAdvisory - An Advisory is all the known information about a vulnerability.
type PolicyAdvisory struct {
	// The CVSS score details.
	Cvss map[string]PolicyAdvisoryCvss `json:"cvss"`
	// The EPSS details. Null if not available.
	Epss *Epss `json:"epss"`
	// The format of the vulnerable package.
	Format string `json:"format"`
	// The vulnerability identifier. E.g. CVE-2021-1234.
	Identifier string `json:"identifier"`
	// The name of the vulnerable package.
	PackageName string `json:"package_name"`
	// List of patched versions, if available.
	PatchedVersions []string `json:"patched_versions"`
	// The published date of vulnerability.
	PublishedDate time.Time `json:"published_date"`
	// The severity level of the vulnerability.
	//
	// * `LOW` - LOW
	// * `MEDIUM` - MEDIUM
	// * `HIGH` - HIGH
	// * `CRITICAL` - CRITICAL
	Severity SeverityEnum `json:"severity"`
	// The advisory source details.
	Source PolicyAdvisorySource `json:"source"`
	// The title of the advisory.
	Title string `json:"title"`
	// List of known vulnerable versions.
	VulnerableVersions []string `json:"vulnerable_versions"`
}

func (p PolicyAdvisory) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PolicyAdvisory) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PolicyAdvisory) GetCvss() map[string]PolicyAdvisoryCvss {
	if p == nil {
		return nil
	}
	return p.Cvss
}

func (p *PolicyAdvisory) GetEpss() *Epss {
	if p == nil {
		return nil
	}
	return p.Epss
}

func (p *PolicyAdvisory) GetFormat() string {
	if p == nil {
		return ""
	}
	return p.Format
}

func (p *PolicyAdvisory) GetIdentifier() string {
	if p == nil {
		return ""
	}
	return p.Identifier
}

func (p *PolicyAdvisory) GetPackageName() string {
	if p == nil {
		return ""
	}
	return p.PackageName
}

func (p *PolicyAdvisory) GetPatchedVersions() []string {
	if p == nil {
		return []string{}
	}
	return p.PatchedVersions
}

func (p *PolicyAdvisory) GetPublishedDate() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.PublishedDate
}

func (p *PolicyAdvisory) GetSeverity() SeverityEnum {
	if p == nil {
		return SeverityEnum("")
	}
	return p.Severity
}

func (p *PolicyAdvisory) GetSource() PolicyAdvisorySource {
	if p == nil {
		return PolicyAdvisorySource{}
	}
	return p.Source
}

func (p *PolicyAdvisory) GetTitle() string {
	if p == nil {
		return ""
	}
	return p.Title
}

func (p *PolicyAdvisory) GetVulnerableVersions() []string {
	if p == nil {
		return []string{}
	}
	return p.VulnerableVersions
}
