// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PolicyOSVSeverityTypeEnum - * `Ubuntu` - An "Ubuntu" severity type indicates that the associated score is a lowercased string
//
//	representing the Ubuntu priority.
//
//	If a severity has this type, the associated "score" will be one of "negligible",
//	"low", "medium", "high", or "critical".
//
//	See https://ubuntu.com/security/cves/about#priority for more information.
//
//   - `CVSS_V2` - A "CVSS_V2" severity type indicates that the associated score is a CVSS vector
//     string using a version of the Common Vulnerability Scoring System notation that
//     is == 2.0 (e.g."AV:L/AC:M/Au:N/C:N/I:P/A:C").
//
//   - `CVSS_V3` - A "CVSS_V3" severity type indicates that the associated score is a CVSS vector string
//     using a version of the Common Vulnerability Scoring System notation that
//     is >= 3.0 and < 4.0 (e.g."CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:H/I:N/A:N").
//
//   - `CVSS_V4` - A "CVSS_V4" severity type indicates that the associated score is a CVSS vector string
//     using a version of the Common Vulnerability Scoring System notation that
//     is >= 4.0 and < 5.0 (e.g. "CVSS:4.0/AV:N/AC:L/AT:N/PR:H/UI:N/VC:L/VI:L/VA:N/SC:N/SI:N/SA:N").
type PolicyOSVSeverityTypeEnum string

const (
	PolicyOSVSeverityTypeEnumUbuntu PolicyOSVSeverityTypeEnum = "Ubuntu"
	PolicyOSVSeverityTypeEnumCvssV2 PolicyOSVSeverityTypeEnum = "CVSS_V2"
	PolicyOSVSeverityTypeEnumCvssV3 PolicyOSVSeverityTypeEnum = "CVSS_V3"
	PolicyOSVSeverityTypeEnumCvssV4 PolicyOSVSeverityTypeEnum = "CVSS_V4"
)

func (e PolicyOSVSeverityTypeEnum) ToPointer() *PolicyOSVSeverityTypeEnum {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PolicyOSVSeverityTypeEnum) IsExact() bool {
	if e != nil {
		switch *e {
		case "Ubuntu", "CVSS_V2", "CVSS_V3", "CVSS_V4":
			return true
		}
	}
	return false
}
