// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/cloudsmith-io/cloudsmith-go-v2/internal/utils"
	"github.com/cloudsmith-io/cloudsmith-go-v2/optionalnullable"
	"time"
)

// PolicyPackageTypedUpstreamMetadata - Additional information in the form of arbitrary metadata that may be copied or added from the upstream source during upstream caching. For example the published at timestamp, or attestations etc.
type PolicyPackageTypedUpstreamMetadata struct {
	PublishedAt optionalnullable.OptionalNullable[time.Time] `json:"published_at,omitzero"`
}

func (p PolicyPackageTypedUpstreamMetadata) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PolicyPackageTypedUpstreamMetadata) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PolicyPackageTypedUpstreamMetadata) GetPublishedAt() optionalnullable.OptionalNullable[time.Time] {
	if p == nil {
		return nil
	}
	return p.PublishedAt
}

// PolicyPackageTyped - The details of the package for policy purposes.
type PolicyPackageTyped struct {
	Format         string               `json:"format"`
	Architectures  []PolicyArchitecture `json:"architectures"`
	ChecksumMd5    string               `json:"checksum_md5"`
	ChecksumSha1   string               `json:"checksum_sha1"`
	ChecksumSha256 string               `json:"checksum_sha256"`
	ChecksumSha512 string               `json:"checksum_sha512"`
	// A textual description of this package.
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	// The distribution of the package for policy purposes.
	Distro PolicyDistribution `json:"distro"`
	// The version of  distribution of the package for policy purposes.
	DistroVersion PolicyDistributionVersion `json:"distro_version"`
	// The epoch of the package version (if any).
	Epoch     optionalnullable.OptionalNullable[int64] `json:"epoch,omitzero"`
	Extension string                                   `json:"extension"`
	Filename  string                                   `json:"filename"`
	Files     []PolicyPackageFile                      `json:"files"`
	Indexed   *bool                                    `json:"indexed,omitzero"`
	// Whether the package is cached in the repository or proxied from an upstream
	IsLocal bool `json:"is_local"`
	// The last time the package was downloaded.
	LastDownloadedAt time.Time `json:"last_downloaded_at"`
	// The licensing details of a package.
	License PolicyPackageLicense `json:"license"`
	// The name of this package.
	Name     optionalnullable.OptionalNullable[string] `json:"name,omitzero"`
	NumFiles *int64                                    `json:"num_files,omitzero"`
	// * `BINARY` - Binary
	// * `SOURCE` - Source
	// * `COMBINED` - Combined
	// * `OTHER` - Other
	PackageType PackageTypeEnum `json:"package_type"`
	// The release of the package version (if any).
	Release optionalnullable.OptionalNullable[string] `json:"release,omitzero"`
	// The datetime the security scanning was completed.
	SecurityScanCompletedAt optionalnullable.OptionalNullable[time.Time] `json:"security_scan_completed_at,omitzero"`
	// The datetime the security scanning was started.
	SecurityScanStartedAt optionalnullable.OptionalNullable[time.Time] `json:"security_scan_started_at,omitzero"`
	// * `AWAITING_SCAN` - Awaiting Security Scan
	// * `SCANNING` - Security Scanning in Progress
	// * `VULNERABLE` - Scan Detected Vulnerabilities
	// * `NOT_VULNERABLE` - Scan Detected No Vulnerabilities
	// * `DISABLED` - Security Scanning Disabled
	// * `FAILED` - Security Scanning Failed
	// * `SKIPPED` - Security Scanning Skipped
	// * `UNSUPPORTED_PACKAGE` - Security Scanning Not Supported
	// * `UNSUPPORTED_FORMAT` - Security Scanning Not Supported
	SecurityScanStatus SecurityScanStatusEnum `json:"security_scan_status"`
	// The datetime the security scanning status was updated.
	SecurityScanStatusUpdatedAt optionalnullable.OptionalNullable[time.Time] `json:"security_scan_status_updated_at,omitzero"`
	// The calculated size of the package.
	Size *int64 `json:"size,omitzero"`
	// The public unique identifier for the package.
	Slug     string  `json:"slug"`
	SlugPerm *string `json:"slug_perm,omitzero"`
	Subtype  string  `json:"subtype"`
	// A one-liner synopsis of this package.
	Summary optionalnullable.OptionalNullable[string] `json:"summary,omitzero"`
	Tags    []PolicyPackageTag                        `json:"tags"`
	// The date this package was uploaded.
	UploadedAt *time.Time `json:"uploaded_at,omitzero"`
	// The package uploader for policy puposes.
	Uploader *PolicyUploader `json:"uploader,omitzero"`
	// Additional information in the form of arbitrary metadata that may be copied or added from the upstream source during upstream caching. For example the published at timestamp, or attestations etc.
	UpstreamMetadata optionalnullable.OptionalNullable[PolicyPackageTypedUpstreamMetadata] `json:"upstream_metadata,omitzero"`
	// The raw version for this package.
	Version optionalnullable.OptionalNullable[string] `json:"version,omitzero"`
}

func (p PolicyPackageTyped) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PolicyPackageTyped) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PolicyPackageTyped) GetFormat() string {
	if p == nil {
		return ""
	}
	return p.Format
}

func (p *PolicyPackageTyped) GetArchitectures() []PolicyArchitecture {
	if p == nil {
		return []PolicyArchitecture{}
	}
	return p.Architectures
}

func (p *PolicyPackageTyped) GetChecksumMd5() string {
	if p == nil {
		return ""
	}
	return p.ChecksumMd5
}

func (p *PolicyPackageTyped) GetChecksumSha1() string {
	if p == nil {
		return ""
	}
	return p.ChecksumSha1
}

func (p *PolicyPackageTyped) GetChecksumSha256() string {
	if p == nil {
		return ""
	}
	return p.ChecksumSha256
}

func (p *PolicyPackageTyped) GetChecksumSha512() string {
	if p == nil {
		return ""
	}
	return p.ChecksumSha512
}

func (p *PolicyPackageTyped) GetDescription() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PolicyPackageTyped) GetDistro() PolicyDistribution {
	if p == nil {
		return PolicyDistribution{}
	}
	return p.Distro
}

func (p *PolicyPackageTyped) GetDistroVersion() PolicyDistributionVersion {
	if p == nil {
		return PolicyDistributionVersion{}
	}
	return p.DistroVersion
}

func (p *PolicyPackageTyped) GetEpoch() optionalnullable.OptionalNullable[int64] {
	if p == nil {
		return nil
	}
	return p.Epoch
}

func (p *PolicyPackageTyped) GetExtension() string {
	if p == nil {
		return ""
	}
	return p.Extension
}

func (p *PolicyPackageTyped) GetFilename() string {
	if p == nil {
		return ""
	}
	return p.Filename
}

func (p *PolicyPackageTyped) GetFiles() []PolicyPackageFile {
	if p == nil {
		return []PolicyPackageFile{}
	}
	return p.Files
}

func (p *PolicyPackageTyped) GetIndexed() *bool {
	if p == nil {
		return nil
	}
	return p.Indexed
}

func (p *PolicyPackageTyped) GetIsLocal() bool {
	if p == nil {
		return false
	}
	return p.IsLocal
}

func (p *PolicyPackageTyped) GetLastDownloadedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.LastDownloadedAt
}

func (p *PolicyPackageTyped) GetLicense() PolicyPackageLicense {
	if p == nil {
		return PolicyPackageLicense{}
	}
	return p.License
}

func (p *PolicyPackageTyped) GetName() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *PolicyPackageTyped) GetNumFiles() *int64 {
	if p == nil {
		return nil
	}
	return p.NumFiles
}

func (p *PolicyPackageTyped) GetPackageType() PackageTypeEnum {
	if p == nil {
		return PackageTypeEnum("")
	}
	return p.PackageType
}

func (p *PolicyPackageTyped) GetRelease() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Release
}

func (p *PolicyPackageTyped) GetSecurityScanCompletedAt() optionalnullable.OptionalNullable[time.Time] {
	if p == nil {
		return nil
	}
	return p.SecurityScanCompletedAt
}

func (p *PolicyPackageTyped) GetSecurityScanStartedAt() optionalnullable.OptionalNullable[time.Time] {
	if p == nil {
		return nil
	}
	return p.SecurityScanStartedAt
}

func (p *PolicyPackageTyped) GetSecurityScanStatus() SecurityScanStatusEnum {
	if p == nil {
		return SecurityScanStatusEnum("")
	}
	return p.SecurityScanStatus
}

func (p *PolicyPackageTyped) GetSecurityScanStatusUpdatedAt() optionalnullable.OptionalNullable[time.Time] {
	if p == nil {
		return nil
	}
	return p.SecurityScanStatusUpdatedAt
}

func (p *PolicyPackageTyped) GetSize() *int64 {
	if p == nil {
		return nil
	}
	return p.Size
}

func (p *PolicyPackageTyped) GetSlug() string {
	if p == nil {
		return ""
	}
	return p.Slug
}

func (p *PolicyPackageTyped) GetSlugPerm() *string {
	if p == nil {
		return nil
	}
	return p.SlugPerm
}

func (p *PolicyPackageTyped) GetSubtype() string {
	if p == nil {
		return ""
	}
	return p.Subtype
}

func (p *PolicyPackageTyped) GetSummary() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Summary
}

func (p *PolicyPackageTyped) GetTags() []PolicyPackageTag {
	if p == nil {
		return []PolicyPackageTag{}
	}
	return p.Tags
}

func (p *PolicyPackageTyped) GetUploadedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.UploadedAt
}

func (p *PolicyPackageTyped) GetUploader() *PolicyUploader {
	if p == nil {
		return nil
	}
	return p.Uploader
}

func (p *PolicyPackageTyped) GetUpstreamMetadata() optionalnullable.OptionalNullable[PolicyPackageTypedUpstreamMetadata] {
	if p == nil {
		return nil
	}
	return p.UpstreamMetadata
}

func (p *PolicyPackageTyped) GetVersion() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Version
}
