// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 63e23651c562

package components

import (
	"github.com/cloudsmith-io/cloudsmith-go-v2/internal/utils"
	"github.com/cloudsmith-io/cloudsmith-go-v2/optionalnullable"
)

// PolicyUploader - The package uploader for policy puposes.
type PolicyUploader struct {
	// Your email address that we use to contact you. This is only visible to you.
	Email     optionalnullable.OptionalNullable[string] `json:"email,omitzero"`
	FirstName string                                    `json:"first_name"`
	LastName  string                                    `json:"last_name"`
	Slug      string                                    `json:"slug"`
	SlugPerm  string                                    `json:"slug_perm"`
}

func (p PolicyUploader) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PolicyUploader) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PolicyUploader) GetEmail() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Email
}

func (p *PolicyUploader) GetFirstName() string {
	if p == nil {
		return ""
	}
	return p.FirstName
}

func (p *PolicyUploader) GetLastName() string {
	if p == nil {
		return ""
	}
	return p.LastName
}

func (p *PolicyUploader) GetSlug() string {
	if p == nil {
		return ""
	}
	return p.Slug
}

func (p *PolicyUploader) GetSlugPerm() string {
	if p == nil {
		return ""
	}
	return p.SlugPerm
}
