// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/cloudsmith-io/cloudsmith-go-v2/internal/utils"
	"github.com/cloudsmith-io/cloudsmith-go-v2/optionalnullable"
)

// PolicyHuggingfaceEvalResult - The evaluation results of model-card of a Huggingface package.
//
// A flattened version of the evaluation results from the model card.
type PolicyHuggingfaceEvalResult struct {
	// The task identifier, e.g. image-classification.
	TaskType string `json:"task_type"`
	// The dataset identifier, e.g.g common_voice.
	DatasetType string `json:"dataset_type"`
	// A pretty name for the dataset, e.g. Common Voice.
	DatasetName string `json:"dataset_name"`
	// The metric identifier, e.g. accuracy.
	MetricType string `json:"metric_type"`
	// The value fo the metric, e.g. 0.95.
	MetricValue string `json:"metric_value"`
	// The pretty name of the task, e.g. Speech Recognition.
	TaskName optionalnullable.OptionalNullable[string] `json:"task_name,omitzero"`
	// The name of the dataset configuration used in `load_dataset()`.
	DatasetConfig optionalnullable.OptionalNullable[string] `json:"dataset_config,omitzero"`
	// The split used in the `load_dataset()`.
	DatasetSplit optionalnullable.OptionalNullable[string] `json:"dataset_split,omitzero"`
	// The revision (aka git sha) of the dataset used in `load_dataset()`.
	DatasetRevision optionalnullable.OptionalNullable[string] `json:"dataset_revision,omitzero"`
	// The arguments passed during `Metric.compute()`.
	DatasetArgs optionalnullable.OptionalNullable[map[string]any] `json:"dataset_args,omitzero"`
	// A pretty name for the metric, e.g. Accuracy.
	MetricName optionalnullable.OptionalNullable[string] `json:"metric_name,omitzero"`
	// The name of metric used in `load_metric()`.
	MetricConfig optionalnullable.OptionalNullable[string] `json:"metric_config,omitzero"`
	// The arguments passed during `Metric.compute()`.
	MetricArgs optionalnullable.OptionalNullable[map[string]any] `json:"metric_args,omitzero"`
	// Indicates if the metrics originate from Hugging Face's evaluation serivce.
	Verified optionalnullable.OptionalNullable[bool] `json:"verified,omitzero"`
	// A JWT token used to verify the metrics origin.
	VerifyToken optionalnullable.OptionalNullable[string] `json:"verify_token,omitzero"`
	// The name of the source of the evaluation result, e.g. Open LLM Leaderboard.
	SourceName optionalnullable.OptionalNullable[string] `json:"source_name,omitzero"`
	// The url of the source of the evalatuation result.
	SourceURL optionalnullable.OptionalNullable[string] `json:"source_url,omitzero"`
}

func (p PolicyHuggingfaceEvalResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PolicyHuggingfaceEvalResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PolicyHuggingfaceEvalResult) GetTaskType() string {
	if p == nil {
		return ""
	}
	return p.TaskType
}

func (p *PolicyHuggingfaceEvalResult) GetDatasetType() string {
	if p == nil {
		return ""
	}
	return p.DatasetType
}

func (p *PolicyHuggingfaceEvalResult) GetDatasetName() string {
	if p == nil {
		return ""
	}
	return p.DatasetName
}

func (p *PolicyHuggingfaceEvalResult) GetMetricType() string {
	if p == nil {
		return ""
	}
	return p.MetricType
}

func (p *PolicyHuggingfaceEvalResult) GetMetricValue() string {
	if p == nil {
		return ""
	}
	return p.MetricValue
}

func (p *PolicyHuggingfaceEvalResult) GetTaskName() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.TaskName
}

func (p *PolicyHuggingfaceEvalResult) GetDatasetConfig() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.DatasetConfig
}

func (p *PolicyHuggingfaceEvalResult) GetDatasetSplit() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.DatasetSplit
}

func (p *PolicyHuggingfaceEvalResult) GetDatasetRevision() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.DatasetRevision
}

func (p *PolicyHuggingfaceEvalResult) GetDatasetArgs() optionalnullable.OptionalNullable[map[string]any] {
	if p == nil {
		return nil
	}
	return p.DatasetArgs
}

func (p *PolicyHuggingfaceEvalResult) GetMetricName() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.MetricName
}

func (p *PolicyHuggingfaceEvalResult) GetMetricConfig() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.MetricConfig
}

func (p *PolicyHuggingfaceEvalResult) GetMetricArgs() optionalnullable.OptionalNullable[map[string]any] {
	if p == nil {
		return nil
	}
	return p.MetricArgs
}

func (p *PolicyHuggingfaceEvalResult) GetVerified() optionalnullable.OptionalNullable[bool] {
	if p == nil {
		return nil
	}
	return p.Verified
}

func (p *PolicyHuggingfaceEvalResult) GetVerifyToken() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.VerifyToken
}

func (p *PolicyHuggingfaceEvalResult) GetSourceName() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.SourceName
}

func (p *PolicyHuggingfaceEvalResult) GetSourceURL() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.SourceURL
}
