// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 67f69fd09238

package components

import (
	"github.com/cloudsmith-io/cloudsmith-go-v2/internal/utils"
)

type RemovePackageTagsPolicyActionTypedInput struct {
	ActionType string `json:"action_type"`
	// The order in which this action occurs relative to other actions for the same policy.
	Precedence *int64   `json:"precedence,omitzero"`
	Tags       []string `json:"tags"`
}

func (r RemovePackageTagsPolicyActionTypedInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RemovePackageTagsPolicyActionTypedInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RemovePackageTagsPolicyActionTypedInput) GetActionType() string {
	if r == nil {
		return ""
	}
	return r.ActionType
}

func (r *RemovePackageTagsPolicyActionTypedInput) GetPrecedence() *int64 {
	if r == nil {
		return nil
	}
	return r.Precedence
}

func (r *RemovePackageTagsPolicyActionTypedInput) GetTags() []string {
	if r == nil {
		return []string{}
	}
	return r.Tags
}
