// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 98a157f44f3e

package components

// RepositoryTypeEnum - * `PUBLIC` - Public
// * `PRIVATE` - Private
// * `OPEN_SOURCE` - Open-Source
type RepositoryTypeEnum string

const (
	RepositoryTypeEnumPublic     RepositoryTypeEnum = "PUBLIC"
	RepositoryTypeEnumPrivate    RepositoryTypeEnum = "PRIVATE"
	RepositoryTypeEnumOpenSource RepositoryTypeEnum = "OPEN_SOURCE"
)

func (e RepositoryTypeEnum) ToPointer() *RepositoryTypeEnum {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *RepositoryTypeEnum) IsExact() bool {
	if e != nil {
		switch *e {
		case "PUBLIC", "PRIVATE", "OPEN_SOURCE":
			return true
		}
	}
	return false
}
