// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ScanSummaryEnum - * `UNSAFE` - Unsafe
// * `UNKNOWN` - Unknown
// * `QUEUED` - Queued
// * `SAFE` - Safe
type ScanSummaryEnum string

const (
	ScanSummaryEnumUnsafe  ScanSummaryEnum = "UNSAFE"
	ScanSummaryEnumUnknown ScanSummaryEnum = "UNKNOWN"
	ScanSummaryEnumQueued  ScanSummaryEnum = "QUEUED"
	ScanSummaryEnumSafe    ScanSummaryEnum = "SAFE"
)

func (e ScanSummaryEnum) ToPointer() *ScanSummaryEnum {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ScanSummaryEnum) IsExact() bool {
	if e != nil {
		switch *e {
		case "UNSAFE", "UNKNOWN", "QUEUED", "SAFE":
			return true
		}
	}
	return false
}
