// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SecurityScanStatusEnum - * `AWAITING_SCAN` - Awaiting Security Scan
// * `SCANNING` - Security Scanning in Progress
// * `VULNERABLE` - Scan Detected Vulnerabilities
// * `NOT_VULNERABLE` - Scan Detected No Vulnerabilities
// * `DISABLED` - Security Scanning Disabled
// * `FAILED` - Security Scanning Failed
// * `SKIPPED` - Security Scanning Skipped
// * `UNSUPPORTED_PACKAGE` - Security Scanning Not Supported
// * `UNSUPPORTED_FORMAT` - Security Scanning Not Supported
type SecurityScanStatusEnum string

const (
	SecurityScanStatusEnumAwaitingScan       SecurityScanStatusEnum = "AWAITING_SCAN"
	SecurityScanStatusEnumScanning           SecurityScanStatusEnum = "SCANNING"
	SecurityScanStatusEnumVulnerable         SecurityScanStatusEnum = "VULNERABLE"
	SecurityScanStatusEnumNotVulnerable      SecurityScanStatusEnum = "NOT_VULNERABLE"
	SecurityScanStatusEnumDisabled           SecurityScanStatusEnum = "DISABLED"
	SecurityScanStatusEnumFailed             SecurityScanStatusEnum = "FAILED"
	SecurityScanStatusEnumSkipped            SecurityScanStatusEnum = "SKIPPED"
	SecurityScanStatusEnumUnsupportedPackage SecurityScanStatusEnum = "UNSUPPORTED_PACKAGE"
	SecurityScanStatusEnumUnsupportedFormat  SecurityScanStatusEnum = "UNSUPPORTED_FORMAT"
)

func (e SecurityScanStatusEnum) ToPointer() *SecurityScanStatusEnum {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SecurityScanStatusEnum) IsExact() bool {
	if e != nil {
		switch *e {
		case "AWAITING_SCAN", "SCANNING", "VULNERABLE", "NOT_VULNERABLE", "DISABLED", "FAILED", "SKIPPED", "UNSUPPORTED_PACKAGE", "UNSUPPORTED_FORMAT":
			return true
		}
	}
	return false
}
