// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	Apikey string `security:"scheme,type=apiKey,subtype=header,name=X-Api-Key"`
}

func (s *Security) GetApikey() string {
	if s == nil {
		return ""
	}
	return s.Apikey
}
