// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4efc21ee90a3

package components

// StatusEnum - * `UNSAFE` - Unsafe
// * `UNKNOWN` - Unknown
// * `QUEUED` - Queued
// * `SAFE` - Safe
type StatusEnum string

const (
	StatusEnumUnsafe  StatusEnum = "UNSAFE"
	StatusEnumUnknown StatusEnum = "UNKNOWN"
	StatusEnumQueued  StatusEnum = "QUEUED"
	StatusEnumSafe    StatusEnum = "SAFE"
)

func (e StatusEnum) ToPointer() *StatusEnum {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *StatusEnum) IsExact() bool {
	if e != nil {
		switch *e {
		case "UNSAFE", "UNKNOWN", "QUEUED", "SAFE":
			return true
		}
	}
	return false
}
