// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4770fdff33c9

package components

import (
	"mockserver/internal/sdk/utils"
)

type AddPackageTagsPolicyActionTypedInput struct {
	ActionType string `json:"action_type"`
	// The order in which this action occurs relative to other actions for the same policy.
	Precedence *int64   `json:"precedence,omitempty"`
	Tags       []string `json:"tags"`
}

func (a AddPackageTagsPolicyActionTypedInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AddPackageTagsPolicyActionTypedInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"action_type", "tags"}); err != nil {
		return err
	}
	return nil
}

func (o *AddPackageTagsPolicyActionTypedInput) GetActionType() string {
	if o == nil {
		return ""
	}
	return o.ActionType
}

func (o *AddPackageTagsPolicyActionTypedInput) GetPrecedence() *int64 {
	if o == nil {
		return nil
	}
	return o.Precedence
}

func (o *AddPackageTagsPolicyActionTypedInput) GetTags() []string {
	if o == nil {
		return []string{}
	}
	return o.Tags
}
