// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 07c48af17419

package components

// ArtifactMetadataWrite - Serializer for POST create and PATCH update on artifact metadata.
type ArtifactMetadataWrite struct {
	SlugPerm string `json:"slug_perm"`
	// The metadata payload as a JSON object.
	Content any `json:"content"`
	// The content type describing the structure of the metadata payload.
	ContentType string `json:"content_type"`
	// The identifier for the source of this metadata, for example 'upstream:npmjs'.
	SourceIdentity string `json:"source_identity"`
}

func (o *ArtifactMetadataWrite) GetSlugPerm() string {
	if o == nil {
		return ""
	}
	return o.SlugPerm
}

func (o *ArtifactMetadataWrite) GetContent() any {
	if o == nil {
		return nil
	}
	return o.Content
}

func (o *ArtifactMetadataWrite) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ArtifactMetadataWrite) GetSourceIdentity() string {
	if o == nil {
		return ""
	}
	return o.SourceIdentity
}
