// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 88769e0d693c

package components

import (
	"encoding/json"
	"fmt"
)

// AvailabilityEnum - * `UNAVAILABLE` - Unavailable
// * `PARTIAL` - Partially complete
// * `COMPLETE` - Complete
type AvailabilityEnum string

const (
	AvailabilityEnumUnavailable AvailabilityEnum = "UNAVAILABLE"
	AvailabilityEnumPartial     AvailabilityEnum = "PARTIAL"
	AvailabilityEnumComplete    AvailabilityEnum = "COMPLETE"
)

func (e AvailabilityEnum) ToPointer() *AvailabilityEnum {
	return &e
}
func (e *AvailabilityEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "UNAVAILABLE":
		fallthrough
	case "PARTIAL":
		fallthrough
	case "COMPLETE":
		*e = AvailabilityEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AvailabilityEnum: %v", v)
	}
}
