// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3a7644cf0df2

package components

import (
	"encoding/json"
	"fmt"
)

// ClassificationEnum - * `UNKNOWN` - Unknown
// * `INTRINSIC` - Intrinsic
// * `SECURITY` - Security
// * `PROVENANCE` - Provenance
// * `SBOM` - SBOM
// * `GENERIC` - Generic
type ClassificationEnum string

const (
	ClassificationEnumUnknown    ClassificationEnum = "UNKNOWN"
	ClassificationEnumIntrinsic  ClassificationEnum = "INTRINSIC"
	ClassificationEnumSecurity   ClassificationEnum = "SECURITY"
	ClassificationEnumProvenance ClassificationEnum = "PROVENANCE"
	ClassificationEnumSbom       ClassificationEnum = "SBOM"
	ClassificationEnumGeneric    ClassificationEnum = "GENERIC"
)

func (e ClassificationEnum) ToPointer() *ClassificationEnum {
	return &e
}
func (e *ClassificationEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "UNKNOWN":
		fallthrough
	case "INTRINSIC":
		fallthrough
	case "SECURITY":
		fallthrough
	case "PROVENANCE":
		fallthrough
	case "SBOM":
		fallthrough
	case "GENERIC":
		*e = ClassificationEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ClassificationEnum: %v", v)
	}
}
