// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a8b03ffd73a2

package components

import (
	"encoding/json"
	"fmt"
)

// LicenseSourceEnum - * `AUTOMATIC` - Automatically sourced
// * `MANUAL` - Manually sourced
type LicenseSourceEnum string

const (
	LicenseSourceEnumAutomatic LicenseSourceEnum = "AUTOMATIC"
	LicenseSourceEnumManual    LicenseSourceEnum = "MANUAL"
)

func (e LicenseSourceEnum) ToPointer() *LicenseSourceEnum {
	return &e
}
func (e *LicenseSourceEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "AUTOMATIC":
		fallthrough
	case "MANUAL":
		*e = LicenseSourceEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for LicenseSourceEnum: %v", v)
	}
}
