// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0427e20faa53

package components

import (
	"encoding/json"
	"fmt"
)

// LicenseOverrideEnum - * `NONE` - None
// * `IGNORED` - Ignored
// * `PURCHASED` - Purchased
type LicenseOverrideEnum string

const (
	LicenseOverrideEnumNone      LicenseOverrideEnum = "NONE"
	LicenseOverrideEnumIgnored   LicenseOverrideEnum = "IGNORED"
	LicenseOverrideEnumPurchased LicenseOverrideEnum = "PURCHASED"
)

func (e LicenseOverrideEnum) ToPointer() *LicenseOverrideEnum {
	return &e
}
func (e *LicenseOverrideEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NONE":
		fallthrough
	case "IGNORED":
		fallthrough
	case "PURCHASED":
		*e = LicenseOverrideEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for LicenseOverrideEnum: %v", v)
	}
}
