// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: bb4ed896cb47

package components

import (
	"encoding/json"
	"fmt"
)

// PackageTypeEnum - * `BINARY` - Binary
// * `SOURCE` - Source
// * `COMBINED` - Combined
// * `OTHER` - Other
type PackageTypeEnum string

const (
	PackageTypeEnumBinary   PackageTypeEnum = "BINARY"
	PackageTypeEnumSource   PackageTypeEnum = "SOURCE"
	PackageTypeEnumCombined PackageTypeEnum = "COMBINED"
	PackageTypeEnumOther    PackageTypeEnum = "OTHER"
)

func (e PackageTypeEnum) ToPointer() *PackageTypeEnum {
	return &e
}
func (e *PackageTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "BINARY":
		fallthrough
	case "SOURCE":
		fallthrough
	case "COMBINED":
		fallthrough
	case "OTHER":
		*e = PackageTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PackageTypeEnum: %v", v)
	}
}
