// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 19bb814426fc

package components

import (
	"encoding/json"
	"fmt"
)

// PackageStateEnum - * `AVAILABLE` - The package is available for download.
// * `DELETED` - The package is deleted.
// * `QUARANTINED` - The package is quarantined.
// * `HIDDEN` - The package is hidden.
type PackageStateEnum string

const (
	PackageStateEnumAvailable   PackageStateEnum = "AVAILABLE"
	PackageStateEnumDeleted     PackageStateEnum = "DELETED"
	PackageStateEnumQuarantined PackageStateEnum = "QUARANTINED"
	PackageStateEnumHidden      PackageStateEnum = "HIDDEN"
)

func (e PackageStateEnum) ToPointer() *PackageStateEnum {
	return &e
}
func (e *PackageStateEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "AVAILABLE":
		fallthrough
	case "DELETED":
		fallthrough
	case "QUARANTINED":
		fallthrough
	case "HIDDEN":
		*e = PackageStateEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PackageStateEnum: %v", v)
	}
}
