// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3cbb03ad971c

package components

import (
	"encoding/json"
	"fmt"
)

// PackageTagTypeEnum - * `INFO` - Info
// * `SOME_VERSION` - Some Version
// * `LATEST_VERSION` - Latest Version
// * `ANNOTATION` - Annotation
type PackageTagTypeEnum string

const (
	PackageTagTypeEnumInfo          PackageTagTypeEnum = "INFO"
	PackageTagTypeEnumSomeVersion   PackageTagTypeEnum = "SOME_VERSION"
	PackageTagTypeEnumLatestVersion PackageTagTypeEnum = "LATEST_VERSION"
	PackageTagTypeEnumAnnotation    PackageTagTypeEnum = "ANNOTATION"
)

func (e PackageTagTypeEnum) ToPointer() *PackageTagTypeEnum {
	return &e
}
func (e *PackageTagTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "INFO":
		fallthrough
	case "SOME_VERSION":
		fallthrough
	case "LATEST_VERSION":
		fallthrough
	case "ANNOTATION":
		*e = PackageTagTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PackageTagTypeEnum: %v", v)
	}
}
