// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0ed1689c4ed4

package components

import (
	"encoding/json"
	"fmt"
)

// PackageTagSourceTypeEnum - * `AUTOMATIC` - Automatic
// * `MANUAL` - Manual
type PackageTagSourceTypeEnum string

const (
	PackageTagSourceTypeEnumAutomatic PackageTagSourceTypeEnum = "AUTOMATIC"
	PackageTagSourceTypeEnumManual    PackageTagSourceTypeEnum = "MANUAL"
)

func (e PackageTagSourceTypeEnum) ToPointer() *PackageTagSourceTypeEnum {
	return &e
}
func (e *PackageTagSourceTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "AUTOMATIC":
		fallthrough
	case "MANUAL":
		*e = PackageTagSourceTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PackageTagSourceTypeEnum: %v", v)
	}
}
