// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a95a9c38e327

package components

type PaginatedPolicyActionList struct {
	Results []PolicyAction `json:"results"`
}

func (o *PaginatedPolicyActionList) GetResults() []PolicyAction {
	if o == nil {
		return []PolicyAction{}
	}
	return o.Results
}
