// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: fbdb7c5b7b66

package components

type PaginatedPolicyList struct {
	Results []Policy `json:"results"`
	// Total number of pages. Synthesised from the X-Pagination-Pagetotal
	// header by the SDK; not a field returned by the server.
	//
	Pagetotal *int64 `json:"pagetotal,omitempty"`
}

func (o *PaginatedPolicyList) GetResults() []Policy {
	if o == nil {
		return []Policy{}
	}
	return o.Results
}

func (o *PaginatedPolicyList) GetPagetotal() *int64 {
	if o == nil {
		return nil
	}
	return o.Pagetotal
}
