// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0980ebf4d144

package components

import (
	"mockserver/internal/sdk/utils"
)

type PatchedRemovePackageTagsPolicyActionTyped struct {
	ActionType *string `json:"action_type,omitempty"`
	// The order in which this action occurs relative to other actions for the same policy.
	Precedence *int64   `json:"precedence,omitempty"`
	Tags       []string `json:"tags,omitempty"`
}

func (p PatchedRemovePackageTagsPolicyActionTyped) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PatchedRemovePackageTagsPolicyActionTyped) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *PatchedRemovePackageTagsPolicyActionTyped) GetActionType() *string {
	if o == nil {
		return nil
	}
	return o.ActionType
}

func (o *PatchedRemovePackageTagsPolicyActionTyped) GetPrecedence() *int64 {
	if o == nil {
		return nil
	}
	return o.Precedence
}

func (o *PatchedRemovePackageTagsPolicyActionTyped) GetTags() []string {
	if o == nil {
		return nil
	}
	return o.Tags
}
