// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 45ed8f69b867

package components

import (
	"mockserver/internal/sdk/optionalnullable"
	"mockserver/internal/sdk/utils"
	"time"
)

// PolicyHuggingfaceFileReference - The files in a Huggingface model or dataset for policy purposes.
type PolicyHuggingfaceFileReference struct {
	CreatedAt     *time.Time `json:"created_at,omitempty"`
	FileExtension string     `json:"file_extension"`
	// The filename i.e 'model.safetensors'.
	Filename optionalnullable.OptionalNullable[string] `json:"filename,omitempty"`
	// The content-addressed object ID (OID) of this file, typically a SHA256 hash.
	Oid string `json:"oid"`
	// The calculated storage size for the file.
	Size int64 `json:"size"`
	// The full path of the file within the package i.e 'models/model.safetensors'.
	Path string `json:"path"`
}

func (p PolicyHuggingfaceFileReference) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PolicyHuggingfaceFileReference) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"file_extension", "oid", "size", "path"}); err != nil {
		return err
	}
	return nil
}

func (o *PolicyHuggingfaceFileReference) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *PolicyHuggingfaceFileReference) GetFileExtension() string {
	if o == nil {
		return ""
	}
	return o.FileExtension
}

func (o *PolicyHuggingfaceFileReference) GetFilename() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Filename
}

func (o *PolicyHuggingfaceFileReference) GetOid() string {
	if o == nil {
		return ""
	}
	return o.Oid
}

func (o *PolicyHuggingfaceFileReference) GetSize() int64 {
	if o == nil {
		return 0
	}
	return o.Size
}

func (o *PolicyHuggingfaceFileReference) GetPath() string {
	if o == nil {
		return ""
	}
	return o.Path
}
