// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 2a5ce7bd102d

package components

// PolicyAdvisorySource - The source of the advisory.
type PolicyAdvisorySource struct {
	// The advisory source name.
	Name string `json:"name"`
	// The advisory source URL.
	URL string `json:"url"`
}

func (o *PolicyAdvisorySource) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *PolicyAdvisorySource) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}
