// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ae2a9986eefc

package components

import (
	"encoding/json"
	"fmt"
)

// PolicyHuggingfaceSecuritySourceEnum - * `HUGGINGFACE_HUB` - Hugging Face Hub
type PolicyHuggingfaceSecuritySourceEnum string

const (
	PolicyHuggingfaceSecuritySourceEnumHuggingfaceHub PolicyHuggingfaceSecuritySourceEnum = "HUGGINGFACE_HUB"
)

func (e PolicyHuggingfaceSecuritySourceEnum) ToPointer() *PolicyHuggingfaceSecuritySourceEnum {
	return &e
}
func (e *PolicyHuggingfaceSecuritySourceEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "HUGGINGFACE_HUB":
		*e = PolicyHuggingfaceSecuritySourceEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PolicyHuggingfaceSecuritySourceEnum: %v", v)
	}
}
