// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c97acfcf7f71

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"mockserver/internal/sdk/utils"
)

type PolicyPolymorphicPackageType string

const (
	PolicyPolymorphicPackageTypePackage            PolicyPolymorphicPackageType = "Package"
	PolicyPolymorphicPackageTypeHuggingfacePackage PolicyPolymorphicPackageType = "HuggingfacePackage"
)

type PolicyPolymorphicPackage struct {
	PolicyPackageTyped            *PolicyPackageTyped            `queryParam:"inline"`
	PolicyHuggingfacePackageTyped *PolicyHuggingfacePackageTyped `queryParam:"inline"`

	Type PolicyPolymorphicPackageType
}

func CreatePolicyPolymorphicPackagePackage(packageT PolicyPackageTyped) PolicyPolymorphicPackage {
	typ := PolicyPolymorphicPackageTypePackage

	typStr := string(typ)
	packageT.Format = typStr

	return PolicyPolymorphicPackage{
		PolicyPackageTyped: &packageT,
		Type:               typ,
	}
}

func CreatePolicyPolymorphicPackageHuggingfacePackage(huggingfacePackage PolicyHuggingfacePackageTyped) PolicyPolymorphicPackage {
	typ := PolicyPolymorphicPackageTypeHuggingfacePackage

	typStr := string(typ)
	huggingfacePackage.Format = typStr

	return PolicyPolymorphicPackage{
		PolicyHuggingfacePackageTyped: &huggingfacePackage,
		Type:                          typ,
	}
}

func (u *PolicyPolymorphicPackage) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Format string `json:"format"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Format {
	case "Package":
		policyPackageTyped := new(PolicyPackageTyped)
		if err := utils.UnmarshalJSON(data, &policyPackageTyped, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Format == Package) type PolicyPackageTyped within PolicyPolymorphicPackage: %w", string(data), err)
		}

		u.PolicyPackageTyped = policyPackageTyped
		u.Type = PolicyPolymorphicPackageTypePackage
		return nil
	case "HuggingfacePackage":
		policyHuggingfacePackageTyped := new(PolicyHuggingfacePackageTyped)
		if err := utils.UnmarshalJSON(data, &policyHuggingfacePackageTyped, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Format == HuggingfacePackage) type PolicyHuggingfacePackageTyped within PolicyPolymorphicPackage: %w", string(data), err)
		}

		u.PolicyHuggingfacePackageTyped = policyHuggingfacePackageTyped
		u.Type = PolicyPolymorphicPackageTypeHuggingfacePackage
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for PolicyPolymorphicPackage", string(data))
}

func (u PolicyPolymorphicPackage) MarshalJSON() ([]byte, error) {
	if u.PolicyPackageTyped != nil {
		return utils.MarshalJSON(u.PolicyPackageTyped, "", true)
	}

	if u.PolicyHuggingfacePackageTyped != nil {
		return utils.MarshalJSON(u.PolicyHuggingfacePackageTyped, "", true)
	}

	return nil, errors.New("could not marshal union type PolicyPolymorphicPackage: all fields are null")
}
