// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 61136cca7685

package components

import (
	"mockserver/internal/sdk/utils"
	"time"
)

// PolicyRepository - The details of the package repository for policy purposes.
type PolicyRepository struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// A description of the repository's purpose/contents.
	Description *string                    `json:"description,omitempty"`
	EcdsaKeys   []PolicyRepositoryEcdsaKey `json:"ecdsa_keys"`
	GpgKeys     []PolicyRepositoryGpgKey   `json:"gpg_keys"`
	// A descriptive name for the repository.
	Name              string  `json:"name"`
	OpenSourceLicense *string `json:"open_source_license"`
	// * `PUBLIC` - Public
	// * `PRIVATE` - Private
	// * `OPEN_SOURCE` - Open-Source
	RepositoryType RepositoryTypeEnum `json:"repository_type"`
	// The slug identifies the repository in URIs.
	Slug *string `json:"slug,omitempty"`
	// The slug_perm immutably identifies the repository. It will never change once a repository has been created.
	SlugPerm      *string `json:"slug_perm,omitempty"`
	StorageRegion string  `json:"storage_region"`
}

func (p PolicyRepository) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PolicyRepository) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"ecdsa_keys", "gpg_keys", "name", "open_source_license", "repository_type", "storage_region"}); err != nil {
		return err
	}
	return nil
}

func (o *PolicyRepository) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *PolicyRepository) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *PolicyRepository) GetEcdsaKeys() []PolicyRepositoryEcdsaKey {
	if o == nil {
		return []PolicyRepositoryEcdsaKey{}
	}
	return o.EcdsaKeys
}

func (o *PolicyRepository) GetGpgKeys() []PolicyRepositoryGpgKey {
	if o == nil {
		return []PolicyRepositoryGpgKey{}
	}
	return o.GpgKeys
}

func (o *PolicyRepository) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *PolicyRepository) GetOpenSourceLicense() *string {
	if o == nil {
		return nil
	}
	return o.OpenSourceLicense
}

func (o *PolicyRepository) GetRepositoryType() RepositoryTypeEnum {
	if o == nil {
		return RepositoryTypeEnum("")
	}
	return o.RepositoryType
}

func (o *PolicyRepository) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

func (o *PolicyRepository) GetSlugPerm() *string {
	if o == nil {
		return nil
	}
	return o.SlugPerm
}

func (o *PolicyRepository) GetStorageRegion() string {
	if o == nil {
		return ""
	}
	return o.StorageRegion
}
