// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3b43446921db

package components

import (
	"mockserver/internal/sdk/optionalnullable"
)

// Identity - Read-only serializer for Artifact model in policy input context.
type Identity struct {
	Purl           string  `json:"purl"`
	Namespace      string  `json:"namespace"`
	Name           string  `json:"name"`
	Version        *string `json:"version"`
	Qualifiers     any     `json:"qualifiers"`
	Subpath        *string `json:"subpath"`
	Format         string  `json:"format"`
	ChecksumMd5    *string `json:"checksum_md5"`
	ChecksumSha1   *string `json:"checksum_sha1"`
	ChecksumSha256 *string `json:"checksum_sha256"`
	ChecksumSha512 *string `json:"checksum_sha512"`
}

func (o *Identity) GetPurl() string {
	if o == nil {
		return ""
	}
	return o.Purl
}

func (o *Identity) GetNamespace() string {
	if o == nil {
		return ""
	}
	return o.Namespace
}

func (o *Identity) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Identity) GetVersion() *string {
	if o == nil {
		return nil
	}
	return o.Version
}

func (o *Identity) GetQualifiers() any {
	if o == nil {
		return nil
	}
	return o.Qualifiers
}

func (o *Identity) GetSubpath() *string {
	if o == nil {
		return nil
	}
	return o.Subpath
}

func (o *Identity) GetFormat() string {
	if o == nil {
		return ""
	}
	return o.Format
}

func (o *Identity) GetChecksumMd5() *string {
	if o == nil {
		return nil
	}
	return o.ChecksumMd5
}

func (o *Identity) GetChecksumSha1() *string {
	if o == nil {
		return nil
	}
	return o.ChecksumSha1
}

func (o *Identity) GetChecksumSha256() *string {
	if o == nil {
		return nil
	}
	return o.ChecksumSha256
}

func (o *Identity) GetChecksumSha512() *string {
	if o == nil {
		return nil
	}
	return o.ChecksumSha512
}

type ModelSecurity struct {
	// Whether security data is available for this Huggingface package.
	//
	// * `UNAVAILABLE` - Unavailable
	// * `PARTIAL` - Partially complete
	// * `COMPLETE` - Complete
	Availability AvailabilityEnum `json:"availability"`
	// If data is available, the overall summary of the scan results. Result precedence from highest to lowest is: UNSAFE > UNKNOWN > QUEUED > SAFE.
	//
	// * `UNSAFE` - Unsafe
	// * `UNKNOWN` - Unknown
	// * `QUEUED` - Queued
	// * `SAFE` - Safe
	ScanSummary *ScanSummaryEnum `json:"scan_summary,omitempty"`
	// The scan details for any file that is NOT reported as SAFE will be included in this list.
	ScanDetails []PolicyHuggingfaceHubScans `json:"scan_details,omitempty"`
	// * `HUGGINGFACE_HUB` - Hugging Face Hub
	Source *PolicyHuggingfaceSecuritySourceEnum `json:"source,omitempty"`
}

func (o *ModelSecurity) GetAvailability() AvailabilityEnum {
	if o == nil {
		return AvailabilityEnum("")
	}
	return o.Availability
}

func (o *ModelSecurity) GetScanSummary() *ScanSummaryEnum {
	if o == nil {
		return nil
	}
	return o.ScanSummary
}

func (o *ModelSecurity) GetScanDetails() []PolicyHuggingfaceHubScans {
	if o == nil {
		return nil
	}
	return o.ScanDetails
}

func (o *ModelSecurity) GetSource() *PolicyHuggingfaceSecuritySourceEnum {
	if o == nil {
		return nil
	}
	return o.Source
}

// PolicyInputV0 - Serializer for V0 policy input.
type PolicyInputV0 struct {
	Package PolicyPolymorphicPackage `json:"package"`
	// The details of the package repository for policy purposes.
	Repository PolicyRepository `json:"repository"`
	// Representation of a Workspace used in Policy input.
	Workspace       PolicyWorkspace                                  `json:"workspace"`
	Identity        optionalnullable.OptionalNullable[Identity]      `json:"identity,omitempty"`
	Metadata        []PolicyArtifactMetadata                         `json:"metadata,omitempty"`
	Upstream        optionalnullable.OptionalNullable[any]           `json:"upstream,omitempty"`
	Osv             []PolicyOSVVulnerability                         `json:"osv,omitempty"`
	SecurityScan    optionalnullable.OptionalNullable[any]           `json:"security_scan,omitempty"`
	Vulnerabilities []PolicyAdvisory                                 `json:"vulnerabilities,omitempty"`
	ModelSecurity   optionalnullable.OptionalNullable[ModelSecurity] `json:"model_security,omitempty"`
	// Raw SBOM data in CycloneDX format, generated by Cloudsmith. Only available for supported Docker/OCI images.
	Sbom optionalnullable.OptionalNullable[any] `json:"sbom,omitempty"`
}

func (o *PolicyInputV0) GetPackage() PolicyPolymorphicPackage {
	if o == nil {
		return PolicyPolymorphicPackage{}
	}
	return o.Package
}

func (o *PolicyInputV0) GetPackagePackage() *PolicyPackageTyped {
	return o.GetPackage().PolicyPackageTyped
}

func (o *PolicyInputV0) GetPackageHuggingfacePackage() *PolicyHuggingfacePackageTyped {
	return o.GetPackage().PolicyHuggingfacePackageTyped
}

func (o *PolicyInputV0) GetRepository() PolicyRepository {
	if o == nil {
		return PolicyRepository{}
	}
	return o.Repository
}

func (o *PolicyInputV0) GetWorkspace() PolicyWorkspace {
	if o == nil {
		return PolicyWorkspace{}
	}
	return o.Workspace
}

func (o *PolicyInputV0) GetIdentity() optionalnullable.OptionalNullable[Identity] {
	if o == nil {
		return nil
	}
	return o.Identity
}

func (o *PolicyInputV0) GetMetadata() []PolicyArtifactMetadata {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *PolicyInputV0) GetUpstream() optionalnullable.OptionalNullable[any] {
	if o == nil {
		return nil
	}
	return o.Upstream
}

func (o *PolicyInputV0) GetOsv() []PolicyOSVVulnerability {
	if o == nil {
		return nil
	}
	return o.Osv
}

func (o *PolicyInputV0) GetSecurityScan() optionalnullable.OptionalNullable[any] {
	if o == nil {
		return nil
	}
	return o.SecurityScan
}

func (o *PolicyInputV0) GetVulnerabilities() []PolicyAdvisory {
	if o == nil {
		return nil
	}
	return o.Vulnerabilities
}

func (o *PolicyInputV0) GetModelSecurity() optionalnullable.OptionalNullable[ModelSecurity] {
	if o == nil {
		return nil
	}
	return o.ModelSecurity
}

func (o *PolicyInputV0) GetSbom() optionalnullable.OptionalNullable[any] {
	if o == nil {
		return nil
	}
	return o.Sbom
}
