// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d1cfcf1018a6

package components

// PolicyAdvisoryCvss - A CVSS score and vector string.
type PolicyAdvisoryCvss struct {
	// The CVSS V2 score.
	V2Score *float64 `json:"V2Score"`
	// The CVSS V2 vector string.
	V2Vector *string `json:"V2Vector"`
	// The CVSS V3 score.
	V3Score *float64 `json:"V3Score"`
	// The CVSS V3 vector string.
	V3Vector *string `json:"V3Vector"`
}

func (o *PolicyAdvisoryCvss) GetV2Score() *float64 {
	if o == nil {
		return nil
	}
	return o.V2Score
}

func (o *PolicyAdvisoryCvss) GetV2Vector() *string {
	if o == nil {
		return nil
	}
	return o.V2Vector
}

func (o *PolicyAdvisoryCvss) GetV3Score() *float64 {
	if o == nil {
		return nil
	}
	return o.V3Score
}

func (o *PolicyAdvisoryCvss) GetV3Vector() *string {
	if o == nil {
		return nil
	}
	return o.V3Vector
}
