// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b2d8349fba32

package components

import (
	"mockserver/internal/sdk/optionalnullable"
)

type PolicyInput1 struct {
	// The description of the Policy.
	Description optionalnullable.OptionalNullable[string] `json:"description,omitempty"`
	// The name of the Policy.
	Name string `json:"name"`
	// The rego code which constitutes the Policy logic.
	Rego string `json:"rego"`
	// If true, the policy is enabled.
	Enabled *bool `json:"enabled,omitempty"`
	// If true and the policy matches, no further policies are evaluated.
	IsTerminal *bool `json:"is_terminal,omitempty"`
	// The order in which this policy is evaluated relative to other policies.
	Precedence *int64 `json:"precedence,omitempty"`
}

func (o *PolicyInput1) GetDescription() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *PolicyInput1) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *PolicyInput1) GetRego() string {
	if o == nil {
		return ""
	}
	return o.Rego
}

func (o *PolicyInput1) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

func (o *PolicyInput1) GetIsTerminal() *bool {
	if o == nil {
		return nil
	}
	return o.IsTerminal
}

func (o *PolicyInput1) GetPrecedence() *int64 {
	if o == nil {
		return nil
	}
	return o.Precedence
}
