// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f65b656b9310

package components

import (
	"mockserver/internal/sdk/optionalnullable"
	"mockserver/internal/sdk/utils"
)

// PolicyArchitecture - The package architecture for policy purposes.
type PolicyArchitecture struct {
	Description optionalnullable.OptionalNullable[string] `json:"description,omitempty"`
	Name        string                                    `json:"name"`
}

func (p PolicyArchitecture) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PolicyArchitecture) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"name"}); err != nil {
		return err
	}
	return nil
}

func (o *PolicyArchitecture) GetDescription() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *PolicyArchitecture) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
