// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3106c70e2247

package components

import (
	"mockserver/internal/sdk/optionalnullable"
	"mockserver/internal/sdk/utils"
)

// PolicyHuggingfaceEvalResult - The evaluation results of model-card of a Huggingface package.
//
// A flattened version of the evaluation results from the model card.
type PolicyHuggingfaceEvalResult struct {
	// The task identifier, e.g. image-classification.
	TaskType string `json:"task_type"`
	// The dataset identifier, e.g.g common_voice.
	DatasetType string `json:"dataset_type"`
	// A pretty name for the dataset, e.g. Common Voice.
	DatasetName string `json:"dataset_name"`
	// The metric identifier, e.g. accuracy.
	MetricType string `json:"metric_type"`
	// The value fo the metric, e.g. 0.95.
	MetricValue string `json:"metric_value"`
	// The pretty name of the task, e.g. Speech Recognition.
	TaskName optionalnullable.OptionalNullable[string] `json:"task_name,omitempty"`
	// The name of the dataset configuration used in `load_dataset()`.
	DatasetConfig optionalnullable.OptionalNullable[string] `json:"dataset_config,omitempty"`
	// The split used in the `load_dataset()`.
	DatasetSplit optionalnullable.OptionalNullable[string] `json:"dataset_split,omitempty"`
	// The revision (aka git sha) of the dataset used in `load_dataset()`.
	DatasetRevision optionalnullable.OptionalNullable[string] `json:"dataset_revision,omitempty"`
	// The arguments passed during `Metric.compute()`.
	DatasetArgs optionalnullable.OptionalNullable[map[string]any] `json:"dataset_args,omitempty"`
	// A pretty name for the metric, e.g. Accuracy.
	MetricName optionalnullable.OptionalNullable[string] `json:"metric_name,omitempty"`
	// The name of metric used in `load_metric()`.
	MetricConfig optionalnullable.OptionalNullable[string] `json:"metric_config,omitempty"`
	// The arguments passed during `Metric.compute()`.
	MetricArgs optionalnullable.OptionalNullable[map[string]any] `json:"metric_args,omitempty"`
	// Indicates if the metrics originate from Hugging Face's evaluation serivce.
	Verified optionalnullable.OptionalNullable[bool] `json:"verified,omitempty"`
	// A JWT token used to verify the metrics origin.
	VerifyToken optionalnullable.OptionalNullable[string] `json:"verify_token,omitempty"`
	// The name of the source of the evaluation result, e.g. Open LLM Leaderboard.
	SourceName optionalnullable.OptionalNullable[string] `json:"source_name,omitempty"`
	// The url of the source of the evalatuation result.
	SourceURL optionalnullable.OptionalNullable[string] `json:"source_url,omitempty"`
}

func (p PolicyHuggingfaceEvalResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PolicyHuggingfaceEvalResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"task_type", "dataset_type", "dataset_name", "metric_type", "metric_value"}); err != nil {
		return err
	}
	return nil
}

func (o *PolicyHuggingfaceEvalResult) GetTaskType() string {
	if o == nil {
		return ""
	}
	return o.TaskType
}

func (o *PolicyHuggingfaceEvalResult) GetDatasetType() string {
	if o == nil {
		return ""
	}
	return o.DatasetType
}

func (o *PolicyHuggingfaceEvalResult) GetDatasetName() string {
	if o == nil {
		return ""
	}
	return o.DatasetName
}

func (o *PolicyHuggingfaceEvalResult) GetMetricType() string {
	if o == nil {
		return ""
	}
	return o.MetricType
}

func (o *PolicyHuggingfaceEvalResult) GetMetricValue() string {
	if o == nil {
		return ""
	}
	return o.MetricValue
}

func (o *PolicyHuggingfaceEvalResult) GetTaskName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.TaskName
}

func (o *PolicyHuggingfaceEvalResult) GetDatasetConfig() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.DatasetConfig
}

func (o *PolicyHuggingfaceEvalResult) GetDatasetSplit() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.DatasetSplit
}

func (o *PolicyHuggingfaceEvalResult) GetDatasetRevision() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.DatasetRevision
}

func (o *PolicyHuggingfaceEvalResult) GetDatasetArgs() optionalnullable.OptionalNullable[map[string]any] {
	if o == nil {
		return nil
	}
	return o.DatasetArgs
}

func (o *PolicyHuggingfaceEvalResult) GetMetricName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.MetricName
}

func (o *PolicyHuggingfaceEvalResult) GetMetricConfig() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.MetricConfig
}

func (o *PolicyHuggingfaceEvalResult) GetMetricArgs() optionalnullable.OptionalNullable[map[string]any] {
	if o == nil {
		return nil
	}
	return o.MetricArgs
}

func (o *PolicyHuggingfaceEvalResult) GetVerified() optionalnullable.OptionalNullable[bool] {
	if o == nil {
		return nil
	}
	return o.Verified
}

func (o *PolicyHuggingfaceEvalResult) GetVerifyToken() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.VerifyToken
}

func (o *PolicyHuggingfaceEvalResult) GetSourceName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.SourceName
}

func (o *PolicyHuggingfaceEvalResult) GetSourceURL() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.SourceURL
}
