// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 2394ca444c94

package components

import (
	"mockserver/internal/sdk/optionalnullable"
	"mockserver/internal/sdk/utils"
)

// PolicyPackageFile - The package files for policy purposes.
type PolicyPackageFile struct {
	ChecksumMd5    optionalnullable.OptionalNullable[string] `json:"checksum_md5,omitempty"`
	ChecksumSha1   optionalnullable.OptionalNullable[string] `json:"checksum_sha1,omitempty"`
	ChecksumSha256 optionalnullable.OptionalNullable[string] `json:"checksum_sha256,omitempty"`
	ChecksumSha512 optionalnullable.OptionalNullable[string] `json:"checksum_sha512,omitempty"`
	Filename       string                                    `json:"filename"`
	IsPrimary      string                                    `json:"is_primary"`
	// The calculated size of the file.
	Size     *int64  `json:"size,omitempty"`
	SlugPerm *string `json:"slug_perm,omitempty"`
	// Freeform descriptor that describes what the file is.
	Tag optionalnullable.OptionalNullable[string] `json:"tag,omitempty"`
}

func (p PolicyPackageFile) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PolicyPackageFile) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"filename", "is_primary"}); err != nil {
		return err
	}
	return nil
}

func (o *PolicyPackageFile) GetChecksumMd5() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.ChecksumMd5
}

func (o *PolicyPackageFile) GetChecksumSha1() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.ChecksumSha1
}

func (o *PolicyPackageFile) GetChecksumSha256() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.ChecksumSha256
}

func (o *PolicyPackageFile) GetChecksumSha512() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.ChecksumSha512
}

func (o *PolicyPackageFile) GetFilename() string {
	if o == nil {
		return ""
	}
	return o.Filename
}

func (o *PolicyPackageFile) GetIsPrimary() string {
	if o == nil {
		return ""
	}
	return o.IsPrimary
}

func (o *PolicyPackageFile) GetSize() *int64 {
	if o == nil {
		return nil
	}
	return o.Size
}

func (o *PolicyPackageFile) GetSlugPerm() *string {
	if o == nil {
		return nil
	}
	return o.SlugPerm
}

func (o *PolicyPackageFile) GetTag() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Tag
}
