// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 40148f8e84b0

package components

import (
	"mockserver/internal/sdk/utils"
)

// PolicyDistributionVersion - The version of  distribution of the package for policy purposes.
type PolicyDistributionVersion struct {
	// The textual name for this version.
	Name *string `json:"name,omitempty"`
	Slug string  `json:"slug"`
}

func (p PolicyDistributionVersion) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PolicyDistributionVersion) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"slug"}); err != nil {
		return err
	}
	return nil
}

func (o *PolicyDistributionVersion) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *PolicyDistributionVersion) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}
