// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c2e6510a87f0

package components

import (
	"mockserver/internal/sdk/optionalnullable"
	"mockserver/internal/sdk/utils"
	"time"
)

type Policy struct {
	// The date and time the policy was created.
	CreatedAt time.Time `json:"created_at"`
	// The description of the Policy.
	Description optionalnullable.OptionalNullable[string] `json:"description,omitempty"`
	// The name of the Policy.
	Name string `json:"name"`
	// The rego code which constitutes the Policy logic.
	Rego string `json:"rego"`
	// If true, the policy is enabled.
	Enabled *bool `json:"enabled,omitempty"`
	// If true and the policy matches, no further policies are evaluated.
	IsTerminal *bool `json:"is_terminal,omitempty"`
	// Whether this policy is read-only (only specific variables can be updated).
	ReadOnly bool `json:"read_only"`
	// The Policy identifier.
	SlugPerm string `json:"slug_perm"`
	// The date and time the policy was updated.
	UpdatedAt time.Time `json:"updated_at"`
	// The version of the rego code.
	Version int64 `json:"version"`
	// The order in which this policy is evaluated relative to other policies.
	Precedence *int64 `json:"precedence,omitempty"`
}

func (p Policy) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Policy) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"created_at", "name", "rego", "read_only", "slug_perm", "updated_at", "version"}); err != nil {
		return err
	}
	return nil
}

func (o *Policy) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *Policy) GetDescription() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *Policy) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Policy) GetRego() string {
	if o == nil {
		return ""
	}
	return o.Rego
}

func (o *Policy) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

func (o *Policy) GetIsTerminal() *bool {
	if o == nil {
		return nil
	}
	return o.IsTerminal
}

func (o *Policy) GetReadOnly() bool {
	if o == nil {
		return false
	}
	return o.ReadOnly
}

func (o *Policy) GetSlugPerm() string {
	if o == nil {
		return ""
	}
	return o.SlugPerm
}

func (o *Policy) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}

func (o *Policy) GetVersion() int64 {
	if o == nil {
		return 0
	}
	return o.Version
}

func (o *Policy) GetPrecedence() *int64 {
	if o == nil {
		return nil
	}
	return o.Precedence
}
