// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b68581d7104d

package components

import (
	"mockserver/internal/sdk/optionalnullable"
	"mockserver/internal/sdk/utils"
)

// PolicyUploader - The package uploader for policy puposes.
type PolicyUploader struct {
	// Your email address that we use to contact you. This is only visible to you.
	Email     optionalnullable.OptionalNullable[string] `json:"email,omitempty"`
	FirstName string                                    `json:"first_name"`
	LastName  string                                    `json:"last_name"`
	Slug      string                                    `json:"slug"`
	SlugPerm  string                                    `json:"slug_perm"`
}

func (p PolicyUploader) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PolicyUploader) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"first_name", "last_name", "slug", "slug_perm"}); err != nil {
		return err
	}
	return nil
}

func (o *PolicyUploader) GetEmail() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *PolicyUploader) GetFirstName() string {
	if o == nil {
		return ""
	}
	return o.FirstName
}

func (o *PolicyUploader) GetLastName() string {
	if o == nil {
		return ""
	}
	return o.LastName
}

func (o *PolicyUploader) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *PolicyUploader) GetSlugPerm() string {
	if o == nil {
		return ""
	}
	return o.SlugPerm
}
