// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 40c6c2f142a5

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"mockserver/internal/sdk/utils"
)

type PolicyActionType string

const (
	PolicyActionTypeSetPackageState   PolicyActionType = "SetPackageState"
	PolicyActionTypeAddPackageTags    PolicyActionType = "AddPackageTags"
	PolicyActionTypeRemovePackageTags PolicyActionType = "RemovePackageTags"
)

type PolicyAction struct {
	SetPackageStatePolicyActionTyped   *SetPackageStatePolicyActionTyped   `queryParam:"inline"`
	AddPackageTagsPolicyActionTyped    *AddPackageTagsPolicyActionTyped    `queryParam:"inline"`
	RemovePackageTagsPolicyActionTyped *RemovePackageTagsPolicyActionTyped `queryParam:"inline"`

	Type PolicyActionType
}

func CreatePolicyActionSetPackageState(setPackageState SetPackageStatePolicyActionTyped) PolicyAction {
	typ := PolicyActionTypeSetPackageState

	typStr := string(typ)
	setPackageState.ActionType = typStr

	return PolicyAction{
		SetPackageStatePolicyActionTyped: &setPackageState,
		Type:                             typ,
	}
}

func CreatePolicyActionAddPackageTags(addPackageTags AddPackageTagsPolicyActionTyped) PolicyAction {
	typ := PolicyActionTypeAddPackageTags

	typStr := string(typ)
	addPackageTags.ActionType = typStr

	return PolicyAction{
		AddPackageTagsPolicyActionTyped: &addPackageTags,
		Type:                            typ,
	}
}

func CreatePolicyActionRemovePackageTags(removePackageTags RemovePackageTagsPolicyActionTyped) PolicyAction {
	typ := PolicyActionTypeRemovePackageTags

	typStr := string(typ)
	removePackageTags.ActionType = typStr

	return PolicyAction{
		RemovePackageTagsPolicyActionTyped: &removePackageTags,
		Type:                               typ,
	}
}

func (u *PolicyAction) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		ActionType string `json:"action_type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.ActionType {
	case "SetPackageState":
		setPackageStatePolicyActionTyped := new(SetPackageStatePolicyActionTyped)
		if err := utils.UnmarshalJSON(data, &setPackageStatePolicyActionTyped, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ActionType == SetPackageState) type SetPackageStatePolicyActionTyped within PolicyAction: %w", string(data), err)
		}

		u.SetPackageStatePolicyActionTyped = setPackageStatePolicyActionTyped
		u.Type = PolicyActionTypeSetPackageState
		return nil
	case "AddPackageTags":
		addPackageTagsPolicyActionTyped := new(AddPackageTagsPolicyActionTyped)
		if err := utils.UnmarshalJSON(data, &addPackageTagsPolicyActionTyped, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ActionType == AddPackageTags) type AddPackageTagsPolicyActionTyped within PolicyAction: %w", string(data), err)
		}

		u.AddPackageTagsPolicyActionTyped = addPackageTagsPolicyActionTyped
		u.Type = PolicyActionTypeAddPackageTags
		return nil
	case "RemovePackageTags":
		removePackageTagsPolicyActionTyped := new(RemovePackageTagsPolicyActionTyped)
		if err := utils.UnmarshalJSON(data, &removePackageTagsPolicyActionTyped, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ActionType == RemovePackageTags) type RemovePackageTagsPolicyActionTyped within PolicyAction: %w", string(data), err)
		}

		u.RemovePackageTagsPolicyActionTyped = removePackageTagsPolicyActionTyped
		u.Type = PolicyActionTypeRemovePackageTags
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for PolicyAction", string(data))
}

func (u PolicyAction) MarshalJSON() ([]byte, error) {
	if u.SetPackageStatePolicyActionTyped != nil {
		return utils.MarshalJSON(u.SetPackageStatePolicyActionTyped, "", true)
	}

	if u.AddPackageTagsPolicyActionTyped != nil {
		return utils.MarshalJSON(u.AddPackageTagsPolicyActionTyped, "", true)
	}

	if u.RemovePackageTagsPolicyActionTyped != nil {
		return utils.MarshalJSON(u.RemovePackageTagsPolicyActionTyped, "", true)
	}

	return nil, errors.New("could not marshal union type PolicyAction: all fields are null")
}
