// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: aed13521b962

package components

import (
	"errors"
	"fmt"
	"mockserver/internal/sdk/optionalnullable"
	"mockserver/internal/sdk/utils"
	"time"
)

// PolicyHuggingfaceDatasetCardTyped - The dataset-card of a Huggingface package.
//
// The dataset-card is metadata specified inside the README.md file of a Huggingface model.
type PolicyHuggingfaceDatasetCardTyped struct {
	Type string `json:"type"`
	// How the annotations for the dataset were created. Options are: 'found', 'crowdsourced', 'expert-generated', 'machine-generated', 'no-annotation', 'other'.
	AnnotationsCreators optionalnullable.OptionalNullable[[]string] `json:"annotations_creators,omitempty"`
	//  A list of the available dataset configs for the dataset.
	ConfigNames optionalnullable.OptionalNullable[[]string] `json:"config_names,omitempty"`
	// Any additional metadata fields present in the datasetcard that is not one of the well-known fields.
	Extras optionalnullable.OptionalNullable[map[string]any] `json:"extras,omitempty"`
	// List of languages of the dataset's data or metadata.
	Language optionalnullable.OptionalNullable[[]string] `json:"language,omitempty"`
	// How the text-based data in the dataset was created. Options are: 'found', 'crowdsourced', 'expert-generated', 'machine-generated', 'other'.
	LanguageCreators optionalnullable.OptionalNullable[[]string] `json:"language_creators,omitempty"`
	// The license(s) identifier(s) of this dataset, e.g. apache-2.0.
	License optionalnullable.OptionalNullable[[]string] `json:"license,omitempty"`
	// Whether the dataset is multilingual. Options are: 'monolingual', 'multilingual', 'translation', 'other'.
	Multilinguality optionalnullable.OptionalNullable[[]string] `json:"multilinguality,omitempty"`
	// The ID of the dataset on PapersWithCode.
	PaperswithcodeID optionalnullable.OptionalNullable[string] `json:"paperswithcode_id,omitempty"`
	// A human-readable name for the dataset, e.g. 'Cities and Buildings'.
	PrettyName optionalnullable.OptionalNullable[string] `json:"pretty_name,omitempty"`
	// The number of examples in the dataset. Options are: 'n<1K', '1K<n<10K', '10K<n<100K', '100K<n<1M', '1M<n<10M', '10M<n<100M', '100M<n<1B', '1B<n<10B', '10B<n<100B', '100B<n<1T', 'n>1T', and 'other'.
	SizeCategories optionalnullable.OptionalNullable[[]string] `json:"size_categories,omitempty"`
	// Indicates whether the dataset is an original dataset or extended from another existing dataset. Options are: 'original' and 'extended'.
	SourceDatasets optionalnullable.OptionalNullable[[]string] `json:"source_datasets,omitempty"`
	// The categories of tasks that the dataset supports.
	TaskCategories optionalnullable.OptionalNullable[[]string] `json:"task_categories,omitempty"`
	// The specific tasks that the dataset supports
	TaskIds optionalnullable.OptionalNullable[[]string] `json:"task_ids,omitempty"`
	// JSON that describes the necessary spec for doing evaluation on the Hub.
	TrainEvalIndex optionalnullable.OptionalNullable[any] `json:"train_eval_index,omitempty"`
}

func (p PolicyHuggingfaceDatasetCardTyped) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PolicyHuggingfaceDatasetCardTyped) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (o *PolicyHuggingfaceDatasetCardTyped) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *PolicyHuggingfaceDatasetCardTyped) GetAnnotationsCreators() optionalnullable.OptionalNullable[[]string] {
	if o == nil {
		return nil
	}
	return o.AnnotationsCreators
}

func (o *PolicyHuggingfaceDatasetCardTyped) GetConfigNames() optionalnullable.OptionalNullable[[]string] {
	if o == nil {
		return nil
	}
	return o.ConfigNames
}

func (o *PolicyHuggingfaceDatasetCardTyped) GetExtras() optionalnullable.OptionalNullable[map[string]any] {
	if o == nil {
		return nil
	}
	return o.Extras
}

func (o *PolicyHuggingfaceDatasetCardTyped) GetLanguage() optionalnullable.OptionalNullable[[]string] {
	if o == nil {
		return nil
	}
	return o.Language
}

func (o *PolicyHuggingfaceDatasetCardTyped) GetLanguageCreators() optionalnullable.OptionalNullable[[]string] {
	if o == nil {
		return nil
	}
	return o.LanguageCreators
}

func (o *PolicyHuggingfaceDatasetCardTyped) GetLicense() optionalnullable.OptionalNullable[[]string] {
	if o == nil {
		return nil
	}
	return o.License
}

func (o *PolicyHuggingfaceDatasetCardTyped) GetMultilinguality() optionalnullable.OptionalNullable[[]string] {
	if o == nil {
		return nil
	}
	return o.Multilinguality
}

func (o *PolicyHuggingfaceDatasetCardTyped) GetPaperswithcodeID() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.PaperswithcodeID
}

func (o *PolicyHuggingfaceDatasetCardTyped) GetPrettyName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.PrettyName
}

func (o *PolicyHuggingfaceDatasetCardTyped) GetSizeCategories() optionalnullable.OptionalNullable[[]string] {
	if o == nil {
		return nil
	}
	return o.SizeCategories
}

func (o *PolicyHuggingfaceDatasetCardTyped) GetSourceDatasets() optionalnullable.OptionalNullable[[]string] {
	if o == nil {
		return nil
	}
	return o.SourceDatasets
}

func (o *PolicyHuggingfaceDatasetCardTyped) GetTaskCategories() optionalnullable.OptionalNullable[[]string] {
	if o == nil {
		return nil
	}
	return o.TaskCategories
}

func (o *PolicyHuggingfaceDatasetCardTyped) GetTaskIds() optionalnullable.OptionalNullable[[]string] {
	if o == nil {
		return nil
	}
	return o.TaskIds
}

func (o *PolicyHuggingfaceDatasetCardTyped) GetTrainEvalIndex() optionalnullable.OptionalNullable[any] {
	if o == nil {
		return nil
	}
	return o.TrainEvalIndex
}

// PolicyHuggingfaceModelCardTyped - The model-card of a Huggingface package.
//
// The model-card is metadata specified inside the README.md file of a Huggingface model.
type PolicyHuggingfaceModelCardTyped struct {
	Type string `json:"type"`
	// ('The identifier of the base model from which the model derives. This is applicable for example if your', 'model is a fine-tune or adapter of an existing model. ')
	BaseModel optionalnullable.OptionalNullable[[]string] `json:"base_model,omitempty"`
	// The list of datasets used to train this model.
	Datasets    optionalnullable.OptionalNullable[[]string]                      `json:"datasets,omitempty"`
	EvalResults optionalnullable.OptionalNullable[[]PolicyHuggingfaceEvalResult] `json:"eval_results,omitempty"`
	// Any additional metadata fields present in the modelcard that is not one of the well-known fields.
	Extras optionalnullable.OptionalNullable[map[string]any] `json:"extras,omitempty"`
	// List of languages of the model's training data or metadata.
	Language optionalnullable.OptionalNullable[[]string] `json:"language,omitempty"`
	// The name of the library used to create the model, e.g. keras, pytorch, etc.
	LibraryName optionalnullable.OptionalNullable[string] `json:"library_name,omitempty"`
	// The license identifier of the model, e.g. apache-2.0.
	License optionalnullable.OptionalNullable[string] `json:"license,omitempty"`
	// The name of the license if using license_link, e.g. Apache 2.0.
	LicenseName optionalnullable.OptionalNullable[string] `json:"license_name,omitempty"`
	// The license URL for this model.
	LicenseLink optionalnullable.OptionalNullable[string] `json:"license_link,omitempty"`
	// List of metrics used to evaluate the model.
	Metrics optionalnullable.OptionalNullable[[]string] `json:"metrics,omitempty"`
	// Derived from the model-index.name attribute if it's present in the evaluation results.
	ModelName optionalnullable.OptionalNullable[string] `json:"model_name,omitempty"`
	// The pipeline tag for the model, e.g. text-classification, image-classification, etc.
	PipelineTag optionalnullable.OptionalNullable[string] `json:"pipeline_tag,omitempty"`
	// List of freeform tags to describe the model.
	Tags optionalnullable.OptionalNullable[[]string] `json:"tags,omitempty"`
}

func (p PolicyHuggingfaceModelCardTyped) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PolicyHuggingfaceModelCardTyped) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (o *PolicyHuggingfaceModelCardTyped) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *PolicyHuggingfaceModelCardTyped) GetBaseModel() optionalnullable.OptionalNullable[[]string] {
	if o == nil {
		return nil
	}
	return o.BaseModel
}

func (o *PolicyHuggingfaceModelCardTyped) GetDatasets() optionalnullable.OptionalNullable[[]string] {
	if o == nil {
		return nil
	}
	return o.Datasets
}

func (o *PolicyHuggingfaceModelCardTyped) GetEvalResults() optionalnullable.OptionalNullable[[]PolicyHuggingfaceEvalResult] {
	if o == nil {
		return nil
	}
	return o.EvalResults
}

func (o *PolicyHuggingfaceModelCardTyped) GetExtras() optionalnullable.OptionalNullable[map[string]any] {
	if o == nil {
		return nil
	}
	return o.Extras
}

func (o *PolicyHuggingfaceModelCardTyped) GetLanguage() optionalnullable.OptionalNullable[[]string] {
	if o == nil {
		return nil
	}
	return o.Language
}

func (o *PolicyHuggingfaceModelCardTyped) GetLibraryName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.LibraryName
}

func (o *PolicyHuggingfaceModelCardTyped) GetLicense() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.License
}

func (o *PolicyHuggingfaceModelCardTyped) GetLicenseName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.LicenseName
}

func (o *PolicyHuggingfaceModelCardTyped) GetLicenseLink() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.LicenseLink
}

func (o *PolicyHuggingfaceModelCardTyped) GetMetrics() optionalnullable.OptionalNullable[[]string] {
	if o == nil {
		return nil
	}
	return o.Metrics
}

func (o *PolicyHuggingfaceModelCardTyped) GetModelName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.ModelName
}

func (o *PolicyHuggingfaceModelCardTyped) GetPipelineTag() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.PipelineTag
}

func (o *PolicyHuggingfaceModelCardTyped) GetTags() optionalnullable.OptionalNullable[[]string] {
	if o == nil {
		return nil
	}
	return o.Tags
}

type PolicyHuggingfaceUnknownCardTyped struct {
	Type string `json:"type"`
}

func (p PolicyHuggingfaceUnknownCardTyped) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PolicyHuggingfaceUnknownCardTyped) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (o *PolicyHuggingfaceUnknownCardTyped) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

type CardType string

const (
	CardTypePolicyHuggingfaceUnknownCardTyped CardType = "PolicyHuggingfaceUnknownCardTyped"
	CardTypePolicyHuggingfaceModelCardTyped   CardType = "PolicyHuggingfaceModelCardTyped"
	CardTypePolicyHuggingfaceDatasetCardTyped CardType = "PolicyHuggingfaceDatasetCardTyped"
)

type Card struct {
	PolicyHuggingfaceUnknownCardTyped *PolicyHuggingfaceUnknownCardTyped `queryParam:"inline"`
	PolicyHuggingfaceModelCardTyped   *PolicyHuggingfaceModelCardTyped   `queryParam:"inline"`
	PolicyHuggingfaceDatasetCardTyped *PolicyHuggingfaceDatasetCardTyped `queryParam:"inline"`

	Type CardType
}

func CreateCardPolicyHuggingfaceUnknownCardTyped(policyHuggingfaceUnknownCardTyped PolicyHuggingfaceUnknownCardTyped) Card {
	typ := CardTypePolicyHuggingfaceUnknownCardTyped

	return Card{
		PolicyHuggingfaceUnknownCardTyped: &policyHuggingfaceUnknownCardTyped,
		Type:                              typ,
	}
}

func CreateCardPolicyHuggingfaceModelCardTyped(policyHuggingfaceModelCardTyped PolicyHuggingfaceModelCardTyped) Card {
	typ := CardTypePolicyHuggingfaceModelCardTyped

	return Card{
		PolicyHuggingfaceModelCardTyped: &policyHuggingfaceModelCardTyped,
		Type:                            typ,
	}
}

func CreateCardPolicyHuggingfaceDatasetCardTyped(policyHuggingfaceDatasetCardTyped PolicyHuggingfaceDatasetCardTyped) Card {
	typ := CardTypePolicyHuggingfaceDatasetCardTyped

	return Card{
		PolicyHuggingfaceDatasetCardTyped: &policyHuggingfaceDatasetCardTyped,
		Type:                              typ,
	}
}

func (u *Card) UnmarshalJSON(data []byte) error {

	var policyHuggingfaceUnknownCardTyped PolicyHuggingfaceUnknownCardTyped = PolicyHuggingfaceUnknownCardTyped{}
	if err := utils.UnmarshalJSON(data, &policyHuggingfaceUnknownCardTyped, "", true, nil); err == nil {
		u.PolicyHuggingfaceUnknownCardTyped = &policyHuggingfaceUnknownCardTyped
		u.Type = CardTypePolicyHuggingfaceUnknownCardTyped
		return nil
	}

	var policyHuggingfaceModelCardTyped PolicyHuggingfaceModelCardTyped = PolicyHuggingfaceModelCardTyped{}
	if err := utils.UnmarshalJSON(data, &policyHuggingfaceModelCardTyped, "", true, nil); err == nil {
		u.PolicyHuggingfaceModelCardTyped = &policyHuggingfaceModelCardTyped
		u.Type = CardTypePolicyHuggingfaceModelCardTyped
		return nil
	}

	var policyHuggingfaceDatasetCardTyped PolicyHuggingfaceDatasetCardTyped = PolicyHuggingfaceDatasetCardTyped{}
	if err := utils.UnmarshalJSON(data, &policyHuggingfaceDatasetCardTyped, "", true, nil); err == nil {
		u.PolicyHuggingfaceDatasetCardTyped = &policyHuggingfaceDatasetCardTyped
		u.Type = CardTypePolicyHuggingfaceDatasetCardTyped
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Card", string(data))
}

func (u Card) MarshalJSON() ([]byte, error) {
	if u.PolicyHuggingfaceUnknownCardTyped != nil {
		return utils.MarshalJSON(u.PolicyHuggingfaceUnknownCardTyped, "", true)
	}

	if u.PolicyHuggingfaceModelCardTyped != nil {
		return utils.MarshalJSON(u.PolicyHuggingfaceModelCardTyped, "", true)
	}

	if u.PolicyHuggingfaceDatasetCardTyped != nil {
		return utils.MarshalJSON(u.PolicyHuggingfaceDatasetCardTyped, "", true)
	}

	return nil, errors.New("could not marshal union type Card: all fields are null")
}

// PolicyHuggingfacePackageTypedUpstreamMetadata - Additional information in the form of arbitrary metadata that may be copied or added from the upstream source during upstream caching. For example the published at timestamp, or attestations etc.
type PolicyHuggingfacePackageTypedUpstreamMetadata struct {
	PublishedAt optionalnullable.OptionalNullable[time.Time] `json:"published_at,omitempty"`
}

func (p PolicyHuggingfacePackageTypedUpstreamMetadata) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PolicyHuggingfacePackageTypedUpstreamMetadata) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *PolicyHuggingfacePackageTypedUpstreamMetadata) GetPublishedAt() optionalnullable.OptionalNullable[time.Time] {
	if o == nil {
		return nil
	}
	return o.PublishedAt
}

// PolicyHuggingfacePackageTyped - The details of a Huggingface package for policy purposes.
//
// This extends the common package fields with Huggingface-specific fields including
// the model/dataset-card data.
type PolicyHuggingfacePackageTyped struct {
	Format        string                                  `json:"format"`
	Architectures []PolicyArchitecture                    `json:"architectures"`
	Card          optionalnullable.OptionalNullable[Card] `json:"card,omitempty"`
	// A textual description of this package.
	Description optionalnullable.OptionalNullable[string] `json:"description,omitempty"`
	Files       []PolicyHuggingfaceFileReference          `json:"files"`
	Indexed     *bool                                     `json:"indexed,omitempty"`
	// Whether the package is cached in the repository or proxied from an upstream
	IsLocal bool `json:"is_local"`
	// The last time the package was downloaded.
	LastDownloadedAt time.Time `json:"last_downloaded_at"`
	// The licensing details of a package.
	License PolicyPackageLicense `json:"license"`
	// The name of this package.
	Name     optionalnullable.OptionalNullable[string] `json:"name,omitempty"`
	NumFiles int64                                     `json:"num_files"`
	// * `BINARY` - Binary
	// * `SOURCE` - Source
	// * `COMBINED` - Combined
	// * `OTHER` - Other
	PackageType PackageTypeEnum `json:"package_type"`
	// The datetime the security scanning was completed.
	SecurityScanCompletedAt optionalnullable.OptionalNullable[time.Time] `json:"security_scan_completed_at,omitempty"`
	// The datetime the security scanning was started.
	SecurityScanStartedAt optionalnullable.OptionalNullable[time.Time] `json:"security_scan_started_at,omitempty"`
	// * `AWAITING_SCAN` - Awaiting Security Scan
	// * `SCANNING` - Security Scanning in Progress
	// * `VULNERABLE` - Scan Detected Vulnerabilities
	// * `NOT_VULNERABLE` - Scan Detected No Vulnerabilities
	// * `DISABLED` - Security Scanning Disabled
	// * `FAILED` - Security Scanning Failed
	// * `SKIPPED` - Security Scanning Skipped
	// * `UNSUPPORTED_PACKAGE` - Security Scanning Not Supported
	// * `UNSUPPORTED_FORMAT` - Security Scanning Not Supported
	SecurityScanStatus SecurityScanStatusEnum `json:"security_scan_status"`
	// The datetime the security scanning status was updated.
	SecurityScanStatusUpdatedAt optionalnullable.OptionalNullable[time.Time] `json:"security_scan_status_updated_at,omitempty"`
	// The calculated size of the package.
	Size *int64 `json:"size,omitempty"`
	// The public unique identifier for the package.
	Slug     string  `json:"slug"`
	SlugPerm *string `json:"slug_perm,omitempty"`
	// A one-liner synopsis of this package.
	Summary optionalnullable.OptionalNullable[string] `json:"summary,omitempty"`
	Tags    []PolicyPackageTag                        `json:"tags"`
	// The date this package was uploaded.
	UploadedAt *time.Time `json:"uploaded_at,omitempty"`
	// The package uploader for policy puposes.
	Uploader *PolicyUploader `json:"uploader,omitempty"`
	// Additional information in the form of arbitrary metadata that may be copied or added from the upstream source during upstream caching. For example the published at timestamp, or attestations etc.
	UpstreamMetadata optionalnullable.OptionalNullable[PolicyHuggingfacePackageTypedUpstreamMetadata] `json:"upstream_metadata,omitempty"`
	// The raw version for this package.
	Version optionalnullable.OptionalNullable[string] `json:"version,omitempty"`
}

func (p PolicyHuggingfacePackageTyped) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PolicyHuggingfacePackageTyped) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"format", "architectures", "files", "is_local", "last_downloaded_at", "license", "num_files", "package_type", "security_scan_status", "slug", "tags"}); err != nil {
		return err
	}
	return nil
}

func (o *PolicyHuggingfacePackageTyped) GetFormat() string {
	if o == nil {
		return ""
	}
	return o.Format
}

func (o *PolicyHuggingfacePackageTyped) GetArchitectures() []PolicyArchitecture {
	if o == nil {
		return []PolicyArchitecture{}
	}
	return o.Architectures
}

func (o *PolicyHuggingfacePackageTyped) GetCard() optionalnullable.OptionalNullable[Card] {
	if o == nil {
		return nil
	}
	return o.Card
}

func (o *PolicyHuggingfacePackageTyped) GetDescription() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *PolicyHuggingfacePackageTyped) GetFiles() []PolicyHuggingfaceFileReference {
	if o == nil {
		return []PolicyHuggingfaceFileReference{}
	}
	return o.Files
}

func (o *PolicyHuggingfacePackageTyped) GetIndexed() *bool {
	if o == nil {
		return nil
	}
	return o.Indexed
}

func (o *PolicyHuggingfacePackageTyped) GetIsLocal() bool {
	if o == nil {
		return false
	}
	return o.IsLocal
}

func (o *PolicyHuggingfacePackageTyped) GetLastDownloadedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.LastDownloadedAt
}

func (o *PolicyHuggingfacePackageTyped) GetLicense() PolicyPackageLicense {
	if o == nil {
		return PolicyPackageLicense{}
	}
	return o.License
}

func (o *PolicyHuggingfacePackageTyped) GetName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *PolicyHuggingfacePackageTyped) GetNumFiles() int64 {
	if o == nil {
		return 0
	}
	return o.NumFiles
}

func (o *PolicyHuggingfacePackageTyped) GetPackageType() PackageTypeEnum {
	if o == nil {
		return PackageTypeEnum("")
	}
	return o.PackageType
}

func (o *PolicyHuggingfacePackageTyped) GetSecurityScanCompletedAt() optionalnullable.OptionalNullable[time.Time] {
	if o == nil {
		return nil
	}
	return o.SecurityScanCompletedAt
}

func (o *PolicyHuggingfacePackageTyped) GetSecurityScanStartedAt() optionalnullable.OptionalNullable[time.Time] {
	if o == nil {
		return nil
	}
	return o.SecurityScanStartedAt
}

func (o *PolicyHuggingfacePackageTyped) GetSecurityScanStatus() SecurityScanStatusEnum {
	if o == nil {
		return SecurityScanStatusEnum("")
	}
	return o.SecurityScanStatus
}

func (o *PolicyHuggingfacePackageTyped) GetSecurityScanStatusUpdatedAt() optionalnullable.OptionalNullable[time.Time] {
	if o == nil {
		return nil
	}
	return o.SecurityScanStatusUpdatedAt
}

func (o *PolicyHuggingfacePackageTyped) GetSize() *int64 {
	if o == nil {
		return nil
	}
	return o.Size
}

func (o *PolicyHuggingfacePackageTyped) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *PolicyHuggingfacePackageTyped) GetSlugPerm() *string {
	if o == nil {
		return nil
	}
	return o.SlugPerm
}

func (o *PolicyHuggingfacePackageTyped) GetSummary() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Summary
}

func (o *PolicyHuggingfacePackageTyped) GetTags() []PolicyPackageTag {
	if o == nil {
		return []PolicyPackageTag{}
	}
	return o.Tags
}

func (o *PolicyHuggingfacePackageTyped) GetUploadedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UploadedAt
}

func (o *PolicyHuggingfacePackageTyped) GetUploader() *PolicyUploader {
	if o == nil {
		return nil
	}
	return o.Uploader
}

func (o *PolicyHuggingfacePackageTyped) GetUpstreamMetadata() optionalnullable.OptionalNullable[PolicyHuggingfacePackageTypedUpstreamMetadata] {
	if o == nil {
		return nil
	}
	return o.UpstreamMetadata
}

func (o *PolicyHuggingfacePackageTyped) GetVersion() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Version
}
