// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 07ec2572369b

package components

import (
	"mockserver/internal/sdk/optionalnullable"
	"mockserver/internal/sdk/utils"
	"time"
)

// PolicyRepositoryEcdsaKey - An ECDSA key used to sign repository contents.
type PolicyRepositoryEcdsaKey struct {
	// If selected this is the active key for this repository.
	Active    *bool      `json:"active,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// If selected this is the default key for this repository.
	Default          *bool  `json:"default,omitempty"`
	FingerprintShort string `json:"fingerprint_short"`
	// The long identifier used by ECDSA for this key.
	Fingerprint string `json:"fingerprint"`
	// The public key given to repository users.
	PublicKey string `json:"public_key"`
	// The SSH fingerprint used by ECDSA for this key.
	SSHFingerprint optionalnullable.OptionalNullable[string] `json:"ssh_fingerprint,omitempty"`
}

func (p PolicyRepositoryEcdsaKey) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PolicyRepositoryEcdsaKey) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"fingerprint_short", "fingerprint", "public_key"}); err != nil {
		return err
	}
	return nil
}

func (o *PolicyRepositoryEcdsaKey) GetActive() *bool {
	if o == nil {
		return nil
	}
	return o.Active
}

func (o *PolicyRepositoryEcdsaKey) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *PolicyRepositoryEcdsaKey) GetDefault() *bool {
	if o == nil {
		return nil
	}
	return o.Default
}

func (o *PolicyRepositoryEcdsaKey) GetFingerprintShort() string {
	if o == nil {
		return ""
	}
	return o.FingerprintShort
}

func (o *PolicyRepositoryEcdsaKey) GetFingerprint() string {
	if o == nil {
		return ""
	}
	return o.Fingerprint
}

func (o *PolicyRepositoryEcdsaKey) GetPublicKey() string {
	if o == nil {
		return ""
	}
	return o.PublicKey
}

func (o *PolicyRepositoryEcdsaKey) GetSSHFingerprint() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.SSHFingerprint
}
