// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c9651706f079

package components

// PolicyInput2 - Serializer for policy input.
type PolicyInput2 struct {
	// Serializer for V0 policy input.
	V0 PolicyInputV0 `json:"v0"`
}

func (o *PolicyInput2) GetV0() PolicyInputV0 {
	if o == nil {
		return PolicyInputV0{}
	}
	return o.V0
}
