// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 519b8dcacbef

package components

import (
	"mockserver/internal/sdk/utils"
	"time"
)

type RemovePackageTagsPolicyActionTyped struct {
	ActionType string `json:"action_type"`
	// The order in which this action occurs relative to other actions for the same policy.
	Precedence *int64 `json:"precedence,omitempty"`
	// The Action identifier.
	SlugPerm string `json:"slug_perm"`
	// The date and time the policy was created.
	CreatedAt time.Time `json:"created_at"`
	// The date and time the policy was updated.
	UpdatedAt time.Time `json:"updated_at"`
	Effect    string    `json:"effect"`
	Tags      []string  `json:"tags"`
}

func (r RemovePackageTagsPolicyActionTyped) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RemovePackageTagsPolicyActionTyped) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"action_type", "slug_perm", "created_at", "updated_at", "effect", "tags"}); err != nil {
		return err
	}
	return nil
}

func (o *RemovePackageTagsPolicyActionTyped) GetActionType() string {
	if o == nil {
		return ""
	}
	return o.ActionType
}

func (o *RemovePackageTagsPolicyActionTyped) GetPrecedence() *int64 {
	if o == nil {
		return nil
	}
	return o.Precedence
}

func (o *RemovePackageTagsPolicyActionTyped) GetSlugPerm() string {
	if o == nil {
		return ""
	}
	return o.SlugPerm
}

func (o *RemovePackageTagsPolicyActionTyped) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *RemovePackageTagsPolicyActionTyped) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}

func (o *RemovePackageTagsPolicyActionTyped) GetEffect() string {
	if o == nil {
		return ""
	}
	return o.Effect
}

func (o *RemovePackageTagsPolicyActionTyped) GetTags() []string {
	if o == nil {
		return []string{}
	}
	return o.Tags
}
