// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b9cb5b81b4b7

package components

import (
	"encoding/json"
	"fmt"
)

// RepositoryTypeEnum - * `PUBLIC` - Public
// * `PRIVATE` - Private
// * `OPEN_SOURCE` - Open-Source
type RepositoryTypeEnum string

const (
	RepositoryTypeEnumPublic     RepositoryTypeEnum = "PUBLIC"
	RepositoryTypeEnumPrivate    RepositoryTypeEnum = "PRIVATE"
	RepositoryTypeEnumOpenSource RepositoryTypeEnum = "OPEN_SOURCE"
)

func (e RepositoryTypeEnum) ToPointer() *RepositoryTypeEnum {
	return &e
}
func (e *RepositoryTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PUBLIC":
		fallthrough
	case "PRIVATE":
		fallthrough
	case "OPEN_SOURCE":
		*e = RepositoryTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RepositoryTypeEnum: %v", v)
	}
}
