// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c69fd513b4b6

package components

import (
	"encoding/json"
	"fmt"
)

// ScanSummaryEnum - * `UNSAFE` - Unsafe
// * `UNKNOWN` - Unknown
// * `QUEUED` - Queued
// * `SAFE` - Safe
type ScanSummaryEnum string

const (
	ScanSummaryEnumUnsafe  ScanSummaryEnum = "UNSAFE"
	ScanSummaryEnumUnknown ScanSummaryEnum = "UNKNOWN"
	ScanSummaryEnumQueued  ScanSummaryEnum = "QUEUED"
	ScanSummaryEnumSafe    ScanSummaryEnum = "SAFE"
)

func (e ScanSummaryEnum) ToPointer() *ScanSummaryEnum {
	return &e
}
func (e *ScanSummaryEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "UNSAFE":
		fallthrough
	case "UNKNOWN":
		fallthrough
	case "QUEUED":
		fallthrough
	case "SAFE":
		*e = ScanSummaryEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ScanSummaryEnum: %v", v)
	}
}
