// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: fa6cb32e2c62

package components

type Security struct {
	Apikey string `security:"scheme,type=apiKey,subtype=header,name=X-Api-Key"`
}

func (o *Security) GetApikey() string {
	if o == nil {
		return ""
	}
	return o.Apikey
}
