// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: dc35b0f3aa68

package components

import (
	"encoding/json"
	"fmt"
)

// SecurityScanStatusEnum - * `AWAITING_SCAN` - Awaiting Security Scan
// * `SCANNING` - Security Scanning in Progress
// * `VULNERABLE` - Scan Detected Vulnerabilities
// * `NOT_VULNERABLE` - Scan Detected No Vulnerabilities
// * `DISABLED` - Security Scanning Disabled
// * `FAILED` - Security Scanning Failed
// * `SKIPPED` - Security Scanning Skipped
// * `UNSUPPORTED_PACKAGE` - Security Scanning Not Supported
// * `UNSUPPORTED_FORMAT` - Security Scanning Not Supported
type SecurityScanStatusEnum string

const (
	SecurityScanStatusEnumAwaitingScan       SecurityScanStatusEnum = "AWAITING_SCAN"
	SecurityScanStatusEnumScanning           SecurityScanStatusEnum = "SCANNING"
	SecurityScanStatusEnumVulnerable         SecurityScanStatusEnum = "VULNERABLE"
	SecurityScanStatusEnumNotVulnerable      SecurityScanStatusEnum = "NOT_VULNERABLE"
	SecurityScanStatusEnumDisabled           SecurityScanStatusEnum = "DISABLED"
	SecurityScanStatusEnumFailed             SecurityScanStatusEnum = "FAILED"
	SecurityScanStatusEnumSkipped            SecurityScanStatusEnum = "SKIPPED"
	SecurityScanStatusEnumUnsupportedPackage SecurityScanStatusEnum = "UNSUPPORTED_PACKAGE"
	SecurityScanStatusEnumUnsupportedFormat  SecurityScanStatusEnum = "UNSUPPORTED_FORMAT"
)

func (e SecurityScanStatusEnum) ToPointer() *SecurityScanStatusEnum {
	return &e
}
func (e *SecurityScanStatusEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "AWAITING_SCAN":
		fallthrough
	case "SCANNING":
		fallthrough
	case "VULNERABLE":
		fallthrough
	case "NOT_VULNERABLE":
		fallthrough
	case "DISABLED":
		fallthrough
	case "FAILED":
		fallthrough
	case "SKIPPED":
		fallthrough
	case "UNSUPPORTED_PACKAGE":
		fallthrough
	case "UNSUPPORTED_FORMAT":
		*e = SecurityScanStatusEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SecurityScanStatusEnum: %v", v)
	}
}
