// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f2e0d7acf680

package components

import (
	"mockserver/internal/sdk/utils"
	"time"
)

type SetPackageStatePolicyActionTyped struct {
	ActionType string `json:"action_type"`
	// The order in which this action occurs relative to other actions for the same policy.
	Precedence *int64 `json:"precedence,omitempty"`
	// The Action identifier.
	SlugPerm string `json:"slug_perm"`
	// The date and time the policy was created.
	CreatedAt time.Time `json:"created_at"`
	// The date and time the policy was updated.
	UpdatedAt time.Time `json:"updated_at"`
	Effect    string    `json:"effect"`
	// * `AVAILABLE` - The package is available for download.
	// * `DELETED` - The package is deleted.
	// * `QUARANTINED` - The package is quarantined.
	// * `HIDDEN` - The package is hidden.
	PackageState PackageStateEnum `json:"package_state"`
}

func (s SetPackageStatePolicyActionTyped) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SetPackageStatePolicyActionTyped) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"action_type", "slug_perm", "created_at", "updated_at", "effect", "package_state"}); err != nil {
		return err
	}
	return nil
}

func (o *SetPackageStatePolicyActionTyped) GetActionType() string {
	if o == nil {
		return ""
	}
	return o.ActionType
}

func (o *SetPackageStatePolicyActionTyped) GetPrecedence() *int64 {
	if o == nil {
		return nil
	}
	return o.Precedence
}

func (o *SetPackageStatePolicyActionTyped) GetSlugPerm() string {
	if o == nil {
		return ""
	}
	return o.SlugPerm
}

func (o *SetPackageStatePolicyActionTyped) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *SetPackageStatePolicyActionTyped) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}

func (o *SetPackageStatePolicyActionTyped) GetEffect() string {
	if o == nil {
		return ""
	}
	return o.Effect
}

func (o *SetPackageStatePolicyActionTyped) GetPackageState() PackageStateEnum {
	if o == nil {
		return PackageStateEnum("")
	}
	return o.PackageState
}
