// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9489aa59bbe3

package components

import (
	"encoding/json"
	"fmt"
)

// SeverityEnum - * `LOW` - LOW
// * `MEDIUM` - MEDIUM
// * `HIGH` - HIGH
// * `CRITICAL` - CRITICAL
type SeverityEnum string

const (
	SeverityEnumLow      SeverityEnum = "LOW"
	SeverityEnumMedium   SeverityEnum = "MEDIUM"
	SeverityEnumHigh     SeverityEnum = "HIGH"
	SeverityEnumCritical SeverityEnum = "CRITICAL"
)

func (e SeverityEnum) ToPointer() *SeverityEnum {
	return &e
}
func (e *SeverityEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "LOW":
		fallthrough
	case "MEDIUM":
		fallthrough
	case "HIGH":
		fallthrough
	case "CRITICAL":
		*e = SeverityEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SeverityEnum: %v", v)
	}
}
