// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 52618b34a568

package components

import (
	"encoding/json"
	"fmt"
)

// SourceKindEnum - * `UNKNOWN` - Unknown
// * `SYSTEM` - System
// * `UPSTREAM` - Upstream
// * `CUSTOM` - Custom
// * `THIRD_PARTY` - Third Party
type SourceKindEnum string

const (
	SourceKindEnumUnknown    SourceKindEnum = "UNKNOWN"
	SourceKindEnumSystem     SourceKindEnum = "SYSTEM"
	SourceKindEnumUpstream   SourceKindEnum = "UPSTREAM"
	SourceKindEnumCustom     SourceKindEnum = "CUSTOM"
	SourceKindEnumThirdParty SourceKindEnum = "THIRD_PARTY"
)

func (e SourceKindEnum) ToPointer() *SourceKindEnum {
	return &e
}
func (e *SourceKindEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "UNKNOWN":
		fallthrough
	case "SYSTEM":
		fallthrough
	case "UPSTREAM":
		fallthrough
	case "CUSTOM":
		fallthrough
	case "THIRD_PARTY":
		*e = SourceKindEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceKindEnum: %v", v)
	}
}
