// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e2c96e2041c9

package apierrors

import (
	"encoding/json"
	"github.com/cloudsmith-io/cloudsmith-go-v2/models/components"
)

// ErrorDetail - A serializer for displaying a detail error message.
type ErrorDetail struct {
	// An extended message for the response.
	Detail string `json:"detail"`
	// A Dictionary of related errors where key: Field and value: Array of Errors related to that field
	Fields   map[string][]string     `json:"fields,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ErrorDetail{}

func (e *ErrorDetail) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
