// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ab999678a924

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type PackagesMetadataRetrieveRequest struct {
	// The `slug_perm` of the package.
	PackageSlugPerm string `pathParam:"style=simple,explode=false,name=package_slug_perm"`
	// The `slug_perm` of the metadata entry.
	SlugPerm string `pathParam:"style=simple,explode=false,name=slug_perm"`
}

func (o *PackagesMetadataRetrieveRequest) GetPackageSlugPerm() string {
	if o == nil {
		return ""
	}
	return o.PackageSlugPerm
}

func (o *PackagesMetadataRetrieveRequest) GetSlugPerm() string {
	if o == nil {
		return ""
	}
	return o.SlugPerm
}

type PackagesMetadataRetrieveResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The requested metadata entry.
	ArtifactMetadataRead *components.ArtifactMetadataRead
}

func (o *PackagesMetadataRetrieveResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PackagesMetadataRetrieveResponse) GetArtifactMetadataRead() *components.ArtifactMetadataRead {
	if o == nil {
		return nil
	}
	return o.ArtifactMetadataRead
}
