// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1eec01b28320

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type WorkspacesPoliciesRetrieveRequest struct {
	// The `slug_perm` (identifier) of the Policy.
	Policy string `pathParam:"style=simple,explode=false,name=policy"`
	// The `name` of the Workspace.
	Workspace string `pathParam:"style=simple,explode=false,name=workspace"`
}

func (o *WorkspacesPoliciesRetrieveRequest) GetPolicy() string {
	if o == nil {
		return ""
	}
	return o.Policy
}

func (o *WorkspacesPoliciesRetrieveRequest) GetWorkspace() string {
	if o == nil {
		return ""
	}
	return o.Workspace
}

type WorkspacesPoliciesRetrieveResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Policy   *components.Policy
}

func (o *WorkspacesPoliciesRetrieveResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *WorkspacesPoliciesRetrieveResponse) GetPolicy() *components.Policy {
	if o == nil {
		return nil
	}
	return o.Policy
}
