// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: bd3d317820cf

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type WorkspacesPoliciesActionsPartialUpdateRequest struct {
	// The `slug_perm` (identifier) of the Action.
	Action string `pathParam:"style=simple,explode=false,name=action"`
	// The `slug_perm` (identifier) of the Policy.
	Policy string `pathParam:"style=simple,explode=false,name=policy"`
	// The `name` of the Workspace.
	Workspace string                          `pathParam:"style=simple,explode=false,name=workspace"`
	Body      *components.PatchedPolicyAction `request:"mediaType=application/json"`
}

func (o *WorkspacesPoliciesActionsPartialUpdateRequest) GetAction() string {
	if o == nil {
		return ""
	}
	return o.Action
}

func (o *WorkspacesPoliciesActionsPartialUpdateRequest) GetPolicy() string {
	if o == nil {
		return ""
	}
	return o.Policy
}

func (o *WorkspacesPoliciesActionsPartialUpdateRequest) GetWorkspace() string {
	if o == nil {
		return ""
	}
	return o.Workspace
}

func (o *WorkspacesPoliciesActionsPartialUpdateRequest) GetBody() *components.PatchedPolicyAction {
	if o == nil {
		return nil
	}
	return o.Body
}

func (o *WorkspacesPoliciesActionsPartialUpdateRequest) GetBodySetPackageState() *components.PatchedSetPackageStatePolicyActionTyped {
	if v := o.GetBody(); v != nil {
		return v.PatchedSetPackageStatePolicyActionTyped
	}
	return nil
}

func (o *WorkspacesPoliciesActionsPartialUpdateRequest) GetBodyAddPackageTags() *components.PatchedAddPackageTagsPolicyActionTyped {
	if v := o.GetBody(); v != nil {
		return v.PatchedAddPackageTagsPolicyActionTyped
	}
	return nil
}

func (o *WorkspacesPoliciesActionsPartialUpdateRequest) GetBodyRemovePackageTags() *components.PatchedRemovePackageTagsPolicyActionTyped {
	if v := o.GetBody(); v != nil {
		return v.PatchedRemovePackageTagsPolicyActionTyped
	}
	return nil
}

type WorkspacesPoliciesActionsPartialUpdateResponse struct {
	HTTPMeta     components.HTTPMetadata `json:"-"`
	PolicyAction *components.PolicyAction
}

func (o *WorkspacesPoliciesActionsPartialUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *WorkspacesPoliciesActionsPartialUpdateResponse) GetPolicyAction() *components.PolicyAction {
	if o == nil {
		return nil
	}
	return o.PolicyAction
}

func (o *WorkspacesPoliciesActionsPartialUpdateResponse) GetPolicyActionSetPackageState() *components.SetPackageStatePolicyActionTyped {
	if v := o.GetPolicyAction(); v != nil {
		return v.SetPackageStatePolicyActionTyped
	}
	return nil
}

func (o *WorkspacesPoliciesActionsPartialUpdateResponse) GetPolicyActionAddPackageTags() *components.AddPackageTagsPolicyActionTyped {
	if v := o.GetPolicyAction(); v != nil {
		return v.AddPackageTagsPolicyActionTyped
	}
	return nil
}

func (o *WorkspacesPoliciesActionsPartialUpdateResponse) GetPolicyActionRemovePackageTags() *components.RemovePackageTagsPolicyActionTyped {
	if v := o.GetPolicyAction(); v != nil {
		return v.RemovePackageTagsPolicyActionTyped
	}
	return nil
}
