// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 085ecfe3bb8c

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type WorkspacesPoliciesPartialUpdateRequest struct {
	// The `slug_perm` (identifier) of the Policy.
	Policy string `pathParam:"style=simple,explode=false,name=policy"`
	// The `name` of the Workspace.
	Workspace string                    `pathParam:"style=simple,explode=false,name=workspace"`
	Body      *components.PatchedPolicy `request:"mediaType=application/json"`
}

func (o *WorkspacesPoliciesPartialUpdateRequest) GetPolicy() string {
	if o == nil {
		return ""
	}
	return o.Policy
}

func (o *WorkspacesPoliciesPartialUpdateRequest) GetWorkspace() string {
	if o == nil {
		return ""
	}
	return o.Workspace
}

func (o *WorkspacesPoliciesPartialUpdateRequest) GetBody() *components.PatchedPolicy {
	if o == nil {
		return nil
	}
	return o.Body
}

type WorkspacesPoliciesPartialUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Policy   *components.Policy
}

func (o *WorkspacesPoliciesPartialUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *WorkspacesPoliciesPartialUpdateResponse) GetPolicy() *components.Policy {
	if o == nil {
		return nil
	}
	return o.Policy
}
