// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 94face5bcf8f

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type WorkspacesPoliciesCreateRequest struct {
	// The `name` of the Workspace.
	Workspace string                  `pathParam:"style=simple,explode=false,name=workspace"`
	Body      components.PolicyInput1 `request:"mediaType=application/json"`
}

func (o *WorkspacesPoliciesCreateRequest) GetWorkspace() string {
	if o == nil {
		return ""
	}
	return o.Workspace
}

func (o *WorkspacesPoliciesCreateRequest) GetBody() components.PolicyInput1 {
	if o == nil {
		return components.PolicyInput1{}
	}
	return o.Body
}

type WorkspacesPoliciesCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Policy   *components.Policy
}

func (o *WorkspacesPoliciesCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *WorkspacesPoliciesCreateResponse) GetPolicy() *components.Policy {
	if o == nil {
		return nil
	}
	return o.Policy
}
