// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ed7756d317b2

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type WorkspacesPoliciesActionsCreateRequest struct {
	// The `slug_perm` (identifier) of the Policy.
	Policy string `pathParam:"style=simple,explode=false,name=policy"`
	// The `name` of the Workspace.
	Workspace string                        `pathParam:"style=simple,explode=false,name=workspace"`
	Body      *components.PolicyActionInput `request:"mediaType=application/json"`
}

func (o *WorkspacesPoliciesActionsCreateRequest) GetPolicy() string {
	if o == nil {
		return ""
	}
	return o.Policy
}

func (o *WorkspacesPoliciesActionsCreateRequest) GetWorkspace() string {
	if o == nil {
		return ""
	}
	return o.Workspace
}

func (o *WorkspacesPoliciesActionsCreateRequest) GetBody() *components.PolicyActionInput {
	if o == nil {
		return nil
	}
	return o.Body
}

func (o *WorkspacesPoliciesActionsCreateRequest) GetBodySetPackageState() *components.SetPackageStatePolicyActionTypedInput {
	if v := o.GetBody(); v != nil {
		return v.SetPackageStatePolicyActionTypedInput
	}
	return nil
}

func (o *WorkspacesPoliciesActionsCreateRequest) GetBodyAddPackageTags() *components.AddPackageTagsPolicyActionTypedInput {
	if v := o.GetBody(); v != nil {
		return v.AddPackageTagsPolicyActionTypedInput
	}
	return nil
}

func (o *WorkspacesPoliciesActionsCreateRequest) GetBodyRemovePackageTags() *components.RemovePackageTagsPolicyActionTypedInput {
	if v := o.GetBody(); v != nil {
		return v.RemovePackageTagsPolicyActionTypedInput
	}
	return nil
}

type WorkspacesPoliciesActionsCreateResponse struct {
	HTTPMeta     components.HTTPMetadata `json:"-"`
	PolicyAction *components.PolicyAction
}

func (o *WorkspacesPoliciesActionsCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *WorkspacesPoliciesActionsCreateResponse) GetPolicyAction() *components.PolicyAction {
	if o == nil {
		return nil
	}
	return o.PolicyAction
}

func (o *WorkspacesPoliciesActionsCreateResponse) GetPolicyActionSetPackageState() *components.SetPackageStatePolicyActionTyped {
	if v := o.GetPolicyAction(); v != nil {
		return v.SetPackageStatePolicyActionTyped
	}
	return nil
}

func (o *WorkspacesPoliciesActionsCreateResponse) GetPolicyActionAddPackageTags() *components.AddPackageTagsPolicyActionTyped {
	if v := o.GetPolicyAction(); v != nil {
		return v.AddPackageTagsPolicyActionTyped
	}
	return nil
}

func (o *WorkspacesPoliciesActionsCreateResponse) GetPolicyActionRemovePackageTags() *components.RemovePackageTagsPolicyActionTyped {
	if v := o.GetPolicyAction(); v != nil {
		return v.RemovePackageTagsPolicyActionTyped
	}
	return nil
}
