// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 84a1ef342430

package operations

import (
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type WorkspacesPoliciesListRequest struct {
	// A page number within the paginated result set.
	Page int64 `queryParam:"style=form,explode=true,name=page"`
	// Number of results to return per page.
	PageSize *int64 `queryParam:"style=form,explode=true,name=page_size"`
	// A search string to limit results by name. Legal fields are: `name`, `enabled`. Boolean operators may be used to construct intricate queries. Omitting boolean operators is interpreted as an implicit `AND`.
	Query *string `queryParam:"style=form,explode=true,name=query"`
	// A comma-separated string of fields to sort by. Legal fields are: `created_at`, `enabled`, `name`, `precedence`, `version`, `updated_at`. Descending order can be expressed by prepending `-` to a field name.
	Sort *string `default:"-created_at" queryParam:"style=form,explode=true,name=sort"`
	// The `name` of the Workspace.
	Workspace string `pathParam:"style=simple,explode=false,name=workspace"`
}

func (w WorkspacesPoliciesListRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WorkspacesPoliciesListRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, []string{"page", "workspace"}); err != nil {
		return err
	}
	return nil
}

func (o *WorkspacesPoliciesListRequest) GetPage() int64 {
	if o == nil {
		return 0
	}
	return o.Page
}

func (o *WorkspacesPoliciesListRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *WorkspacesPoliciesListRequest) GetQuery() *string {
	if o == nil {
		return nil
	}
	return o.Query
}

func (o *WorkspacesPoliciesListRequest) GetSort() *string {
	if o == nil {
		return nil
	}
	return o.Sort
}

func (o *WorkspacesPoliciesListRequest) GetWorkspace() string {
	if o == nil {
		return ""
	}
	return o.Workspace
}

type WorkspacesPoliciesListResponse struct {
	HTTPMeta            components.HTTPMetadata `json:"-"`
	PaginatedPolicyList *components.PaginatedPolicyList

	Next func() (*WorkspacesPoliciesListResponse, error)
}

func (o *WorkspacesPoliciesListResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *WorkspacesPoliciesListResponse) GetPaginatedPolicyList() *components.PaginatedPolicyList {
	if o == nil {
		return nil
	}
	return o.PaginatedPolicyList
}
