// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 8d45c82f931a

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type WorkspacesPoliciesActionsDestroyRequest struct {
	// The `slug_perm` (identifier) of the Action.
	Action string `pathParam:"style=simple,explode=false,name=action"`
	// The `slug_perm` (identifier) of the Policy.
	Policy string `pathParam:"style=simple,explode=false,name=policy"`
	// The `name` of the Workspace.
	Workspace string `pathParam:"style=simple,explode=false,name=workspace"`
}

func (o *WorkspacesPoliciesActionsDestroyRequest) GetAction() string {
	if o == nil {
		return ""
	}
	return o.Action
}

func (o *WorkspacesPoliciesActionsDestroyRequest) GetPolicy() string {
	if o == nil {
		return ""
	}
	return o.Policy
}

func (o *WorkspacesPoliciesActionsDestroyRequest) GetWorkspace() string {
	if o == nil {
		return ""
	}
	return o.Workspace
}

type WorkspacesPoliciesActionsDestroyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *WorkspacesPoliciesActionsDestroyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
