// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ee7398c9e876

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type WorkspacesPoliciesActionsRetrieveRequest struct {
	// The `slug_perm` (identifier) of the Action.
	Action string `pathParam:"style=simple,explode=false,name=action"`
	// The `slug_perm` (identifier) of the Policy.
	Policy string `pathParam:"style=simple,explode=false,name=policy"`
	// The `name` of the Workspace.
	Workspace string `pathParam:"style=simple,explode=false,name=workspace"`
}

func (o *WorkspacesPoliciesActionsRetrieveRequest) GetAction() string {
	if o == nil {
		return ""
	}
	return o.Action
}

func (o *WorkspacesPoliciesActionsRetrieveRequest) GetPolicy() string {
	if o == nil {
		return ""
	}
	return o.Policy
}

func (o *WorkspacesPoliciesActionsRetrieveRequest) GetWorkspace() string {
	if o == nil {
		return ""
	}
	return o.Workspace
}

type WorkspacesPoliciesActionsRetrieveResponse struct {
	HTTPMeta     components.HTTPMetadata `json:"-"`
	PolicyAction *components.PolicyAction
}

func (o *WorkspacesPoliciesActionsRetrieveResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *WorkspacesPoliciesActionsRetrieveResponse) GetPolicyAction() *components.PolicyAction {
	if o == nil {
		return nil
	}
	return o.PolicyAction
}

func (o *WorkspacesPoliciesActionsRetrieveResponse) GetPolicyActionSetPackageState() *components.SetPackageStatePolicyActionTyped {
	if v := o.GetPolicyAction(); v != nil {
		return v.SetPackageStatePolicyActionTyped
	}
	return nil
}

func (o *WorkspacesPoliciesActionsRetrieveResponse) GetPolicyActionAddPackageTags() *components.AddPackageTagsPolicyActionTyped {
	if v := o.GetPolicyAction(); v != nil {
		return v.AddPackageTagsPolicyActionTyped
	}
	return nil
}

func (o *WorkspacesPoliciesActionsRetrieveResponse) GetPolicyActionRemovePackageTags() *components.RemovePackageTagsPolicyActionTyped {
	if v := o.GetPolicyAction(); v != nil {
		return v.RemovePackageTagsPolicyActionTyped
	}
	return nil
}
