// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d53608c99c82

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type WorkspacesPoliciesSimulateListRequest struct {
	// A [package search](https://help.cloudsmith.io/docs/search-packages) query by which to filter the packages being evaluated.
	PackageQueryString *string `queryParam:"style=form,explode=true,name=package_query_string"`
	// A page number within the paginated result set.
	Page *int64 `queryParam:"style=form,explode=true,name=page"`
	// Number of results to return per page.
	PageSize *int64 `queryParam:"style=form,explode=true,name=page_size"`
	// The `slug_perm` (identifier) of the Policy.
	Policy string `pathParam:"style=simple,explode=false,name=policy"`
	// The `name` of the Workspace.
	Workspace string `pathParam:"style=simple,explode=false,name=workspace"`
}

func (o *WorkspacesPoliciesSimulateListRequest) GetPackageQueryString() *string {
	if o == nil {
		return nil
	}
	return o.PackageQueryString
}

func (o *WorkspacesPoliciesSimulateListRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *WorkspacesPoliciesSimulateListRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *WorkspacesPoliciesSimulateListRequest) GetPolicy() string {
	if o == nil {
		return ""
	}
	return o.Policy
}

func (o *WorkspacesPoliciesSimulateListRequest) GetWorkspace() string {
	if o == nil {
		return ""
	}
	return o.Workspace
}

type WorkspacesPoliciesSimulateListResponse struct {
	HTTPMeta                       components.HTTPMetadata `json:"-"`
	PaginatedPolicyDecisionLogList *components.PaginatedPolicyDecisionLogList
}

func (o *WorkspacesPoliciesSimulateListResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *WorkspacesPoliciesSimulateListResponse) GetPaginatedPolicyDecisionLogList() *components.PaginatedPolicyDecisionLogList {
	if o == nil {
		return nil
	}
	return o.PaginatedPolicyDecisionLogList
}
