// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4a53e9cdb5fc

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type WorkspacesPoliciesUpdateRequest struct {
	// The `slug_perm` (identifier) of the Policy.
	Policy string `pathParam:"style=simple,explode=false,name=policy"`
	// The `name` of the Workspace.
	Workspace string                  `pathParam:"style=simple,explode=false,name=workspace"`
	Body      components.PolicyInput1 `request:"mediaType=application/json"`
}

func (o *WorkspacesPoliciesUpdateRequest) GetPolicy() string {
	if o == nil {
		return ""
	}
	return o.Policy
}

func (o *WorkspacesPoliciesUpdateRequest) GetWorkspace() string {
	if o == nil {
		return ""
	}
	return o.Workspace
}

func (o *WorkspacesPoliciesUpdateRequest) GetBody() components.PolicyInput1 {
	if o == nil {
		return components.PolicyInput1{}
	}
	return o.Body
}

type WorkspacesPoliciesUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Policy   *components.Policy
}

func (o *WorkspacesPoliciesUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *WorkspacesPoliciesUpdateResponse) GetPolicy() *components.Policy {
	if o == nil {
		return nil
	}
	return o.Policy
}
