// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 068d29151cd4

package assert

// Pointer returns a pointer to the given value.
//
// This is intended to simplify inline builtin value expressions that are not
// implemented in the Go language specification, such as a hypothetical
// &"example".
func Pointer[T any](v T) *T {
	return &v
}
