// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: bc4818c1c5f8

package server

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"mockserver/internal/logging"
	"mockserver/internal/tracking"
	"net/http"
	"strings"
	"time"

	"github.com/gorilla/mux"
)

const (
	// Default address for server listening.
	DefaultAddress = ":18080"
)

// Server implements the HTTP server.
type Server struct {
	// Address for server listening.
	address string

	// Directory for raw HTTP request and response files.
	httpFileDir *logging.HTTPFileDirectory

	// Logger implementation.
	logger *slog.Logger

	// Underlying mux implementation.
	// Based on gorilla mux as the native mux suffered from issues with ambiguous paths and different http methods
	// eg - panic: pattern "HEAD /v8/artifacts/{hash}" (registered at /usr/src/app/internal/server/server.go:104) conflicts with pattern "GET /v8/artifacts/status" (registered at /usr/src/app/internal/server/server.go:104): HEAD /v8/artifacts/{hash} matches fewer methods than GET /v8/artifacts/status, but has a more general path pattern
	mux *mux.Router

	// Underlying server implementation.
	server *http.Server

	requestTracker *tracking.RequestTracker
}

// NewServer creates a new Server instance.
func NewServer(ctx context.Context, opts ...ServerOption) (*Server, error) {
	// Initialize with defaults.
	result := &Server{
		address:        DefaultAddress,
		logger:         slog.Default(),
		mux:            mux.NewRouter(),
		requestTracker: tracking.New(),
	}

	// Customize based on ServerOption.
	for _, opt := range opts {
		err := opt(result)

		if err != nil {
			return result, err
		}
	}

	result.server = &http.Server{
		Addr:     result.address,
		Handler:  logging.HTTPLoggerHandler(result.logger, stripV2Prefix(result.mux)),
		ErrorLog: slog.NewLogLogger(result.logger.Handler(), slog.LevelError),
	}

	httpFileDir, err := logging.NewHTTPFileDirectory("")

	if err != nil {
		return result, err
	}

	err = httpFileDir.Clean()

	if err != nil {
		return result, err
	}

	result.httpFileDir = httpFileDir

	result.registerGeneratedHandlers(ctx)
	result.registerInternalHandlers(ctx)

	return result, err
}

// Address returns the server address including protocol, hostname, and port.
func (s *Server) Address() string {
	return "http://localhost" + s.address
}

// RegisterHandlerFunc adds a new HTTP handler function for the given methods and path.
func (s *Server) RegisterHandlerFunc(ctx context.Context, methods []string, path string, handlerFunc http.HandlerFunc) {
	s.logger.DebugContext(ctx, fmt.Sprintf("registering handler for %s %s", strings.Join(methods, ", "), path))

	r := s.mux.HandleFunc(path, handlerFunc)
	if len(methods) > 0 {
		r.Methods(methods...)
	}
}

// Serve starts the server.
func (s *Server) Serve(ctx context.Context) error {
	s.logger.InfoContext(ctx, "starting server with address "+s.server.Addr)

	err := s.server.ListenAndServe()

	if errors.Is(err, http.ErrServerClosed) {
		return nil
	}

	return fmt.Errorf("error running server: %w", err)
}

// stripV2Prefix lets the mock accept the /v2-anchored URLs the SDK produces
// (the SDK normalizes every server URL to end in /v2/) while the generated
// handlers remain registered at the OpenAPI operation paths (root-relative).
// A bare "/v2" maps to "/"; "/v2/..." maps to "/..."; anything else is left
// untouched so root-relative requests still match.
func stripV2Prefix(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch {
		case r.URL.Path == "/v2":
			r.URL.Path = "/"
		case strings.HasPrefix(r.URL.Path, "/v2/"):
			r.URL.Path = strings.TrimPrefix(r.URL.Path, "/v2")
		}
		next.ServeHTTP(w, r)
	})
}

// Shutdown gracefully stops the server.
func (s *Server) Shutdown(ctx context.Context) error {
	s.logger.WarnContext(ctx, "shutting down server")
	s.server.SetKeepAlivesEnabled(false)

	ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()

	err := s.server.Shutdown(ctx)

	if err != nil {
		return fmt.Errorf("error shutting down server: %w", err)
	}

	return nil
}
